# Basic Pitch Onset-Threshold Sweep — tuned by tab accuracy

Standalone companion to **`AudioToTabCAGED (2).ipynb`**. It sweeps the Basic Pitch `onset_threshold` (and `frame_threshold`) that your pipeline currently leaves at the library default, selects the best value **on the validation split by `exact_tab_f1`**, then reports on the test split **once**.

### Why this is worth doing
Your `run_basic_pitch_notes` calls `basic_pitch_predict(audio_path)` with Basic Pitch's *default* onset/frame thresholds, then post-filters notes by their `amplitude` field. Your team tuned that **amplitude** post-filter (0.30 → 0.40). The **onset_threshold inside `predict()`** is a separate, never-swept knob — a threshold sweep on a held-out player showed note-F1 climbing meaningfully from the 0.40-equivalent operating point up toward ~0.60-0.65. This notebook checks whether that helps the thing you actually care about: **end-to-end tab F1**, not note F1.

### How it plugs in
It runs your real notebook with `%run` to import every function unchanged (`evaluate_audio_to_tab_record`, `AUDIO_ASSIGNMENT_METHODS`, `VAL_RECORDS`, `TEST_RECORDS`, `find_audio_for_record`, `basic_pitch_predict`, …), then **monkey-patches only `run_basic_pitch_notes`** to (a) pass `onset_threshold`/`frame_threshold` into `basic_pitch_predict` and (b) use a **threshold-aware cache key** so the sweep never serves stale notes from a different threshold. Nothing in your algorithm changes.

### Discipline baked in
- Tune on `VAL_RECORDS`, report on `TEST_RECORDS` exactly once.
- Select by `exact_tab_f1` (end-to-end). `tab_accuracy_given_pitch_match` (TDR) is assignment-only and barely moves with detection threshold, so it is the wrong selection target — shown for context only.
- Playability columns are printed at the winning threshold so a precision shift that quietly worsens fret jumps doesn't slip through.

## 1. Mount Drive + point to your notebook

In [3]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

# EDIT if your path differs. This is the self-contained algorithm notebook with chord voicings.
PIPELINE_NB = '/content/drive/MyDrive/Capstone/Code/AudioToTabCAGED.ipynb'
assert Path(PIPELINE_NB).exists(), f"Not found: {PIPELINE_NB}  — fix PIPELINE_NB to point at your notebook."
print("Pipeline notebook:", PIPELINE_NB)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Pipeline notebook: /content/drive/MyDrive/Capstone/Code/AudioToTabCAGED.ipynb

## 2. Run your pipeline to import everything

`%run` executes the notebook in this namespace, so all functions, configs, and the `TRAIN/VAL/TEST` split land here exactly as defined there. This runs its end-to-end TEST eval too (cell 46) — a few minutes; harmless, it just warms the note cache. Set `MAX_AUDIO_RECORDINGS` small in your config first if you want it faster.

In [4]:
%run "$PIPELINE_NB"

# Sanity-check the symbols we depend on all exist.
_needed = ['run_basic_pitch_notes','basic_pitch_predict','evaluate_audio_to_tab_record',
           'AUDIO_ASSIGNMENT_METHODS','VAL_RECORDS','TEST_RECORDS','find_audio_for_record',
           'BASIC_PITCH_CACHE_DIR','BASIC_PITCH_AMPLITUDE_THRESHOLD','BASIC_PITCH_MIN_MIDI',
           'BASIC_PITCH_MAX_MIDI','make_audio_record_from_gt']
_missing = [n for n in _needed if n not in dir()]
assert not _missing, f"Missing symbols after %run: {_missing}"
print("All required symbols present. VAL:", len(VAL_RECORDS), "TEST:", len(TEST_RECORDS))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Google Drive mounted successfully.
OUTPUT_DIR: /content/drive/MyDrive/Capstone/outputs/fretboard_playability
OUTPUT_DIR exists: True

Data root candidates visible to this runtime:
 - /content/drive/MyDrive/Capstone/FullGuitarSetData | exists: True
 - /content/drive/MyDrive/FullGuitarSetData | exists: False
 - /content/drive/MyDrive/Capstone/GuitarSet | exists: True
 - /content/drive/MyDrive/GuitarSet | exists: False
 - /content/drive/MyDrive/Capstone | exists: True
 - /content/drive/MyDrive | exists: True
 - /mnt/data/fretwork_repo/GuitarSet | exists: False
 - /mnt/data/fretwork_repo | exists: False

Top-level MyDrive folders/files visible to Colab:
 - labels.csv
 - yelp_dataset.tar
 - Spring 2025
 - Tell a compelling story. Example. Fall 2020. Airline Pricing.gdoc
 - DATASCI200 Project Proposal.gdoc
 - personalized bus routes.fall 2024.gdoc
 - Final Report Template.gdoc
 - Data 201 Final Project Deliverable 2 (WORKING COPY).gdoc
 - Guitar Idea.gdoc
 - Lab 1.gdoc
 - Peer Review.gdoc
 - Lab 2 Proposal.gdoc
 - 203 Lab 3 Intro.gdoc
 - MIDS 207 Project
 - Colab Notebooks
 - HW3.csv
 - HW3.gsheet
 - EuroSAT
 - Exam_Tm.csv
 - Exam_Ts.csv
 - Exam_Tm.gsheet
 - Exam_Ts.gsheet
 - Week_10_student_exercise_Tanya.ipynb
 - Week10_CNN_1D_Tanya.ipynb
 - Ani_09 Embeddings for Text.ipynb
Fretboard rows: 150

    string string_name  fret  midi  pitch_class
0        0       low_E     0    40            4
1        0       low_E     1    41            5
2        0       low_E     2    42            6
3        0       low_E     3    43            7
4        0       low_E     4    44            8
5        0       low_E     5    45            9
6        0       low_E     6    46           10
7        0       low_E     7    47           11
8        0       low_E     8    48            0
9        0       low_E     9    49            1
10       0       low_E    10    50            2
11       0       low_E    11    51            3

Example positions for MIDI 64 / E4:

   string string_name  fret  midi  pitch_class
0       0       low_E    24    64            4
1       1           A    19    64            4
2       2           D    14    64            4
3       3           G     9    64            4
4       4           B     5    64            4
5       5      high_E     0    64            4

        key root  root_pc   mode               scale_pcs                 scale_notes                                    diatonic_chords
0   C major    C        0  major  [0, 2, 4, 5, 7, 9, 11]       [C, D, E, F, G, A, B]  [{'degree': 1, 'root_pc': 0, 'root': 'C', 'qua...
1   C minor    C        0  minor  [0, 2, 3, 5, 7, 8, 10]    [C, D, D#, F, G, G#, A#]  [{'degree': 1, 'root_pc': 0, 'root': 'C', 'qua...
2  C# major   C#        1  major  [1, 3, 5, 6, 8, 10, 0]  [C#, D#, F, F#, G#, A#, C]  [{'degree': 1, 'root_pc': 1, 'root': 'C#', 'qu...
3  C# minor   C#        1  minor  [1, 3, 4, 6, 8, 9, 11]   [C#, D#, E, F#, G#, A, B]  [{'degree': 1, 'root_pc': 1, 'root': 'C#', 'qu...
4   D major    D        2  major  [2, 4, 6, 7, 9, 11, 1]     [D, E, F#, G, A, B, C#]  [{'degree': 1, 'root_pc': 2, 'root': 'D', 'qua...

D major diatonic chords:
['D:maj', 'E:min', 'F#:min', 'G:maj', 'A:maj', 'B:min', 'C#:dim']
{'root': 'D', 'root_pc': 2, 'quality': 'maj', 'tones': [2, 6, 9]}
{'symbol': 'D:maj', 'root_pc': 2, 'quality': 'maj', 'tones': [2, 6, 9], 'score': 0.9999999995}
DATA_ROOT selected: /content/drive/MyDrive/Capstone/FullGuitarSetData
Found 360 JAMS files in /content/drive/MyDrive/Capstone/FullGuitarSetData/JamsFiles
00_BN1-129-Eb_comp.jams
00_BN1-129-Eb_solo.jams
00_BN1-147-Gb_comp.jams
00_BN1-147-Gb_solo.jams
00_BN2-131-B_comp.jams
00_BN2-131-B_solo.jams
00_BN2-166-Ab_comp.jams
00_BN2-166-Ab_solo.jams
00_BN3-119-G_comp.jams
00_BN3-119-G_solo.jams
Parsed records: 360
Example record: 00_BN1-129-Eb_comp
Notes: 133 Chords: 12 Key: Eb:major

      start  duration  midi  pitch_class  true_string  true_fret source
0  0.048816  0.423764    51            3            1          6      1
1  0.049791  0.452789    65            5            4          6      4
2  0.052717  0.458594    62            2            3          7      3
3  0.519995  0.417959    51            3            1          6      1
4  0.722036  0.859138    58           10            2          8      2

Held-out split by recording:
  Train records: 252
  Validation records: 54
  Test records: 54
  Total records: 360
Saved split file to: /content/drive/MyDrive/Capstone/outputs/fretboard_playability/fretboard_train_val_test_split.csv

        split  is_solo  is_comp  recordings  notes
0        test    False     True          27   7364
1        test     True    False          27   2843
2       train    False     True         126  31543
3       train     True    False         126  11572
4  validation    False     True          27   6708
5  validation     True    False          27   2446

      start  duration  midi  pitch_class  true_string  true_fret source key_label in_key chord_label  in_chord
0  0.048816  0.423764    51            3            1          6      1  Eb:major   None      D#:maj      True
1  0.049791  0.452789    65            5            4          6      4  Eb:major   None      D#:maj     False
2  0.052717  0.458594    62            2            3          7      3  Eb:major   None      D#:maj     False
3  0.519995  0.417959    51            3            1          6      1  Eb:major   None      D#:maj      True
4  0.722036  0.859138    58           10            2          8      2  Eb:major   None      D#:maj      True

Number of onset groups: 76
First group size: 3
First group candidates: 25
old_music_theory_greedy: produced 50 predictions
viterbi_original: produced 50 predictions
combined_all: produced 50 predictions
Built empirical position prior from 252 training records for 150 MIDI/string/fret candidates.
Tuned combined-all functions defined. Weight tuning will run after evaluation helpers are defined.
Running lightweight tuning search over preset weights on validation records...

   exact_position_acc  avg_fret_error  avg_fret_jump  large_jump_rate  duplicate_string_violation_rate  objective  preset_id  n_tuning_records
1            0.717002        1.353353       1.029694         0.000843                              0.0   0.649039          1                24
0            0.714173        1.369699       1.019322         0.000843                              0.0   0.645393          0                24
3            0.710572        1.384967       1.019380         0.000843                              0.0   0.641028          3                24
2            0.699138        1.433684       1.012600         0.000843                              0.0   0.627159          2                24

Selected tuned preset: 1
Selected weights: {'playability': 0.6, 'context': 0.35, 'old_theory': 0.35, 'position_prior': 1.4, 'hand_shift': 1.05, 'string_shift': 0.22, 'single_fret_shift': 0.55, 'single_string_shift': 0.3, 'large_jump_extra': 4.5, 'open_after_high_extra': 2.25, 'group_span_extra': 0.15}
Saved tuning results to: /content/drive/MyDrive/Capstone/outputs/fretboard_playability/fretboard_tuning_results_validation.csv
combined_all_tuned smoke test: produced 50 predictions
Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

$ /usr/bin/python3 -m pip install -q --upgrade pip wheel setuptools==80.9.0

$ /usr/bin/python3 -m pip install -q librosa>=0.10 soundfile mir-eval pretty_midi resampy==0.4.2 onnxruntime

$ /usr/bin/python3 -m pip install -q --no-deps basic-pitch==0.4.0

WARNING:root:Coremltools is not installed. If you plan to use a CoreML Saved Model, reinstall basic-pitch with `pip install 'basic-pitch[coreml]'`
WARNING:root:tflite-runtime is not installed. If you plan to use a TFLite Model, reinstall basic-pitch with `pip install 'basic-pitch tflite-runtime'` or `pip install 'basic-pitch[tf]'

✅ Basic Pitch import successful.
✅ librosa: 0.11.0
✅ soundfile import successful.
✅ onnxruntime installed.
AUDIO_OUTPUT_DIR: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout

Audio root candidates:
 - /content/drive/MyDrive/Capstone/GuitarSet/Audio | exists: True
 - /content/drive/MyDrive/Capstone/GuitarSet/AudioFiles | exists: False
 - /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles | exists: True
 - /content/drive/MyDrive/Capstone/FullGuitarSetData/Audio | exists: False
 - /content/drive/MyDrive/Capstone/Audio | exists: True
 - /content/drive/MyDrive/Capstone/GuitarSet | exists: True
 - /content/drive/MyDrive/Capstone | exists: True
 - /content/drive/MyDrive/GuitarSet/Audio | exists: False
 - /content/drive/MyDrive/GuitarSet | exists: False

Final eval split:
USE_HELDOUT_SPLIT: True
TEST_RECORDS: 54
Found 636 audio files.
 - 00_BN1-129-Eb_comp_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_BN1-129-Eb_comp_mic.wav
 - 00_Jazz1-130-D_solo_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Jazz1-130-D_solo_mic.wav
 - 00_Funk1-97-C_solo_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Funk1-97-C_solo_mic.wav
 - 00_Funk1-97-C_comp_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Funk1-97-C_comp_mic.wav
 - 00_Rock1-90-C#_comp_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Rock1-90-C#_comp_mic.wav
 - 00_Rock1-90-C#_solo_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Rock1-90-C#_solo_mic.wav
 - 00_Jazz1-130-D_comp_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Jazz1-130-D_comp_mic.wav
 - 00_SS1-68-E_solo_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_SS1-68-E_solo_mic.wav
 - 00_SS1-68-E_comp_mic -> /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_SS1-68-E_comp_mic.wav
 - 00_BN1-129-Eb_solo_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-129-Eb_solo_mic.wav
 - 00_Funk1-114-Ab_comp_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk1-114-Ab_comp_mic.wav
 - 00_Jazz3-150-C_solo_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-150-C_solo_mic.wav
 - 00_Funk3-98-A_comp_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk3-98-A_comp_mic.wav
 - 00_Jazz2-187-F#_comp_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz2-187-F#_comp_mic.wav
 - 00_Funk2-108-Eb_comp_mic -> /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk2-108-Eb_comp_mic.wav
Audio eval set: heldout_test_audio
Paired 54 / 54 eval records with audio files.
 - 02_BN2-131-B_solo -> 02_BN2-131-B_solo_mic.wav
 - 00_Rock2-142-D_comp -> 00_Rock2-142-D_comp_mic.wav
 - 05_Rock2-85-F_solo -> 05_Rock2-85-F_solo_mic.wav
 - 04_Jazz3-137-Eb_comp -> 04_Jazz3-137-Eb_comp_mic.wav
 - 05_SS2-88-F_solo -> 05_SS2-88-F_solo_mic.wav
 - 01_SS1-100-C#_comp -> 01_SS1-100-C#_comp_mic.wav
 - 04_Funk2-119-G_solo -> 04_Funk2-119-G_solo_mic.wav
 - 00_SS2-107-Ab_solo -> 00_SS2-107-Ab_solo_mic.wav
 - 01_BN2-131-B_comp -> 01_BN2-131-B_comp_mic.wav
 - 04_BN3-119-G_comp -> 04_BN3-119-G_comp_mic.wav
 - 03_Jazz3-150-C_solo -> 03_Jazz3-150-C_solo_mic.wav
 - 03_Rock3-117-Bb_comp -> 03_Rock3-117-Bb_comp_mic.wav
 - 05_BN1-147-Gb_solo -> 05_BN1-147-Gb_solo_mic.wav
 - 04_Rock1-90-C#_solo -> 04_Rock1-90-C#_solo_mic.wav
 - 01_SS1-68-E_solo -> 01_SS1-68-E_solo_mic.wav
CAGED-box eval ready -> add "caged_box": assign_caged_box_eval to AUDIO_ASSIGNMENT_METHODS
caged_voiced ready. VOICING_SHAPES: 21 | weight: 1.0
Running held-out audio-to-tab evaluation on 54 recordings from heldout_test_audio.
Basic Pitch amplitude threshold: 0.3
Onset match tolerance: 0.05 sec
GT key context: False; GT chord context: False
Audio key detection: True; Audio chord detection: True

Recording: 02_BN2-131-B_solo | audio: 02_BN2-131-B_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Rock2-142-D_comp | audio: 00_Rock2-142-D_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_Rock2-85-F_solo | audio: 05_Rock2-85-F_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Jazz3-137-Eb_comp | audio: 04_Jazz3-137-Eb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_SS2-88-F_solo | audio: 05_SS2-88-F_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_SS1-100-C#_comp | audio: 01_SS1-100-C#_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Funk2-119-G_solo | audio: 04_Funk2-119-G_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_SS2-107-Ab_solo | audio: 00_SS2-107-Ab_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_BN2-131-B_comp | audio: 01_BN2-131-B_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_BN3-119-G_comp | audio: 04_BN3-119-G_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_Jazz3-150-C_solo | audio: 03_Jazz3-150-C_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_Rock3-117-Bb_comp | audio: 03_Rock3-117-Bb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_BN1-147-Gb_solo | audio: 05_BN1-147-Gb_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Rock1-90-C#_solo | audio: 04_Rock1-90-C#_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_SS1-68-E_solo | audio: 01_SS1-68-E_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_BN1-129-Eb_solo | audio: 05_BN1-129-Eb_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_Rock1-130-A_solo | audio: 03_Rock1-130-A_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_SS2-107-Ab_solo | audio: 01_SS2-107-Ab_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_BN3-154-E_solo | audio: 01_BN3-154-E_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Funk1-97-C_solo | audio: 00_Funk1-97-C_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_SS1-68-E_comp | audio: 03_SS1-68-E_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 02_Rock1-90-C#_comp | audio: 02_Rock1-90-C#_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 02_Funk3-112-C#_solo | audio: 02_Funk3-112-C#_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_Jazz1-200-B_solo | audio: 05_Jazz1-200-B_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_SS1-68-E_comp | audio: 04_SS1-68-E_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Rock3-148-C_solo | audio: 04_Rock3-148-C_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_Rock3-117-Bb_comp | audio: 05_Rock3-117-Bb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Rock3-148-C_solo | audio: 00_Rock3-148-C_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_Jazz1-130-D_comp | audio: 03_Jazz1-130-D_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Rock1-130-A_comp | audio: 04_Rock1-130-A_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_BN3-154-E_comp | audio: 05_BN3-154-E_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_Jazz1-130-D_comp | audio: 01_Jazz1-130-D_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 02_Funk1-97-C_comp | audio: 02_Funk1-97-C_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Rock2-85-F_comp | audio: 00_Rock2-85-F_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_Rock2-142-D_solo | audio: 01_Rock2-142-D_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_Rock1-130-A_comp | audio: 03_Rock1-130-A_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_Rock1-130-A_comp | audio: 05_Rock1-130-A_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Jazz3-150-C_comp | audio: 00_Jazz3-150-C_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_Rock2-85-F_comp | audio: 01_Rock2-85-F_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Jazz2-187-F#_comp | audio: 04_Jazz2-187-F#_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 05_BN3-119-G_solo | audio: 05_BN3-119-G_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Jazz1-130-D_comp | audio: 04_Jazz1-130-D_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_SS3-98-C_solo | audio: 01_SS3-98-C_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_SS3-84-Bb_solo | audio: 00_SS3-84-Bb_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_BN1-147-Gb_comp | audio: 04_BN1-147-Gb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 04_Rock2-142-D_comp | audio: 04_Rock2-142-D_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_SS2-88-F_solo | audio: 01_SS2-88-F_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Funk1-114-Ab_solo | audio: 00_Funk1-114-Ab_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_SS1-100-C#_solo | audio: 03_SS1-100-C#_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 02_BN1-147-Gb_comp | audio: 02_BN1-147-Gb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 01_BN1-129-Eb_comp | audio: 01_BN1-129-Eb_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Rock3-117-Bb_solo | audio: 00_Rock3-117-Bb_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 00_Funk2-108-Eb_solo | audio: 00_Funk2-108-Eb_solo_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Recording: 03_BN3-154-E_comp | audio: 03_BN3-154-E_comp_mic.wav
  - caged_box
  - caged_voiced
  - combined_all_tuned

Saved audio outputs:
 - /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_eval_by_recording.csv
 - /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_eval_summary.csv
 - /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_predictions_all.csv
 - /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_matches.csv
 - /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_failed_runs.csv

Audio-to-tab summary:

,method,recordings,n_gt_notes,n_basic_pitch_notes,n_pitch_onset_matches,pitch_precision,pitch_recall,pitch_f1,exact_tab_precision,exact_tab_recall,exact_tab_f1,tab_accuracy_given_pitch_match,string_accuracy_given_pitch_match,fret_accuracy_given_pitch_match,mean_runtime_sec_per_recording
1,caged_voiced,54,10207,9561,7668,0.802,0.7512,0.7758,0.5549,0.5197,0.5367,0.6918,0.6918,0.6918,0.7057
0,caged_box,54,10207,9561,7668,0.802,0.7512,0.7758,0.5497,0.5149,0.5318,0.6854,0.6854,0.6854,1.8391
2,combined_all_tuned,54,10207,9561,7668,0.802,0.7512,0.7758,0.5191,0.4862,0.5021,0.6472,0.6472,0.6472,0.7478

=== Position accuracy by solo vs comp ===

               method segment  recordings  n_gt_notes  n_pitch_matches  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
0           caged_box    comp          27        7364             5252        0.7132        0.5454                          0.7199
2        caged_voiced    comp          27        7364             5252        0.7132        0.5536                          0.7308
4  combined_all_tuned    comp          27        7364             5252        0.7132        0.5059                          0.6677
1           caged_box    solo          27        2843             2416        0.8498        0.4997                          0.6105
3        caged_voiced    solo          27        2843             2416        0.8498        0.4970                          0.6072
5  combined_all_tuned    solo          27        2843             2416        0.8498        0.4933                          0.6026

=== Among WRONG-string notes: distribution of |pred_string - true_string| ===

string_err                      1      2      3      4      5
method             segment
caged_box          comp     0.978  0.020  0.002  0.000  0.001
                   solo     0.926  0.063  0.012  0.000  0.000
caged_voiced       comp     0.979  0.018  0.002  0.000  0.001
                   solo     0.926  0.062  0.012  0.000  0.000
combined_all_tuned comp     0.978  0.017  0.003  0.001  0.001
                   solo     0.952  0.045  0.003  0.000  0.000

========================================================================================
Recording: 00_Funk1-114-Ab_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
143          58                   69                     47           0.6812        0.8103        0.5197                          0.7021

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Funk1-114-Ab_solo — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|4-----4-----------------|------------------------|------------------------|------------------------|
G|------------4--4--1-----|------4--4--------------|------------4-----------|------------------------|
D|------------------------|---6-----------3--4--3--|---------6--------1-----|---3--4--6--8--9--8--6--|
A|6-----------2--3--6-----|------------6-----------|6-----------2--3--------|------------------------|
E|---------4--------4-----|---4--7--7--------------|---------4--------------|------------------------|

e|------------------------|------4-----------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|---------------4--3-----|------------------6-----|------------------------|
A|---------6--8-----------|------------------------|6-----------4--3--------|------------------------|
E|------------------------|------------------------|------------------4-----|------------4--4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|5--------------5--------|------3-----------------|------------------------|------------------4--6--|
D|3--------------3--------|------------------6-----|---------------4-----6--|6-----------------------|
A|------4-----------------|6-----8-----------------|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Funk1-114-Ab_solo
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------6-----|------------------------|------------------------|---------6--8--9--8--6--|
A|6-----------------6-----|------------6--8--9--8--|6-----------------6-----|---8--9-----------------|
E|---------4--7--8--------|---4--7--7--------------|---------4--7--8--------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|------------------------|------------------------|------------------------|
A|---------6--8-----------|---------------9--8-----|6--------6--4--3--------|------------------------|
E|------------------------|---------------------8--|------------------4-----|---------------4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|1-----------------------|------------------6-----|
D|------------------------|------8-----------6-----|---------------4--17-18-|6-----------------------|
A|------4-----------------|6-----8-----------6-----|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 4 same-grid-cell collisions; later note shown]

========================================================================================
MATCHED-NOTE-ONLY VIEW: REAL AUDIO PREDICTED
========================================================================================
MATCHED ONLY: REAL AUDIO PREDICTED TAB — 00_Funk1-114-Ab_solo — combined_all_tuned
--------------------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------1-----|------------------------|------------------------|------------------------|
D|------------------------|---------------3--4--3--|------------------1-----|---3--4--6--8--9--8--6--|
A|6-----------2--3--6-----|------------6-----------|6-----------2--3--------|------------------------|
E|---------4--------------|---4--7--7--------------|---------4--------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|---------------4--3-----|------------------------|------------------------|
A|---------6--8-----------|------------------------|6-----------4--3--------|------------------------|
E|------------------------|------------------------|------------------4-----|---------------4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------3-----------------|------------------------|------------------4--6--|
D|------------------------|------------------6-----|------------------------|6-----------------------|
A|------4-----------------|------8-----------------|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


========================================================================================
MATCHED-NOTE-ONLY VIEW: GROUND TRUTH
========================================================================================
MATCHED ONLY: GROUND TRUTH TAB — 00_Funk1-114-Ab_solo — combined_all_tuned
--------------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------6-----|------------------------|------------------------|---------6--8--9--8--6--|
A|6-----------------6-----|------------6--8--9--8--|6-----------------6-----|---8--9-----------------|
E|---------4--7--8--------|---4--7--7--------------|---------4--7--8--------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|------------------------|------------------------|------------------------|
A|---------6--8-----------|---------------9--8-----|6-----------4--3--------|------------------------|
E|------------------------|------------------------|------------------4-----|---------------4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------6-----|
D|------------------------|------8-----------6-----|------------------------|6-----------------------|
A|------4-----------------|------8-----------------|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__ground_truth_midi_tab.txt
 - matched_only_real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__matched_only_real_audio_predicted_tab.txt
 - matched_only_ground_truth_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__matched_only_ground_truth_tab.txt
========================================================================================
Recording: 00_Funk1-114-Ab_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
143          58                   69                     47           0.6812        0.8103        0.5197                          0.7021

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Funk1-114-Ab_solo — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|4-----4-----------------|------------------------|------------------------|------------------------|
G|------------4--4--1-----|------4--4--------------|------------4-----------|------------------------|
D|------------------------|---6-----------3--4--3--|---------6--------1-----|---3--4--6--8--9--8--6--|
A|6-----------2--3--6-----|------------6-----------|6-----------2--3--------|------------------------|
E|---------4--------4-----|---4--7--7--------------|---------4--------------|------------------------|

e|------------------------|------4-----------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|---------------4--3-----|------------------6-----|------------------------|
A|---------6--8-----------|------------------------|6-----------4--3--------|------------------------|
E|------------------------|------------------------|------------------4-----|------------4--4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|5--------------5--------|------3-----------------|------------------------|------------------4--6--|
D|3--------------3--------|------------------6-----|---------------4-----6--|6-----------------------|
A|------4-----------------|6-----8-----------------|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Funk1-114-Ab_solo
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------6-----|------------------------|------------------------|---------6--8--9--8--6--|
A|6-----------------6-----|------------6--8--9--8--|6-----------------6-----|---8--9-----------------|
E|---------4--7--8--------|---4--7--7--------------|---------4--7--8--------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|8--------------6--------|------------------------|------------------------|------------------------|
A|---------6--8-----------|---------------9--8-----|6--------6--4--3--------|------------------------|
E|------------------------|---------------------8--|------------------4-----|---------------4--3--2--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|1-----------------------|------------------6-----|
D|------------------------|------8-----------6-----|---------------4--17-18-|6-----------------------|
A|------4-----------------|6-----8-----------6-----|------------------------|------------------------|
E|1--------------1--------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 4 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-114-Ab_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Funk1-97-C_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
59          62                   79                     54           0.6835         0.871        0.4113                           0.537

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Funk1-97-C_solo — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------6--5--------------|------6--5--------------|------6--5-----5--3--3--|3-----------------------|
D|---------0--------------|---------0--------------|---------0-----0--------|------------------------|
A|---6--6-----------------|---6--6-----------------|---6--6-----------3-----|3-----------------------|
E|------------------------|------------------------|5--4--------------------|------------------------|

e|---------21-------------|---------21-------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------8--6-----5--------|---------------5--4--3--|
D|---0--7-----------------|------------------------|------3--6-----0--------|------------------------|
A|------3-----------------|------------------------|---5-----6--5-----------|------------------0-----|
E|5--5-----17-------------|---5--8--17-------------|5--------------0--------|------------------------|

e|------------------3--3--|------------------------|---------------21-------|------------------------|
B|------------------------|---------6--------------|---8--------------------|------------------------|
G|4--3--4--4--------------|---3-----5--------------|4-----------------------|------------------------|
D|5-----5-----------------|5-----5--5--------------|5-----8-----------------|---6--5--3--2--3--2-----|
A|------------------------|------------------------|------------12----11----|10----------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Funk1-97-C_solo
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------6--5--------------|------6--5--------------|------6-----5--5--3--3--|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|---6-----5--------------|---6-----5--------------|---6-----6--5-----3-----|3-----------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------2--2--------------|---------2--------------|---5--8--6--5-----------|---------------5--4--3--|
D|------------------------|------------------------|---------6--------------|------------------------|
A|---0--3-----------------|---0--3-----------------|---5--8--6--5-----------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------1--------------|------------------------|------------------------|
B|0--------0--------------|---------1--------------|0-----------------------|------------------------|
G|0--3--0-----------------|0--3--0-----------------|0-----3-----2-----1-----|0--1--0-----------------|
D|------------------------|------------------------|------------------------|---------3--2--3--2--0--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-97-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk1-97-C_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Funk2-108-Eb_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
158         121                  125                     89            0.712        0.7355        0.5366                          0.7416

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Funk2-108-Eb_solo — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|6-----------------------|------------------------|---------------4--------|------------------------|
G|4-----------------------|---------3--------------|------------------------|------4-----------------|
D|------------------------|---------------6--------|---------------------4--|4-----------------------|
A|8--------6--4--------2--|1--2--4--------------4--|2--------1--------------|------2-----------------|
E|------------------------|---------6-----4--------|------------4--------2--|2--4-----4--------2-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|4-----------------------|------------------------|------------------------|
G|---------4--3-----3-----|------4-----4-----------|------------------------|------------------------|
D|---------------------8--|6--4--4-----------4--6--|7--------8-----8-----9--|---------9--9-----8--8--|
A|---------------------6--|6--------6--9--6--------|------------------------|------------------------|
E|2--4--6--7--6--4--6--6--|4-----------------------|------------------------|------------------------|

e|22----------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------------6--4-----|---------------6--4-----|6--4-----4--3--4--3-----|------------------------|
D|---8--8-----8--------6--|8--8--8--8-----------6--|8-----8-----6-----6--6--|8--9--6--4-----------4--|
A|------------------------|------------------------|------------------------|------------------------|
E|18----------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---6--------------------|6--------------6--------|------6-----------------|------------6-----------|
G|---------3--------------|------------------------|------------------------|------------------------|
D|4--3--4--------6-----4--|3-----3--4-----3-----4--|3-----------------------|------------3--4--6-----|
A|------------------------|---6--------------6-----|---------4--6-----------|---------6--------------|
E|------------------------|------------------------|5-----------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 7 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Funk2-108-Eb_solo
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|8--------6--4-----------|------4--------------4--|------------------------|------2-----------------|
E|---------------------7--|6--7-----6-----4--6--7--|7--------6--4--------2--|2--4-----4--------2-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|2-----------------------|---------4--4-----3--3--|
D|------------------------|6--4--4--1--4-----4--6--|8-----------------------|------------------------|
A|---------------------6--|6--------6-----6--------|------------------------|------------------------|
E|2--4--5--7-----4--6-----|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|3--3--3--3--3--6--4-----|3--3--3--3-----6--4-----|3--4--3--4--3--3--3--4--|3-----4-----------------|
D|---------------------6--|---------------------6--|------6-----6-----6-----|6-----6--4--------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------3--------------|------------------------|------------------------|------------------------|
D|4--3--4--------6-----4--|3-----3--4-----3-----4--|3-----------------------|---------1--3--4--6-----|
A|------------------------|---6--------------6-----|---------4--6-----------|---------6--------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 25 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk2-108-Eb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Funk2-108-Eb_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Jazz3-150-C_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
113         252                  208                    171           0.8221        0.6786        0.4304                          0.5789

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Jazz3-150-C_comp — combined_all_tuned
-------------------------------------------------------------------
e|------12-------12----10-|---22-------------------|------8--------20----8--|------------------------|
B|------12-------12-------|7--15-------------------|1-----5--------13-------|------8-----8-----8-----|
G|------12-------12-------|7--16-7-----7-----------|0-----5--------0-----9--|------------7-----------|
D|------10----------------|---16-5-----5--------2--|2-----5--------14----10-|---9--9-----9-----9-----|
A|---------------10-------|------------------------|0--------------15----10-|---7--------------7-----|
E|------------------------|---------------3--------|---------5--------------|---------------------5--|

e|5-----5--------8-----8--|20-8--------8--------8--|5-----5-----5-----5--8--|---10----10----------5--|
B|5-----5--------10-------|---8--------8-----------|5-----5-----5-----5--10-|---10----0-----6--6--6--|
G|5-----5--------9-----9--|---9--------9-----9-----|------5-----5-----5--9--|---10----10----4--4-----|
D|---------------10-------|10-10-------10----------|------3-----------3--10-|---------5--------5--5--|
A|---------------------10-|---10-10----10----------|------------------------|------------------------|
E|---------------------8--|------------8-----------|------------------1-----|------------------------|

e|------------------5-----|5-----------7-----------|------5--------5-----7--|---7--------------------|
B|------------5-----5-----|5-----------7-----------|------5--------5-----8--|---8--------8-----------|
G|------5-----5-----5-----|5-----------7-----------|------5--------5-----4--|---9--9-----------12----|
D|------5-----------------|------5-----------------|------5--------7--5--5--|---9--9-----9-----9-----|
A|---3--------------------|------------------------|7--------------0--------|7--10-------10----7-----|
E|------------------------|------------------------|---------5--------------|------------------------|

e|---------------8-----8--|---------------------8--|------8--------------10-|------------10----------|
B|------10-------10----8--|------------5--------10-|5-----10-------10----10-|10----10----------------|
G|9-----9-----9--9--------|5-----5-----5--------9--|------9--------9--------|10----10----------------|
D|10----10----10-10----5--|5-----5-----5--------7--|10-7--10----------------|------10----------------|
A|8-----------------------|3-----------3-----------|------------------------|10----10----------------|
E|------------------------|------------------------|------5-----------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Jazz3-150-C_comp
-------------------------------------------
e|12----12-------12----10-|---10-------10----9-----|------8--------8-----8--|------7-----7-----------|
B|12----12-------12-------|---12-------------12----|------5--------5-----5--|------8-----8-----8-----|
G|12----12-------12-------|---11-------------11----|5-----5--------5-----5--|------7-----7-----7-----|
D|10----10-------------12-|12----12----12----12----|5-----5--------5-----5--|------9-----------9-----|
A|------------------------|------10----10-------7--|7-----------------------|------7-----------7-----|
E|------------------------|------------------------|5-----------------------|------------------------|

e|8-----8--------8--8--8--|---8--------8--------8--|8-----------8--------8--|---10----10----10----10-|
B|10----10-------10----8--|---8--------8-----8-----|10----10----10----10-10-|---10----10----10-10-10-|
G|9-----9--------9-----9--|------------9-----9-----|9-----9-----9-----9--9--|---10----10----10-10-10-|
D|10----10-------10----10-|------10----------------|10----10----10----10-10-|---9-----9--9--9--9--9--|
A|8-----8--------------10-|------10----------------|8-----8-----------8-----|---------10-10----10-10-|
E|---------------------8--|------8-----------------|------------------------|------------------------|

e|------8-----8-----8-----|8-----------10----10-6--|------5--------5-----7--|---7--------7-----7-----|
B|------------------10----|10----------12----------|------5--------5-----8--|---8--8-----8-----8-----|
G|------9-----9-----9-----|9-----11----11----11----|------5--------5-----7--|---9--9-----7-----------|
D|------10----10----10----|10----11----12----------|------5-----------5-----|9-----9-----9-----9-----|
A|------10----10----8-----|7-----10----10----10----|7-----7-----------------|------------------7-----|
E|------------------8-----|8-----------------------|------------------5-----|7-----------------------|

e|------8--------8-----8--|------------8-----8--8--|------8--------8-----10-|10----10----------------|
B|------10-------10----8--|------------8-----7--10-|------10----10-10----10-|10----10----------------|
G|9-----9-----9--9--9-----|------------9--------9--|9-----9-----9--9-----10-|10----10----------------|
D|10----10----10-10-10-9--|------10----10----------|10----10-------10-------|10----10----------------|
A|8-----------------------|10----10----10----------|------------------------|10----10----------------|
E|------------------------|8-----8-----------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Jazz3-150-C_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Jazz3-150-C_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Rock2-142-D_comp
Method:    combined_all_tuned

   n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
5         547                  381                    319           0.8373        0.5832        0.5797                          0.8433

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Rock2-142-D_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------3-----------|------3-----3--------3--|------5-----5--5--------|------------6-----------|
B|3-----------3-----------|5-----5-----5--5--------|------6-----6--6--------|------6-----6--6--3-----|
G|3-----3-----3--3--------|0-----3-----3--3-----3--|2-----5-----5--5-----5--|------7-----7--7--------|
D|5-----0-----5--5--------|------5-----5--5-----5--|3-----7-----7--7-----7--|------8-----8--8--8-----|
A|5-----------5-----------|3-----3-----3--3--------|------8-----8--8-----8--|---8--8-----8--8--8-----|
E|3-----3--3-----3--------|3--------------3--------|5--------------------5--|---6--6--------6--6-----|

e|5-----------0--0--------|---5-----5--------5--5--|------5--5-----5--5-----|5--5--5-----5--5--------|
B|------3-----8--3-----8--|---2-----2--2-----8--5--|10-5--5--6-----5--6-----|5--6--5-----6--5--------|
G|7-----0-----7--0--------|0--0-----0--2--6--------|5-----5--------5--5-----|5--2--5-----2--------0--|
D|---7--8-----8--8-----5--|---7--5--7--5-----5--5--|7-----7--------7--7-----|7-----7-----0--5-----3--|
A|7--7--7-----10-7--------|7--7--------7-----------|5-----------------------|---------------5-----5--|
E|------------12----------|5--5--------5-----------|------------------------|---------5-----------3--|

e|------3-----6--6--------|------3-----3-----3--1--|------1-----1--1--1--1--|---1--1-----------0-----|
B|---------8-----------3--|---5--5-----5-----5-----|------1-----1--1-----1--|6--3--3--3--3--3--3-----|
G|------3-----3--7--7--3--|3--3--3-----3--3-----5--|------2--2--2--2-----2--|------3--------3--3-----|
D|3-----3-----5--8-----5--|5--5--5-----5--5--------|---3--3-----3--3--3--3--|3--3--3-----3--3--3-----|
A|5-----5--------5-----8--|3--3--------------------|3--3--------3--3--------|1-----1--------1--------|
E|3-----3-----------------|3--------------8--------|1-----------------------|---6-----6--------------|

e|3--3--3-----3--3-----3--|------5-----5--5-----5--|---5-----5-----5--5--5--|---5--5-----5--5--5-----|
B|---3--3-----5--3-----5--|------2-----2--------5--|6-----6--6-----6--6-----|6--6--6--6--6--6--6-----|
G|3--3--3-----3--3-----0--|---0--2-----0--0--6-----|---------------7--5-----|7--5--7--7--5--7--7-----|
D|2--5--5-----5--5--------|2--2--5-----7--7--5--5--|7--7--7--7-----7--7-----|7--7--7--7--7--7--7-----|
A|------7--------7--------|------7--------7--------|5-----5--5-----5--5--5--|------------------5-----|
E|------------------------|5--5-----------5--------|5-----5--5--------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 13 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Rock2-142-D_comp
-------------------------------------------
e|3-----3-----3-----------|------3-----3--3-----3--|------5-----5--5--------|---6--6-----6-----6-----|
B|3-----3-----3-----------|5-----5-----5--5-----3--|4-----6-----6--6-----6--|------6--6--6--6--6-----|
G|3-----3--3--3-----------|------3-----3--3-----4--|4-----5-----5--5-----5--|------7--7--7--7--7--7--|
D|5-----5--5--5-----------|------5-----5--5-----4--|7-----7-----7--7-----7--|------8--8--8--8--8-----|
A|5-----5--------------3--|3-----3-----3--3-----4--|8-----8-----8--------8--|---8--8--------8--8--7--|
E|3-----3--------3--------|3--3--3--------3--------|5--------------------5--|---6--6--------6--6-----|

e|------0--0--0--0--0--2--|---5-----5-----5--5--5--|5-----5--5-----5--5--5--|5--5--5-----5--5--------|
B|------8-----8--8-----8--|8--8-----8--8--8--8--5--|6-----5--6-----5--6-----|5--6--5-----6--5--------|
G|7--7--7--7--7--7--------|6--6--6--6--6--6--6--5--|5-----5--5-----5--5-----|5--5-----5--5--5--------|
D|------8-----8--8--------|5--5--5--5--5--5-----5--|7-----7--7-----7--7-----|7--7--7-----7--5-----3--|
A|7--7--7-----7--7-----5--|7-----------7--------5--|5-----------------------|------------5--5--5--5--|
E|---------------------5--|5-----------5-----------|------------------------|---------------------3--|

e|------3--3--6--6-----3--|---3--3--3--3--3--3--1--|------1--1--1--1-----1--|1--1--1--1--1--1--0--0--|
B|------6--6--3--3--3--3--|---5--5--5--5--5--5--5--|1-----1--1--1--1--1--1--|---3--3--3--3--3--3--4--|
G|------3-----3--3--3--3--|3--3--3--3--3--3--3-----|------2--2--2--2--2--2--|------------------------|
D|3-----3-----3--3--3--3--|5--5--5--------5--5-----|3--3--3-----3--3-----3--|3--3--3--3--3--3--3--4--|
A|5-----5-----5--5-----3--|3--3-----------3--------|3-----3-----3--3-----1--|1--1--1--------1-----4--|
E|3-----3-----3--------3--|3-----3-----------------|1-----1-----------------|------------------------|

e|---0--0-----0--0--0--0--|------5--5--5--5--5--5--|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5--5--|
B|8--8--8-----8--8--8--8--|8-----8-----8--7--5--5--|6--6--6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|
G|------7-----7--7--7--7--|------6--6--6--7--6--6--|5-----7--5--7--7--5--7--|7--5--7--7--5--7--7--7--|
D|8--8--8-----8--8-----8--|---5--5--5--5--5--5--5--|7--7--7--7-----7--7-----|7--7-----7--7--7--7--7--|
A|7-----7--------7--------|7--7--7--7--7--7--7--5--|5-----5--5-----5--5-----|5--5-----5--5-----5-----|
E|------------------------|5--5-----------5--------|5-----5-----------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 86 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock2-142-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock2-142-D_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Rock2-85-F_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
101         816                  623                    552            0.886        0.6765         0.656                          0.8551

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Rock2-85-F_comp — combined_all_tuned
------------------------------------------------------------------
e|1--------1-----1--6--3--|3-----------6--3--3-----|---------4-----------4--|------------------------|
B|2-----2--2--------6--4--|4-----8--8--8--4--4--9--|------4--4--4--4--4--6--|6--6--6--6--6--6--6--6--|
G|3-----3--3-----3--6-----|6-----6--6--6--6--------|1-----5-----5--5--5--8--|---6--6-----6-----6--0--|
D|3-----3-----3--3--8--6--|8-----8--8--8--8--------|---6--6--6--6--6--6--6--|6--6--6--6--6--6--6--0--|
A|1-----1--1--------8-----|6-----6--6-----6--------|6-----6--6--6--6--6--4--|---4--4--4-----4--4-----|
E|------------6--6--6--18-|6-----------------18----|4--4--4--4--4--4--4--4--|------------------------|

e|---------------1--------|------3-----0--3--3-----|4-----------20-8-----8--|8-----8--8-----8--------|
B|------6-----------6--5--|------5-----5--5--5-----|------6--9--6--8--9--9--|9--6--6--6--6--9--9--9--|
G|0--------------0--------|3-----3-----3--3--3-----|5-----5-----13-10----10-|---------------10-10-10-|
D|0-----5--5--5--5--5--5--|5-----5--5--5--5--5-----|3-----3-----10-10----10-|---10-10-10-10-10-10-10-|
A|------4--------4--4-----|3-----------------3-----|---------8--8--8-----8--|8--8--8--8--8--8--8--8--|
E|3--3--3-----3--3--3-----|------8-----------------|------------13----------|------------------------|

e|------6--6--6--6--6-----|3--------------3--------|------------4--4--4--4--|1--1--4-----4--4--4--3--|
B|---6--6-----6--6--6-----|4-----8-----8--8--8--8--|9--------4--4--4--4--4--|------4--4--4--4--4--4--|
G|6-----------3--6--6--12-|6-----8--6--6--6--6-----|------5--5--5--5--5--5--|---------6--6--6--6-----|
D|8-----6--6--6--8-----8--|8--------8--8--8--8--8--|6--6--6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|
A|8-----8-----8--8-----6--|6-----------6--6--10----|6--6--6--6--6--6--6--6--|4--4--4--4--4--4--4--4--|
E|6-----6--6--6--6--6--23-|6--6--21----------11----|4--4--4--4--4--4--4--4--|---4--4-----4-----------|

e|1-----------3--1-----1--|1-----1-----3--3--3-----|---1--1--1--1--1--1--1--|1-----1-----1-----1-----|
B|------6-----6--6--6-----|------------5--5--5-----|6-----1--1--1--1--1--1--|1--1--1--1--1--1--1-----|
G|------0--0--------------|---0--------3--3--3-----|------1--1--1--1-----1--|1--1--1--1--1--1--1-----|
D|5--5-----5-----5--5--5--|5-----5--5--5--5--5-----|3--3--3-----3--3--3--3--|3--3--3-----3--3--3-----|
A|5-----4-----4-----4-----|---3--3-----3-----3-----|3-----3--3--3--3-----3--|3--3--3--3-----3--3-----|
E|3-----3-----3--3--3-----|------------------------|1-----1-----4--------1--|1-----1--------1--------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 153 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Rock2-85-F_comp
------------------------------------------
e|---------6-----6--6--6--|6-----6--6--6--6--6--4--|------4--4--4--4--4--4--|4--4--4--4--4--4--4-----|
B|6-----6--6--6--6--6--8--|8-----8--8--8--8--8-----|------4--4--4--4--4--6--|6--6--6--6--6--6--6--6--|
G|6-----6--6--6--6--6--6--|6-----6--6--6--6--6--5--|------5--5--5--5--5-----|5--6--6--6--6--6--6-----|
D|8-----8--8--8--8--8--8--|8-----8--8--8--8--8--3--|6-----6--6--6--6--6--4--|6--6--6--6--6--6--6-----|
A|8-----8--8--8--8--8--6--|6-----6--------6--6-----|6--6--6--------6--6--4--|4--4--4--4--4-----4-----|
E|6-----6--6--6--6--6-----|------------------6-----|4--4--4--------4--4-----|---------------------0--|

e|3-----3--3--------3--3--|------3--3--3--3--3--8--|------8--8--8--8-----8--|8--8--8--8--8--8--8--8--|
B|------6--6--6--6--6--5--|5-----5--5--5--5--5--4--|9-----8--9--9--8--9--9--|9--11-11-11-11-9--9--9--|
G|---------------------3--|3-----3--3--3--3--3--4--|10----10-10-10-10----10-|10-10-10-10-10-10-10-10-|
D|---5--5--5--5--5--5--5--|5-----5--5--5--5--5--4--|10----10-10-10-10----10-|9--10-10-10-10-10-10-8--|
A|------4--4--4--4--4-----|3--3--3-----------3--4--|8-----8-----8--8-----8--|8--8--8--8--8--8--8--8--|
E|3--3--3--3--3--3--3-----|------------------------|------------------------|------------------------|

e|------6--6--6--6--6--6--|6-----6--6--6--6--6--4--|------4--4--4--4--4--4--|4--4--4--4--4--4--4--4--|
B|6-----9--9--6--6--6--6--|8-----8--8--8--8--8--8--|4-----4--4--4--4--4--4--|6--6--4--4--4--4--4--4--|
G|6-----6-----5--6-----6--|6-----6--6--6--6--6--6--|------5--5--5--5--5--5--|---------6--6--6--6--6--|
D|8-----6--6--6--8-----6--|8-----8--8--8--8--8--6--|6--6--6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|
A|8--8--8--8--8--8-----6--|6--6--6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|4--4--4-----4--4--4--4--|
E|6--6--6-----6--6-----6--|6-----------------------|4--4--4--4--------4--4--|---4--------------------|

e|------3--3-----3--3--3--|3--3--3--3--3--3--3--1--|------1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|
B|6-----6--6--6--6--6--6--|6--6--6--6--5--5--5--5--|1-----1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|
G|------------------------|------------3--3--3--3--|------1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|
D|---5--5-----5--5--5--5--|5--5--5--5--5--5--5--5--|3-----3--1--3--3--3--3--|3--3--3--3--3--3--3--3--|
A|5-----4--4--4--4--4-----|3--3--3-----3--3--3-----|3--3--3-----3--3--3--3--|3--3--3--3-----3--3--3--|
E|3--3--3-----3--3--3-----|---------------------0--|1--1--1--1--1-----1-----|1-----1--1-----1--1--1--|

e|---------|
B|---------|
G|1--------|
D|3--------|
A|3--------|
E|1--------|

[note: 238 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock2-85-F_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock2-85-F_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Rock3-117-Bb_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
155         159                  209                    145           0.6938        0.9119        0.3043                          0.3862

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Rock3-117-Bb_solo — combined_all_tuned
--------------------------------------------------------------------
e|10-7--8-----6--8-----10-|---8-----18----8-----10-|10----11----10-8-----10-|---8-----6--------------|
B|11----10----8--10----11-|---10----11----10----11-|11----13----11-10----11-|---------8--------9-----|
G|------------------------|---------12-------------|------------------------|---------------------10-|
D|------------------------|------------------------|------------------7-----|---------5--------------|
A|------------10----------|------------------------|10-------------------10-|------------------------|
E|---------------5--------|------------------------|------------------------|------------5-----------|

e|------------18-------5--|5-----13-6-----13-------|20-------------5--------|---------13-------------|
B|10----10-11-------------|6--------8-----10-------|---8-----8--------8--6--|6-----6--------6--------|
G|10-------12-------------|---------------10-------|14-8-----8-----10-8-----|7-----7--10----5--------|
D|------------------5-----|------------------------|15-------5--------------|---------10-10-------5--|
A|---------10-------------|------------------------|------------------------|------------------------|
E|------------5-----------|---5-----5--------------|------------------------|------------------------|

e|6-----8-----6--8-----10-|---8-----6-----8--6-----|18----5-----19-------6--|---5-----3--------3-----|
B|------10----8--10-8--11-|---10-8--8-----10-8--10-|11----6--8-----10-8--8--|---6-----------6--------|
G|---------------------12-|---------------------10-|12----------12-10-0-----|---------8--------7-----|
D|------------------------|------------------------|------------14----------|---------5--------5-----|
A|------------10----0--10-|---------10-------10----|------------------0-----|------------------5-----|
E|5-----------------------|------------------------|15-5-----5--15----------|5-----5--5--------------|

e|------------------------|------------------------|------------------------|------------------------|
B|8-----8--6--6--8--6--6--|6--6--6--6--------6--6--|6-----6-----6-----6-----|6--------6-----6--6-----|
G|7--8--7--------7--5--7--|7-----7--5-----5--5--5--|5-----5-----5-----5-----|5--------5-----5--5-----|
D|5--------10-10----------|---------------8--8-----|8--7--7--5--5--7--7--8--|7-----7--7--7-----7-----|
A|------------------------|---------10-------------|------------------------|------8-----------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Rock3-117-Bb_solo
--------------------------------------------
e|10----8-----6--8-----10-|---8-----6-----8-----10-|10----11----10-8-----10-|---8-----6--------4-----|
B|11----10----8--10----11-|---10----8-----10----11-|11----13----11-10----11-|---10----8-----------6--|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|5--------6-----------5--|5--------6-----5--------|5--3-----3-----5--3--1--|1-----1--1-----1--4--8--|
B|6--------8--------------|6--------8-----6--------|6--4-----4-----6--4-----|3-----3--1--1-----------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|9-----8-----6--8-----10-|---8-----6-----8--6--5--|6-----5-----3--5-----6--|---5-----3--------3-----|
B|11----10----8--10----11-|---10----8-----10-8--6--|8-----6-----5--6-----8--|---6-----4-----6--3-----|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|3-----3--1--1--3--1--1--|1--1--1--1--------1--1--|------1-----1-----1-----|1--------1-----1--1-----|
B|3-----3--2--1--3--1--3--|3-----3--1-----1--1-----|1-----1-----1-----1-----|1--------1-----1--1-----|
G|------------------------|---------------3--3-----|3--2--2--0--0--2--3-----|2-----------2--2--2-----|
D|------------------------|------------------------|------------------------|------3-----------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock3-117-Bb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock3-117-Bb_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_Rock3-148-C_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
83         146                  164                    122           0.7439        0.8356        0.5097                          0.6475

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_Rock3-148-C_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------5-----|5-----5-----5--5-----7--|---7-----7--7--5--------|
B|8-----6-----5-----------|------------------5-----|5-----5-----5--------5--|---5-----5-----5-----7--|
G|9-----7-----5--5-----5--|------------------4-----|4--4--4-----4--------4--|4--4-----4--4--4--------|
D|9-----7-----5--5-----5--|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|---0--------------------|
E|------------------------|------------------------|---------5--------------|------------------------|

e|------------------8-----|8--------------------8--|8--8-----8-----8--8--8--|---10-10-10-10-10-8--10-|
B|8-----10----10-10----10-|---10----8-----8--10----|---10-8--10-8--10-8--10-|---8--8--8--8--8--8--8--|
G|0-----------------12----|---------------------12-|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------5--5--------|
A|------------------------|------------------------|------------------------|10----10----------------|
E|------------------------|------------------------|------------------------|------------------------|

e|12----12-12-12-10----20-|10-8-----7-----8--8--8--|---8-----8--7--8-----8--|6--8-----8--------------|
B|8-----8--8--8--8--------|8--8-----------8--10----|---------------8--------|---8-----8-----8--------|
G|---------------------17-|------------------------|------------------------|---------------10-10-9--|
D|---------------------17-|------------------------|------------------------|---------5--------------|
A|10----------10-10-------|---------10-------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------5-----|------------------------|------------------------|
B|8-----8-----------------|------------------------|------3-----1-----1--3--|1-----1--3--1-----1-----|
G|---10-10----10-9--7-----|9-----7--5-----5--------|5--------------2--------|---2-----------2--------|
D|------------------------|------------------0--7--|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|---5--------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_Rock3-148-C_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|8-----6-----5--------5--|------------------10----|10----10----10-------12-|---12----12----10-------|
G|9-----7-----5--5-----5--|------------------9--9--|9-----9-----9--------9--|---9-----9-----9--------|
D|9-----7-----5--5-----5--|------------------9-----|9-----9-----9--------9--|---9-----9-----9--------|
A|------------------------|------------------------|------------------------|---0--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------8--8--|8--------------------8--|8--8--8--8--8--8--8--8--|8--10-10-10-10-10-8--10-|
B|8-----10----10-10-8--10-|8--10----8-----8--10----|10----10----10----9--8--|8-----8-----8-----8-----|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|12----12-12-12-10----8--|10-8-----------8--8--8--|---8-----8-----8-----8--|---8-----8--------------|
B|8-----8-----8-----------|---8-----12----8--11----|11----11----12-8--11----|11-8-----8-----8--------|
G|------------------------|------------------------|------------------------|---------0-----10-10-9--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|8-----8-----------------|------------------------|------------------------|------------------------|
G|9--10-------10-9--7-----|9--9--7-----------------|------7--------------7--|---------7-----------7--|
D|------------------------|---------10----10----7--|10----------10-7--10----|10-7--10----10-7--10----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock3-148-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_Rock3-148-C_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_SS2-107-Ab_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
23         116                  177                    107           0.6045        0.9224        0.5734                           0.785

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_SS2-107-Ab_solo — combined_all_tuned
------------------------------------------------------------------
e|------------------------|---------------------2--|4-----------------------|------------------------|
B|4--------------------4--|---------------4--------|------------4-----4-----|------------------------|
G|---------------4--------|4--8--------------------|1-----------------------|4--3--4-----------------|
D|------6-----------------|---------------1--2--4--|---2--------------------|------------------------|
A|6--------------2--4--6--|6--6--4-----------------|------4-----6--4--6--4--|2--1--2-----------------|
E|---4--4-----------------|------------------------|---------5--5-----------|---------4-----------4--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---------------------4--|
G|------3--------------1--|2--------3-----3--3--4--|------------------------|---------------4--6-----|
D|3--------------2--------|------------------------|------------------------|---6--6--6--6-----------|
A|------------------------|0-----1-----------------|------------------------|------------------------|
E|1--4--6--4--2--0--2--4--|---------6-----6--6--7--|6--------4--4-----------|------------------------|

e|4--------4--4--------4--|4--------4--4--4--2--4--|4--4--4--0--------4-----|9--------------------7--|
B|4--------5--5--------4--|7--------5--4--5-----5--|4--5--4--2--4--4--5--4--|---------0--------------|
G|------------------------|------------------------|------------4--6--4--6--|6-----------4--------4--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|---------5--------------|
E|------------------------|---5--------4-----------|4-----4--5--4-----------|5--------5--------------|

e|---19-19-18----7--9-----|7--6-----6--14-6--------|---------18----18-------|---------16----4--------|
B|---0--0-----------------|------9-----7--7--5--5--|4--------11----11----9--|---9--------4--4--4-----|
G|---16-16-15-------------|------4-----------------|4-----------------8--8--|8-----8--13-------------|
D|------------------------|------------------------|5--------------14-------|---------13-------------|
A|------------------------|------------------0-----|------------------------|------------------------|
E|------------------5-----|------------------------|4--5-----------------4--|---------4-----4--4-----|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 3 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_SS2-107-Ab_solo
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|1-----------------------|------------------------|
D|1--------------------1--|1--1-----------1--1--4--|---2--------1-----1-----|------------------------|
A|---------------2--4-----|------4-----------------|------4--------4-----4--|2--1--2-----------------|
E|---4--4-----------------|------------------------|------------------------|---------4-----4--4--4--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---------------------4--|
G|------------------------|------------------------|------------------------|---------------4--6-----|
D|------------------------|------------------------|------------------------|---6--6--6--6-----------|
A|------1-----------------|------------------------|------------------------|------------------------|
E|1--4-----4--2--0--2--4--|5-----6--6-----6--4--7--|6--------4--4-----------|------------------------|

e|4--------4--4--------4--|4--------4--4--4--7--4--|4--4--------------4-----|---------------------7--|
B|4--------5--5--------4--|7--------5--4--5--7--5--|4--5--4-----4-----4--4--|4-----------------------|
G|------------------------|------------------------|---------6--4--6--4--6--|6--------4--4-----------|
D|------------------------|------------------------|------------------------|---------0--------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---7--7--6-----7--9-----|7--------6-----6--------|---------6-----6-----4--|---4-----4-----4-----6--|
B|------------------------|------9-----7-----5-----|4-----------------4-----|------4-----4-----4-----|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 3 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_SS2-107-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_SS2-107-Ab_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 00_SS3-84-Bb_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
131         123                  163                    113           0.6933        0.9187        0.6643                          0.8407

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 00_SS3-84-Bb_solo — combined_all_tuned
-----------------------------------------------------------------
e|6-----8--6-----6-----5--|---5--5--5-----5--6--8--|10----8-----18-8--6--5--|6--5--0--3-----3--3-----|
B|8-----8--8-----6--------|---6--6--6-----6--6--6--|6-----6-----6--6--6--6--|6--6--8--6--5-----------|
G|7-----7--7-----7--------|---7--7-----------------|7--------7--------------|------------------0-----|
D|5-----5--5-----------0--|------------------5-----|5-----------------------|------5-----5-----------|
A|------------------------|------------5-----------|---------5-----8--------|------------------------|
E|---------------------5--|------------------------|10----5-----------------|------------5-----5-----|

e|---18-------------------|---5--------------------|------------------------|------------------------|
B|8--11-10-------------8--|8-----6-----------------|------------------------|------------------------|
G|---12----10-------7-----|---0-----7--------5--3--|5-----3--2--3--5--7--5--|---------5--5--3--5--7--|
D|------------------------|5-----------------------|------------------------|------------------------|
A|------------------------|---------5-----5--------|------------------------|------------------------|
E|---15-------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------6--4--------------|------------------------|------------------------|
G|---7--------------------|------------------------|------------------------|------------------------|
D|8-----------7-----5-----|3--5--3-----------3--5--|------------------------|7-----------------------|
A|------------------------|---------6--5--6--------|6--------5--5-----------|------3-----------------|
E|------------------------|------------------------|------------------6-----|5--6--5--6--5--3--2--3--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|---4--------------------|------------------------|------------------------|
G|2-----------------------|------------------------|3-----3--5--7--5--7--8--|7-----5-----3--5--7-----|
D|5--------5--------------|------------------3--5--|---5--------------------|------------------------|
A|------------3-----------|---6--5--3--3--5--------|------------------------|------------------------|
E|5-----3-----------5-----|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 7 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 00_SS3-84-Bb_solo
-----------------------------------------
e|6-----8--6-----6-----5--|---5--5--5-----5--6--8--|10----8-----6--8--6--5--|6--5--3--3-----3--3--3--|
B|8-----8--8-----6-----5--|---6--6-----------6--6--|6-----6-----6--6--6--6--|6--6--6--6--5-----------|
G|7-----7--7-----7--------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|3--6--5--------------3--|3--5--------------------|------------------------|------------------------|
B|---------6--------3--6--|------6--3--------------|------------------3-----|---------------------3--|
G|------------------------|------------------5--3--|5-----3-----3--5-----5--|---------5--5--3--5-----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|3-----------2-----------|------------------------|------------------------|------------------------|
D|------------------5-----|3--5--3-----------3--5--|------------------------|------------------------|
A|------------------------|---------6--5--6--------|6--------5--5-----------|------3-----------------|
E|------------------------|------------------------|------------------6-----|5--------6--5--3-----3--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------3-----3--4--|3-----------------3--3--|
G|------------------------|------------------------|3-----3--5-----5--------|------5-----3--5--7-----|
D|------------------------|------------------3--5--|---5--------------------|------------------------|
A|------------------------|---6--5--3-----5--------|------------------------|------------------------|
E|5-----3-----8-----5-----|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 5 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_SS3-84-Bb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/00_SS3-84-Bb_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_BN1-129-Eb_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
152         105                  137                     88           0.6423        0.8381        0.6446                          0.8864

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_BN1-129-Eb_comp — combined_all_tuned
------------------------------------------------------------------
e|------------------3-----|------------------------|------------------------|------------------------|
B|---------8--------------|---------4--------------|------------------------|---------4--------------|
G|---------8--------8-----|------------8-----------|---8-----8-----------8--|------------------------|
D|8--------8-----5--------|---------8--------------|8--------8-----8-----8--|8--------8--------------|
A|6--------6--6--6--------|6--------6--6--6--------|6--------6-----6-----6--|6--------6-----6--------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------3-----|------------------------|
B|---------------4--------|------------------------|---------4--------4--4--|---------4--4-----8-----|
G|---------5--------5-----|---------5--------5-----|------------------3-----|------------------8-----|
D|---------6--6--6-----6--|6--------6--------6-----|8--------8--------5--8--|---------8--8--8--------|
A|6--------------------6--|6--------6-----6--6-----|6--------6--6--6--6--6--|6-----------6--6--6-----|
E|4-----------4-----------|4--------4--------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------3--------------|---------------4--------|------8--------------4--|------------------8-----|
G|------------------7-----|---------5--------5-----|8--------8-----8--------|---8-----8-----8--8-----|
D|---------8--------8-----|---------6--6--------5--|8--------8-----------8--|8--------8-----8--5-----|
A|8--------------8--8-----|8--------6-----6--6--6--|6--------6--6--6--6--6--|6--------6--6--6--6-----|
E|6-----------6-----6-----|6--6-----4--4-----------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_BN1-129-Eb_comp
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|---------8--------8-----|------------------------|------------------------|------------------------|
G|---------8--------8-----|---------8--------------|---------8-----------8--|---------8--------------|
D|8--------8--------------|---------8--------8-----|---------8-----------8--|---------8--------------|
A|6-----------6--6--------|6-----------6--6--------|6-----------6--6-----6--|6--------------6--------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------4-----|------------------------|------------------8-----|------------------8-----|
G|---------5--------5--5--|---------5--------5-----|---------8--------8--8--|---------8--------8-----|
D|---------6-----6-----6--|---------6--------6--6--|---------8--------8--8--|---------8--8-----------|
A|6-----------------------|6--------------6--------|6-----------6--6--------|6-----------6--6--6-----|
E|4-----------4-----------|4-----------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------6-----|------------------4-----|------8-----------8-----|------------------8-----|
G|---------7--------7--7--|---------5--------5-----|---------8--------8-----|---------8--------8--8--|
D|---------8-----------8--|---8-----6--------------|---------8-----------8--|---------8-----------8--|
A|8--------------8--------|---------6-----6-----6--|6-----------6--6-----6--|6-----------6--6-----6--|
E|6-----------6-----------|6--------4--4-----------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN1-129-Eb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN1-129-Eb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_BN2-131-B_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
26         205                  196                    158           0.8061        0.7707        0.5885                          0.7468

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_BN2-131-B_comp — combined_all_tuned
-----------------------------------------------------------------
e|---------7--------------|---------5--------------|---------10-------------|------------------------|
B|---------8--------------|---------5--------------|---------7--------------|------------------------|
G|---------9-----4--4-----|0--------6--------6-----|7--------7-----7--------|4--------4-----0--4-----|
D|9--------9-----5--5-----|---------7--------5-----|7--------7-----7--------|5--------5--------5-----|
A|7--------7--------7-----|7--------10-------------|------------------------|5--------5-----5--5-----|
E|------------------------|5--------5--------------|------------------------|3-----------------------|

e|------------------------|------------------------|------------9-----------|------------------------|
B|---------6--------6-----|------------------------|---------7--------0-----|---------3--------3-----|
G|6--------6-----6--6-----|---------6--6--6--6-----|---------7--------7--7--|4--------4-----4--4-----|
D|6--------5-----6--------|4--------8-----8--8-----|---------9-----9--------|4--------4-----4--4-----|
A|4--------4--------4-----|4--------4-----4--4-----|---------9-----9--------|2--------2--------2-----|
E|------------------------|2-----------------------|7--------7-----7--------|------------------------|

e|---------3-----0--------|---------5--------5-----|------------------------|------------------------|
B|---------5--------------|------------------------|---------7--------------|---------0--------0-----|
G|4--------4--4--4--4-----|---------6--------6-----|---------7-----7--------|------------------------|
D|2-----2--5-----2--5-----|2--------5--7--5--5-----|7--------7--------7-----|------5--5-----5--5--5--|
A|---------7--------------|---------7--------------|5--------5--------------|5-----5--5-----5--------|
E|------5-----------------|5-----------5-----------|------------------------|3--------3-----3--------|

e|------------------------|------------------------|---------2--------------|---------2--10----------|
B|---------------6-----6--|------------------------|---------3--------------|---------0--0-----7-----|
G|---------6-----6--6-----|---------3--------3-----|4--------4--------4-----|4--------7--------7-----|
D|------------5--5--6--6--|---------4-----4--4-----|4--------4-----4--4-----|4--------4--------9-----|
A|4--------4-----4--4-----|---------4--------4-----|2--------2--2-----2-----|2-----------------9-----|
E|------------------------|---------2--------6-----|------------------------|------------7-----7-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 3 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_BN2-131-B_comp
-----------------------------------------
e|---------7--------------|---------5--------------|------------------------|------------------------|
B|---------8--------8-----|---------5--------5-----|---------7--------------|------------------------|
G|---------9-----9--9-----|---------6-----6--6-----|7--------7-----7--------|4--------4--------4-----|
D|9--------9-----9--9-----|5--------5-----5--5-----|7--------7-----7--------|5--------5-----5--5-----|
A|7-----------------7-----|7--------7--------6-----|------------------------|5--------5--5--5--5-----|
E|------------------------|5--------5--5-----------|------------------------|3-----------------------|

e|------------------------|------------------------|---------2--------------|------------------------|
B|---------6--------6-----|---------2--------2-----|---------3--------3--3--|---------3--------3-----|
G|---------6-----6--6-----|---------3-----3--3-----|---------4--------4-----|---------4-----4--4-----|
D|6--------5-----5--6-----|------------------------|---------4-----4--4-----|4--------4-----4--4-----|
A|4--------4--------------|4--------4--4--4--4-----|2-----------------------|2-----------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------5--------5-----|------------------------|------------------------|
B|---------8--------8-----|------------------------|---------7--------7-----|---------3--------------|
G|---------9-----9--9-----|---------6--------6-----|---------7-----7--7-----|------4--4--------4-----|
D|9--------9-----9--9-----|---------5-----5--5-----|7-----7--7--7-----7-----|------5--5-----5--5-----|
A|7-----7--7--7--7--------|7--------7--7--7--6-----|5--------5--5-----------|5-----5--5--5--5--4-----|
E|------------------------|5-----------5-----------|------------------------|3-----3-----3--3--------|

e|------------------------|------------------------|---------2--------------|---------2--------2--2--|
B|---------5-----6-----6--|------------------------|---------3--------3-----|---------3--------3--3--|
G|---------6-----6--6--6--|---------3--------3-----|---------4--------4-----|---------4-----4--4--4--|
D|------------------------|---------4-----4--4-----|4--------4--4--4--4-----|4--------4--4--4--4--4--|
A|4--------4--4--4--4-----|---------4-----4--4-----|2--------2--2-----2-----|2--------2--------2--2--|
E|------------------------|---------2--2-----------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN2-131-B_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN2-131-B_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_BN3-154-E_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
56         106                  116                     98           0.8448        0.9245        0.6396                          0.7245

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_BN3-154-E_solo — combined_all_tuned
-----------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------4--5-----7--|------------------------|7-----------------------|------------------------|
G|4-----4--4--------------|------------------------|---9--8--9-----8--6--8--|6--4--4-----4-----4--4--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|12----------------12----|
B|---------5--7-----7-----|---10-9--7--9--7--9--10-|12-10-9--10-12-10----10-|12-12-10-9--10-12-12-12-|
G|---4--6--------------9--|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------0-----------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------12----------12----|------12----------12----|11----9-----7-----------|------------------------|
B|12-12-12-12-12-12-12-12-|12-12-12-12-12-12-12-12-|---12----10----9--10----|------7--9--10----9--9--|
G|------------------------|------------------------|---------------------11-|---9-----------11-11----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------12----------|------------------------|------------------------|------------------------|
E|------------------12----|------------------------|------------------------|------------------------|

e|------------------------|------------------------|---------------------0--|------------------------|
B|7-----7--7--7--7--------|------------------7-----|9--------9--9--9--7--7--|7--5--5--------5--------|
G|------------------------|8-----9-----9-----------|------------------------|------------------------|
D|------------------------|9--9-----9-----9-----9--|9--9--9-----------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_BN3-154-E_solo
-----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------8--9-----11-|------------------------|11-9--8--9-----8-----8--|------------------------|
D|9--------9--------------|------------------------|------------------11----|11-9--9-----9-----9--9--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|12----------------12----|
B|------------------------|---10-9-----9-----9--10-|12-10-9--10-12-10-9--10-|12-12-10-9--10-12----12-|
G|---------9--11----11-9--|---------11----11-------|------------------------|------------------------|
D|---9--11----------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------12----------12----|------12----------12----|11----------------------|------------------------|
B|12-12----12-12-12----12-|12-12----12-12-12----12-|---12----10-12-9--10----|---------9--10-9--9--9--|
G|------------------------|------------------------|---------------------11-|---9--11-------11-11----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------7-----|9--------9--9--9--7-----|7-----------------------|
G|11-9--11----------7-----|8-----9-----9-----------|---------------------9--|---9--9-----------------|
D|---------------------9--|---9-----9-----9-----9--|---9--9-----------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN3-154-E_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_BN3-154-E_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_Jazz1-130-D_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
95         103                  130                     98           0.7538        0.9515         0.824                          0.9796

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_Jazz1-130-D_comp — combined_all_tuned
-------------------------------------------------------------------
e|------10----------5-----|------10----------------|------------------------|------------------------|
B|------7--------------7--|------7--------7-----7--|------7--------7-----7--|------7--------7-----7--|
G|------7--------7-----7--|------7--------7-----7--|------7-----7--7-----7--|7-----7--------7-----7--|
D|7-----------7--7--7-----|7-----7-----7--7--------|------------7-----7-----|7-----7-----7-----------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------3-----------------|------------------------|---10----10-------------|
B|------3--------3-----3--|3-----3--------3-----0--|---7-----7-----7-----7--|------7--------7--------|
G|------4--------4-----4--|------4--------4-----7--|---7-----7-----7-----7--|------7--------7--------|
D|5-----------4-----------|5-----5-----5--5--5-----|---7--7--7--7-----7--7--|------7-----7--7--7--7--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------5--------5-----5--|------3--------3-----3--|------7--------7-----7--|------7--------7--------|
G|------6--------6--6--6--|------4--------4-----4--|------7--------7-----7--|------7--------7--------|
D|------7-----7--7--7--7--|------------4--5--5--5--|------7-----7--7--7--7--|7-----7-----7--7--7-----|
A|------0-----------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_Jazz1-130-D_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------7--------7-----7--|------7--------7-----7--|------7--------7-----7--|------7--------7-----7--|
G|------7--------7-----7--|------7--------7-----7--|------7--------7-----7--|------7--------7-----7--|
D|7-----------7-----7-----|7-----------7-----------|------------7-----------|7-----------7-----------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------3--------3-----3--|------3--------3-----3--|---7-----7-----7-----7--|------7--------7-----7--|
G|------4--------4-----4--|------4--------4-----4--|---7-----7-----7-----7--|------7--------7-----7--|
D|5-----------4-----------|5-----------5-----5-----|7-----7-----7-----7-----|------------7-----7-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------5--------5-----5--|------3--------3-----3--|------7--------7-----7--|------7--------7--------|
G|------6--------6-----6--|------4--------4-----4--|------7--------7-----7--|------7--------7-----7--|
D|------7-----7-----7-----|------------4-----5-----|------7-----7-----7-----|7-----------7-----7-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Jazz1-130-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Jazz1-130-D_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_Rock2-142-D_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
104         114                  110                     97           0.8818        0.8509        0.6964                          0.8041

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_Rock2-142-D_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|---------------14-------|------------------------|20----------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------3--5--5--3--|5-----------------------|------------3-----------|---5--5--5--6--5--7--5--|
D|---------5--------------|---8--10-10-10----8--5--|3-----3--5-----5--8-----|------------------------|
A|------------------------|---------------10-------|------------------------|15----------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------20----------------|------------------------|------------------------|---------20-------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------9--9--9--9--|9-----------------------|------7--7-----7--------|3--5--7-----------------|
D|---8-----10-------------|---------7-----7--7--7--|---------------------5--|------------10----10-8--|
A|------15----------------|------------------------|------------------------|---------15-------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------6-----------------|------------------------|------------------------|
B|---------------6--------|------------------------|---6--6--6--6--8--8--8--|9--8--6--5-----5--------|
G|5--5--5--5--7-----4--3--|5--7-----7-----7--7--7--|7-----------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------6--8--6-----------|------------------------|------------------------|------------------------|
G|---7-----------7--5--3--|---3--5-----5--3--------|------------------------|5--6--7--7-----7--7-----|
D|------------------------|---------5--------5--3--|5--7--7--7-----7--7--7--|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_Rock2-142-D_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------3-----|
G|---------1--3--5--5--3--|6--3--5-----5--3--3-----|------------3-----3-----|5--5--5--5--6--5-----5--|
D|---------5--------------|---------------5-----5--|3-----3--5-----5--------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------3-----------------|
G|---3--5--5--9--9--9--9--|9-----------------------|------7--7--7-----5--3--|3--5-----5--5-----5--3--|
D|------------------------|---------7-----7--7--7--|7--4--------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------6-----------------|------------------------|------------------------|
B|---------------6--------|------------------------|---6--6--6--6--8--8--8--|9--8--6-----------------|
G|5--5--5--5--7-----5--3--|7--------7-----7--7--7--|7-----------------------|---------9-----9--6--1--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------6--8--6--3--------|------------------------|------------------------|------------------------|
G|5--7--------------5--3--|5--3--5-----5--3--------|------------------------|5--6--7--7-----7--7--7--|
D|------------------------|---------5--------5--3--|5--7--7--7-----7--7--7--|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Rock2-142-D_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Rock2-142-D_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_Rock2-85-F_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
116         248                  280                    208           0.7429        0.8387        0.6705                           0.851

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_Rock2-85-F_comp — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|---------4--------4-----|1-----------------------|
B|6--------6--------------|---4-----4--------8-----|---------4--------4-----|---------6--------6-----|
G|6--------6--------6-----|3-----3--6--------6-----|5--------5-----1--5-----|6--------6-----6--6-----|
D|8-----8--8--------8-----|---------8-----8--8-----|6-----6--6--------6-----|6-----6--6-----6--------|
A|8--------8-----8--8-----|6-----6--6-----6--6-----|6-----6--6-----6--6-----|4-----4--4-----4--4--7--|
E|6-----6--6-----6--6--5--|------------------------|4-----4--4-----4--4-----|---------------------0--|

e|------------------------|------------------3-----|---------1--------------|------------------------|
B|------------------------|---------1--------1-----|1--1-----1--------6-----|---1--------------------|
G|------------------------|5-----0-----------0-----|1--------1--------5-----|1--------1--5--5--1-----|
D|5--------5-----5--5-----|5--------5--------------|3--------3-----3--6--3--|3--------3--------------|
A|5-----5--5-----5--5-----|3-----3--3-----3--3-----|3--------3--------3-----|3-----3--3-----8--------|
E|3-----3--3-----3--3--5--|------------------------|1--------1-----1--1-----|1-----1--1--------20----|

e|------------------------|------------------------|---------4--------------|------------------------|
B|---6-----6--------------|---------4--------4-----|1--------4-----4--4-----|---------6--------------|
G|6--------6--------6-----|3-----3--3--------3-----|---------5--------5-----|6-----6-----6--6--------|
D|8--------8--------8-----|------------------------|6--------6-----6--6-----|6-----6--6--6--6--------|
A|8--------8-----8--8-----|6-----6--6--------6-----|6-----6--6-----6--6-----|4-----4-----4--4-----7--|
E|6-----6--6-----6--6--5--|------------------------|4-----4--4-----4--4-----|---------------------0--|

e|------------------19----|------------------------|---------1--------------|------------------------|
B|------------------------|------------------------|6-----------------------|---------6--------------|
G|3--------0--------0-----|5--------5--------5-----|5--------5--------1-----|1--5-----5--------5-----|
D|5--------0--------0--7--|5--------5--------5-----|3-----3--3-----3--------|3-----3--6-----3--6-----|
A|5--5-----------------0--|3--------3--------3-----|3-----3--3-----3--3-----|------3--8--------8-----|
E|3-----3--3-----3--3-----|------------------------|1-----1--1-----1--4-----|4-----1--------8--8-----|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 16 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_Rock2-85-F_comp
------------------------------------------
e|------------------------|------------------------|---------4--------4-----|------------------------|
B|6--------6--------6-----|------------------8-----|4--------4--------4-----|6--------6--------6-----|
G|6--------6--------6-----|---------6--------6-----|5--------5--------5-----|6--------6--------6-----|
D|8--------8--------8-----|8-----8--8-----8--8-----|6--------6--------6--6--|6-----6--6-----6--6-----|
A|8-----8--8-----8--8-----|6-----6--6-----6--6-----|6-----6--6-----6--6-----|4-----4--4-----4--4-----|
E|6-----6--6-----6--6-----|------------------------|4-----4--4-----4--------|---------------------0--|

e|------------------------|------------------------|---------1--------1-----|------------------------|
B|------------------------|------------------------|1--------1--------1-----|---------1--------1-----|
G|------------------------|5--------5--------5-----|1--------1--------1-----|1--------1--------1-----|
D|5--------5--------5-----|5--------5--------5-----|3--------3-----3--------|3--------3--------3-----|
A|5-----5--5--------5--0--|3-----3--3-----3--3-----|3--------3-----3--3--3--|3-----3--3--------3-----|
E|3-----3--3-----3--------|---------------------0--|1-----1--1-----1--1--1--|1-----1--1-----1--1-----|

e|------------------------|------------------------|---------4--------------|------------------------|
B|6--------6--------6-----|------------------------|---------4--------4-----|---------6-----6--------|
G|6--------6--------6-----|8--------8--------8-----|5--------5--------5-----|6--------------6--------|
D|8--------8--------8-----|8--------8--------8-----|6-----6-----------6-----|6-----6-----6--6--------|
A|8--------8-----8--8-----|6-----6--6--------6--5--|6-----6--------6--------|4-----4-----4-----4-----|
E|6-----6--6-----6--6-----|------------------------|4-----4--------4--------|---------------------0--|

e|------------------------|------------------------|---------1--------------|---------1--------------|
B|------------------------|------------------------|1--------1--------1-----|1--------1--------1-----|
G|3-----------------------|5--------5--------5-----|1--------1--------1-----|1--------1--------1-----|
D|5--------5--------5-----|---------5--------------|3-----3--3--------3-----|3-----------------3-----|
A|5-----5--5-----5-----0--|3--------3-----3--3-----|3-----3--3-----3--3-----|3-----3-----------3--3--|
E|3-----3--3-----3--------|------------------------|1-----1--------1-----1--|1-----1--------1-----1--|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Rock2-85-F_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_Rock2-85-F_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_SS1-100-C#_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
17         374                  317                    274           0.8644        0.7326        0.7496                          0.9453

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_SS1-100-C#_comp — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
G|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
D|6-----6--6--6--6--6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6-----|6-----6-----6-----6-----|
A|4-----4--4--4--4--4-----|4-----4--4--4-----4--4--|4-----4-----4-----------|4-----4--4--4-----4-----|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|2-----------2-----------|1-----------------------|------------9-----------|
B|---------------------2--|2-----2-----2-----2-----|------6-----6-----6-----|6-----6--6--6-----6--6--|
G|3-----6--6--6-----6--3--|3-----3--3--3-----3--3--|6--6--6--6--6-----6--6--|6-----6--6--6-----6-----|
D|4-----4--8--8-----4-----|4-----4-----4-----4-----|------6-----6-----6--6--|6-----6--6--6-----6--5--|
A|4-----------9-----4-----|4-----4-----4-----4--4--|4--4--4-----4-----------|4-----4-----4-----4-----|
E|2-----9-----9-----------|------2-----------------|------------------------|------------------------|

e|------------8-----------|------------------------|------------------------|------------------------|
B|4-----1--4--4--4--1--4--|2-----2--2--2--2--------|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
G|5-----5--5--5--5-----5--|3-----3--3--3--3--6-----|6-----6--6--6-----6--6--|6-----6--6--6--6--6--6--|
D|6-----6--6--6-----6--6--|4-----4-----4-----4--4--|6-----6--6--6--6--6--6--|6-----6--6--6-----6--6--|
A|6-----6--6--6--6--6-----|4-----4--4--4-----4-----|4-----4--4--4-----4--4--|4-----4--4--4-----4--4--|
E|4-----4--4--4--4--4--4--|------------6-----------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 41 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_SS1-100-C#_comp
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
G|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
D|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
A|4-----4--4--4-----4--4--|4-----4--4--4-----4--4--|4-----4-----4-----------|4-----4--4--4-----4--4--|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|2-----2--2--2-----2--2--|2-----2--2--2-----2--2--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
G|3-----3--3--3-----3--3--|3-----3--3--3-----3--3--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
D|4-----4--4--4-----4--4--|4-----4--4--4-----4--4--|------6--6--6-----6--6--|6-----6--6--6-----------|
A|4-----4-----4-----4--4--|4-----4--4--4-----4--4--|4-----4--4--4-----4--4--|------4--4--4-----4--4--|
E|2-----------------2-----|------2-----------2-----|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|4-----4--4--4-----4--4--|2-----2--2--2-----2-----|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
G|5-----5--5--5-----5--5--|3-----3--3--3-----3--3--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
D|6-----6--6--6-----6--6--|4-----4--4--4-----4--4--|6-----6--6--6-----6--6--|6-----6--6--6-----6--6--|
A|6-----6--6--6-----6--6--|4-----4-----4-----4-----|4-----4--4--4-----4--4--|------4--4--4-----4--4--|
E|4-----4-----------4-----|14----2-----------2-----|------------------------|------------------------|

e|---------|
B|---------|
G|6--------|
D|6--------|
A|4--------|
E|---------|

[note: 85 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS1-100-C__comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS1-100-C__comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_SS1-68-E_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
44         125                  135                    100           0.7407           0.8        0.3231                            0.42

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_SS1-68-E_solo — combined_all_tuned
----------------------------------------------------------------
e|------------------------|------------------------|------4-----------5--7--|------------------------|
B|------5--5--5-----------|---------3--5-----5-----|5--6--------------------|10-8--10-8--10-8-----5--|
G|------7--------4--------|------4-----------4-----|4-----------------------|---------------9--7-----|
D|------------------------|------------------------|------------------------|------------------------|
A|------5-----------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------5-----|------------------------|

e|---------10-------------|------------------------|---4--------------------|---3--------------------|
B|5--3--------------------|------------10-------3--|---------------------3--|5--5--6-----------------|
G|---4--7--7--------------|---7--------------4--4--|------------------4--4--|---------------7--9--9--|
D|---------7--7--5--------|---9--7--7--7--5--7-----|6--------------5--------|---------------5--------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|7--------7--------------|------------10----------|------------------------|
B|7--8--8-----8-----------|---5--------------------|8--------------------8--|0-----0--------0--------|
G|------9--9--9--9--9-----|------------9--9--7--9--|---7--9--9--7-----------|7-----2--0--------0-----|
D|------------------------|---------0-----------5--|---9-----9-----7--9--9--|---5-----2--2-----0--2--|
A|------------------------|------------------------|------------------------|---------------2--0--0--|
E|------------------------|---------5--------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 28 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_SS1-68-E_solo
----------------------------------------
e|------------------------|------------------------|------3-----------7--7--|3--3--5--3--5--3--------|
B|------5-----5--0--------|---------3--5-----0--4--|5--5--------------------|---------------4--3--5--|
G|------------------------|------4-----------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------0-----|------------------------|
E|------3-----------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|---3--------------------|
B|5--3--3-----------------|---------------------3--|---------------------3--|5--5--3--------3--5--5--|
G|---4-----2--2--0--------|---4--2--2--2--0--4--4--|1--------------0--4--4--|------------------------|
D|------------------------|------------------------|---------------2--------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|7--------7--------------|3--------------------3--|3-----------------------|
B|7--8--8--5--5--5--5--3--|---5-----5--5--5--3--5--|---3--5-----3-----------|3-----------------------|
G|------------------------|------------------------|---4-----4-----2--4-----|4--0--4--0--------------|
D|------------------------|---------0--------------|------------------------|---------2--2--1--0--2--|
A|------------------------|1--------1--------------|------------------------|---------------2--0--2--|
E|------------------------|------------------------|------------------------|---------------1--0-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 29 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS1-68-E_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS1-68-E_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_SS2-107-Ab_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
53         243                  191                    172           0.9005        0.7078        0.4654                          0.5872

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_SS2-107-Ab_solo — combined_all_tuned
------------------------------------------------------------------
e|9-----------------------|------------------4-----|------------------------|------------7-----7-----|
B|------5-----7--5--7--7--|---5--7--7--5--5--5-----|------5--------8--7--7--|9-----9-----------------|
G|6--6--6--6--------------|------6-----------6--6--|4--4--6--6--9-----------|9--9-----9-----9--9--9--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|9-----------------------|---8--8--8--8--8--8-----|8-----------------------|------------------------|
D|---8-----8--8--8--8--8--|8-----------------------|------6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|
A|------------------------|0-----------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------12-12-12-|7--7--7-----------------|4--7-----------7--------|---12----0--12-16-7--7--|
B|------5--------12-12----|------9--7--7--7--7--5--|---7--7--7--9-----7--6--|12----12-12-12-9--9--9--|
G|---6-----9--9-----9--9--|------------------------|------------------------|---13-13-13-16----------|
D|6-----------------------|------------------------|---0--------------------|------------18----------|
A|------------------------|------------------------|5-----------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---9-----9--------------|
G|------------5--5--5--5--|6--6--5--5--5-----------|---------------8-----8--|---8--8--8--------8-----|
D|---8-----8--8-----------|---------------8--8--8--|8--6--6--6--6--6--6--6--|6--6--------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 39 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_SS2-107-Ab_solo
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------9-----|------------------------|9-----9-----12----12----|
G|------9-----9--11-11-11-|11-9--11-11-9--9--9-----|------9-----9--11-11-11-|9--9--9--9--10-9--9--9--|
D|11-11-11-11-------------|---------11-11-11-11-11-|9--9--11-11-11----------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|9-----------------------|---8--8-----8--8--8--8--|8-----------------------|------------------------|
D|------8--8--8-----8--8--|------------------------|------6--6--6--6--6--6--|6--6--6--6--6--6--6--6--|
A|------------------------|0-----------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------12-12-12-|------------------------|------------------------|---12----12-12-12-------|
B|---------------12-12-12-|12-12-9--9--9-----------|---12----------12-------|---12-12-12-13-12----12-|
G|------9-----9-----9--9--|9--------11-11-11-11-9--|13-11-11-11-13-11-11-10-|13-13-13-13-13-13-13-13-|
D|6--11-------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---9-----9-----9-----9--|
G|------------------------|------------------------|---------------8-----8--|---8--8--8--8--8--8--8--|
D|---8--8--8--8--10-10-10-|10-11-10-10-10-8--8--8--|8--6--6--6--6--6--6--6--|6--6--6-----------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 81 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS2-107-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS2-107-Ab_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_SS2-88-F_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
140         154                  164                    134           0.8171        0.8701        0.3333                          0.3955

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_SS2-88-F_solo — combined_all_tuned
----------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|---------2--------2--4--|4--4--4-----------------|---------------------5--|4--4--2--4-----------4--|
G|3--3-----3--------3-----|6--------6--6--8--8--9--|8--------------6-----6--|------3--6--6--6--6-----|
D|------------------------|------0--8--------------|---8--6-----6--8--8-----|------------------------|
A|------------------------|------------------------|---------------0--------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------19----------------|------------------------|
B|4-----------------------|---------------------5--|6-----------------------|10-9--7--6--6--------6--|
G|------5--------5--5--3--|3-----5--5--------5-----|------------8--10-10----|10-------------6--8-----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------4-----------------|------------------------|

e|------5--------------6--|------6-----6--6--6--6--|------------------------|------------------------|
B|4-----4--2--2--6--4--6--|6--6--6--4--6--6-----4--|4--2--2--4--4-----4--2--|------2-----------------|
G|---------3--------------|---------------8--------|---3-----------------3--|---------3--4--3--3--3--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|4--6--6--6--7-----------|
B|---------------2--4--4--|---4--4--6--6-----6--6--|9--8--8-----9--6--6--6--|6--------------6--------|
G|---------3--3-----------|5-----------------------|------10----10----------|------------------------|
D|5-----5-----------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------10----------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 32 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_SS2-88-F_solo
----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------6--------6--9--|6--8--8--6--6--8--8--9--|8--------------6-----9--|8--8--6--6--6--6--6--8--|
D|8-----8-----------8-----|------0--8--------------|---8--6-----6--8--8-----|------8-----------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|9--9--------------------|
G|8-----------------------|------5--5--------5--9--|10----------8--10-10----|10-13-11----10-6--10-8--|
D|------10----------10-8--|8-----2-----------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------------6--|------6-----6-----6-----|------------------------|------------------------|
B|---------------6-----6--|6--6--------6--6-----6--|------------------------|------------------------|
G|8-----8--6--6--8--8-----|10-8-----8-----8-----8--|8--6--6--8--8-----8--6--|------6-----------------|
D|---------8--------------|------------------------|---8-----------------8--|---------8--8-----8--8--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|9--8--------9--8--------|9--11-11-11-12----------|
G|---------------6--8--8--|5--8--8--10-10----10-10-|------10----10-10-10-10-|---------------10----8--|
D|5-----5--8--8-----------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 31 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS2-88-F_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS2-88-F_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 01_SS3-98-C_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
128         195                  212                    174           0.8208        0.8923        0.4914                          0.5747

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 01_SS3-98-C_solo — combined_all_tuned
----------------------------------------------------------------
e|------------------------|------------10----------|------------------------|------------------------|
B|------------------------|------------------------|---------1--3--5--6--5--|------------------6--6--|
G|9-----9-----7-----5--7--|7--7--------7--5--4--5--|2--2--2--2-----------9--|5--9--10-7--7--7--------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------5--5--5--5--5--|5--7--7--8--7-----------|------------------------|
B|6-----6--5-----8--------|---8--8-----------------|---------------10-10-8--|8--8--10----10-10-8--10-|
G|---------7--7--9-----5--|5-----9-----------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|---------------10-------|------------------------|------------------------|------------------------|
E|------------------------|------------5-----------|------------------------|------------------------|

e|20----8--20----8--10-20-|---12-8--10-20-12-20-10-|20----20----------10----|------8--10-7--10-10-8--|
B|13-10----13-10-10-10-13-|---10-10-10-13-10-13-10-|13-12-13-10-10-10-12-10-|8-----------------------|
G|------------------------|14----------14----14----|14-0--------------------|0-----------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|10-10-10-8--7--7--------|------------------------|------------------------|10-------10-------------|
B|------------------8--6--|8-----5--5--------------|---0--------------------|------------------------|
G|------------------------|------------7--7--5--2--|2--0--0--0--2--5-----5--|7--7--7--9--9--9--9-----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------5-----|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 64 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 01_SS3-98-C_solo
----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|---------------6--6-----|5-----6--5--5-----6--6--|
G|9-----------9--7--5--7--|7-----------7--5--5--5--|4--4-----5--7--8-----7--|7--7-----7--7--7--------|
D|------------------------|------------------------|7--7--7--7--------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|6-----6--5--5--8--------|---8--8--10-10-10-8--10-|12-12-12-13-12-10-10-8--|8-----8--8--10-10-------|
G|---------7--9-----9--5--|5--9--9-----------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|8-----8--8-----8--10----|8--8--8--8--8--12-8--10-|8--7--8--7--7-----10----|------------------------|
B|---10----10-10-10-10-10-|---10-10-10-10-10-10-10-|10-10----10-10-10-12-10-|8--------15-12-15-15-12-|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|15-15-15-13-12-12-------|------------------------|------------------------|------------------------|
G|---------------14-12-10-|12-10-9--9--7--7--5--4--|4--------------5-----5--|7--7--7--9--9--9--9--9--|
D|------------------------|---------------------7--|7--8--5--5--7-----------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 51 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS3-98-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/01_SS3-98-C_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 02_BN1-147-Gb_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
149         200                  164                    144            0.878          0.72        0.3132                          0.3958

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 02_BN1-147-Gb_comp — combined_all_tuned
------------------------------------------------------------------
e|2--------2--------2-----|---------------------2--|---------2--------2-----|---2--------------------|
B|2--------2--------2-----|---2-----2--------------|2--------2--------2-----|---2-----2--2-----------|
G|3--------3--------3-----|---3--3--3--3-----3--6--|3--------3--------3-----|3--3-----3--3-----------|
D|4--------4--------4-----|---4-----4--4-----4--4--|4--------4--------4-----|---4-----4--4--4--------|
A|------------------------|------------------------|------------------------|------------------5-----|
E|---2--------------------|------------------------|---2--------------------|------------------------|

e|------------------------|------------------------|---------2-----2--------|---2-----------2--------|
B|------------------0-----|---------4--4-----------|2--------------2--2-----|---2--------2-----------|
G|---------4--------------|---8-----4--4--4--------|3--------3-----3--3-----|3--3--3--3--3--6-----4--|
D|4-----------------4-----|---4-----4--4--4--------|4--------------4--4-----|---4-----4--4--4-----5--|
A|6--------6--------6-----|---6--6--6--6--6--5-----|------------------------|---------------------5--|
E|---7-----7--------7-----|---7-----7--7--7--------|------------------2-----|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|---0-----0--0-----------|---------------------7--|---7-----------7--------|
G|1--------1--------4-----|---8-----------8--------|6--------6--------6-----|6--6--------------------|
D|3--------3--------------|---4-----4--4--4--5--5--|8--------8--------8-----|8--8--8-----8-----8-----|
A|4--------4--------6-----|6--6-----6--6-----------|9--------9--------9-----|9--9--------9-----9-----|
E|4-----------------7-----|---7-----7--7-----------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 02_BN1-147-Gb_comp
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|7--------7--------7-----|------7-----7--------7--|7--------7--------7-----|7--7--------7-----------|
G|6--------6--------6-----|---6--6--6--6-----6--6--|6--------6--------6-----|---6-----6--6--6--------|
D|8-----8--8--------8-----|---8--8--8--8--8--8--8--|8--------8--------8-----|8--8-----8--8--8--0--0--|
A|9-----9--9--------9-----|9--9--8-----9-----9-----|9-----------------9-----|9--9-----9--9--9--------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|6--------7-----7--7-----|---7--------7--7-----0--|
G|---------4--------4-----|---4-----4--4--4--------|6--------6-----6--6-----|6--6--6--6--6--6-----0--|
D|------------------4-----|---4-----4--4--4--0--0--|8-----8--8-----8--8-----|8--8--8--8--8--8-----0--|
A|6--------6--------6-----|---6-----6--6--6--------|9-----------------9-----|---9-----9--9--9--------|
E|7--------7--------7-----|---7-----7--7--7--------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|---4--------------0-----|6-----------------7-----|---7--7-----7--7--------|
G|------------------4-----|---4-----4--4--4--0--0--|6-----6--6--------6-----|6--6--6--6--6--6--6--6--|
D|6--------6-----0--4-----|---4-----4--4--4--0-----|8--------8--------8-----|8--8--8--8--8--8--8--8--|
A|8--------8--------6-----|6-----6--6--6--6--------|9--------9--------9-----|9--9-----9--9--9--9--9--|
E|9--------9--------7-----|---7-----7--7-----------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_BN1-147-Gb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_BN1-147-Gb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 02_BN2-131-B_solo
Method:    combined_all_tuned

   n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
2          66                   83                     59           0.7108        0.8939        0.4966                          0.6271

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 02_BN2-131-B_solo — combined_all_tuned
-----------------------------------------------------------------
e|------------------------|------------------------|------------------9-----|------------------------|
B|---------3--------2-----|---------0--------------|------------------------|------------------------|
G|4-----------2-----------|------------------2-----|4--4-----7--------6-----|------------------------|
D|---4--------------------|------------------------|---4--------7-----------|9--------7--------4-----|
A|---------------------0--|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|---------5--------5-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---5--5--3--5--6--5--3--|
G|------------------4-----|------------------------|4--4-----6--6--6-----7--|7-----------------------|
D|6--------7--------------|6--------4--------------|------------------------|------------------------|
A|------------------------|------------------7-----|------------------------|------------------------|
E|---5--------5-----------|---5--------5-----------|------------------------|------5-----5-----------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|3--------2--------------|5-----7-----------------|5--7--------------------|
G|4-----------------------|------------------2-----|---------7--------------|---------7--------6-----|
D|------------------4-----|------------------------|------------0-----------|------------0-----------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|5-----------5-----------|------------5-----------|

e|---------0--------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------7-----|
G|------------------7--6--|------4--6--------------|---4--------4-----------|6-----7-----9-----------|
D|6-----7--7--------------|------------------6--7--|------------------------|------------------------|
A|---------0--------------|------------------------|------------------------|------------------------|
E|------------------------|5-----------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 02_BN2-131-B_solo
-----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|4--------7--------6-----|---------4--------------|4--------7--------6-----|4-----------------------|
D|---4--------7-----------|------------------7-----|---4--------7-----------|---------7--------4-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|4--4--4--6--6--6--7--7--|7--9-----7--9--10-9--7--|
D|6--------7--------9-----|6--------4--------2-----|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|4-----------------------|7--------6--------------|9-----11-7--------------|9--11----7--------6-----|
D|------------------4-----|------------------7-----|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------9--------7--6--|---------6--------------|---4--------------------|6-----7-----9-----11----|
D|6-----7-----------------|------9-----------6--7--|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 4 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_BN2-131-B_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_BN2-131-B_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 02_Funk1-97-C_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
98         189                  195                    145           0.7436        0.7672        0.6094                          0.8069

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 02_Funk1-97-C_comp — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|1--1--------------------|---1--------------------|------------------------|
G|------------0-----------|0--------------0--0--0--|0--------------0-----0--|---0--------0--0--------|
D|5-----5-----5--5--5-----|5--5--------5-----------|---5--------5-----5--5--|5-----------------5-----|
A|3-----3-----------1--3--|3--3--------1--1--3--3--|3--3-----3--1--3--1--3--|1--3--------1--3--1--3--|
E|------------6--8--------|------------------------|------4-----------------|------0-----------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------0-----------------|---0-----------0--------|
D|3--3--------3-----3-----|3--3--------3-----3--3--|---5--------5-----5--5--|5-----5-----5-----5-----|
A|3--3--------3-----3--3--|3--3--------3-----3-----|3--3--3--1--1--3--------|---3--3-----1--3--1--3--|
E|1--1--------1-----1-----|1--1--------1--0--1-----|------------------6--8--|6--------------------5--|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|0-----0-----------------|---0-----0--0-----0-----|
D|---5-----------0-----2--|3-----3--3--3-----------|---------5--5--5--------|5-----5-----5--5-----5--|
A|5--5--------5-----------|3--3--3--3--3-----------|3-----3-----------------|---3--1--3--------------|
E|3--3--------3--3--4-----|1--1--1--1--1-----------|---------5--8--8-----6--|6-----------6--8--6--8--|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 33 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 02_Funk1-97-C_comp
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|5-----5--5--5--5--5--5--|5--5--------5-----5-----|---5--------5--6--5--5--|5--5--------5--5--5-----|
A|3-----3-----1--3--1--3--|3--3--------1--3--1--3--|3--3-----3--1--3--1--3--|1--3--------1--3--1--3--|
E|------1-----------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------5-----------------|------------------------|
D|0-----------------3-----|3--3--------3--------3--|------5--4--5--5--5-----|5-----------------------|
A|3--3--------3--3--3--3--|3--3-----3--3-----3-----|2--3--3--0--1--2--1--3--|2--3--3--3--1--3--1--3--|
E|1--0--------1--1--1--1--|1--1-----1--------0-----|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|5-----------------------|------------------------|
D|------------5--5--------|3-----3--3--3-----------|5-----5-----5--5--------|5-----5--5--5--5--5-----|
A|5--5--------5--5--------|3--3--3--3--3-----------|3--3--3--1--1--3-----1--|1--3--1--3--1--3--1--3--|
E|3--3--------3--3--------|1--1--1--1--1-----------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 42 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Funk1-97-C_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Funk1-97-C_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 02_Funk3-112-C#_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
68         139                  135                    110           0.8148        0.7914        0.4599                          0.5727

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 02_Funk3-112-C#_solo — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|---------4--------------|------------------------|------4-----------------|
B|---------6--6--------4--|------------6-----------|---------6--6-----------|8-----------6-----4-----|
G|6--------------8--------|------------------------|6--6--8--------8--------|------------------------|
D|------------------------|4--5-----6--3-----------|------------------------|6--6--6--6--3-----------|
A|4-----6--8--8--6-----6--|------------------------|4-----6--8--8--6--------|------------------6--4--|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|---------------3--------|------------------------|
B|---------4-----6-----4--|---------------2--------|6-----4--------------6--|------------6-----------|
G|6-----------------------|---6-----6--------------|------------------------|------------------------|
D|---------------3--------|---------------------2--|3--------------5-----3--|------------3-----------|
A|4--------6-----------6--|---4-----3-----4--------|------6--4--------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---4--------------------|------------------------|------------------------|
B|------4--6--------------|---------6--------4-----|------------------------|------------------------|
G|6--------------------6--|------------------------|6-----4--------8--------|3-----------------------|
D|---------3--------------|---6-----3--------------|------------------------|---------6--------6-----|
A|4-----6--------6-----4--|---7--------------6--4--|4--6--6--8-----6--------|------3-----------------|
E|------------------------|------------------------|---------------------6--|6--------4-----4--4-----|

e|------------------------|------------------------|------------------------|------------------------|
B|---------6-----4--------|---------6--------------|---------6-----4--------|---4--------------------|
G|6--------------------6--|------------------------|6--------------------6--|---------5--5-----5-----|
D|---------3--------------|---5--6-----------------|------6-----------------|------------------------|
A|4-----6--------6-----4--|---------8-----6-----4--|4--------8-----6-----4--|---6-----3--3--3--3-----|
E|------------------------|------------------------|------------------------|---4--------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 2 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 02_Funk3-112-C#_solo
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---6--7-----10-8--------|---12----13-10----------|---6--7-----10-8--------|12-13-13-13-10----6-----|
D|------------------------|------------------------|------------------------|------------------------|
A|4-----6--8-----------6--|---10----11-8-----------|4-----6--8-----6-----4--|11-11-11-11-8-----4-----|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|6--------8-----10----8--|---6-----6-----6--------|10----8--6-----12----10-|------------10----------|
D|------------------------|------------------------|------------------------|------------------------|
A|4--------6-----8-----6--|---4-----3-----4--------|8-----6--4-----10----8--|------------8-----------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|0-----------------------|
G|6-----8--10----8-----6--|---13----10-------8--6--|6-----8--10----8--------|------------------------|
D|------------------------|------------------------|------------------------|8-----------------6-----|
A|4-----6--8-----6-----4--|---11----8--------6--4--|4-----6--8-----6--------|---------------3--3-----|
E|------------------------|------------------------|---------------------6--|6--6--8--4-----4--4-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|6-----8--10----8-----6--|---12----10----8--------|6--10-13-10----8-----6--|---8-----5--5-----5-----|
D|------------------------|------------------------|------------------------|------------------------|
A|4-----6--8-----6-----4--|---10-11-8-----6-----4--|4-----11-8-----6-----4--|---6-----3--3--3--3-----|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Funk3-112-C__solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Funk3-112-C__solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 02_Rock1-90-C#_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
65         227                  205                    158           0.7707         0.696        0.4676                          0.6392

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 02_Rock1-90-C#_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------2-----2-----|------2-----2-----2-----|------------2-----2--4--|------2-----2-----2-----|
G|---------------3--------|------------3-----3-----|---------------3--------|---------------3--3--6--|
D|6-----6--6--6-----6--3--|------6-----6-----6-----|6-----6-----6-----6--6--|6-----6-----6-----6-----|
A|4-----4--4-----4--4--4--|4--4--4--------4--4-----|4-----4--4-----4--------|4--4--4--4--4--4--4--4--|
E|------4--4--------------|------------------------|4--------------------4--|4-----4-----------------|

e|------------2--------2--|------------------------|------------------------|------------------------|
B|------0-----------------|------7-----4--------4--|2-----2-----------------|2-----2-----2-----2-----|
G|6-----6-----6--6-----6--|------6-----6-----6-----|------------6-----6--6--|---------------3--3-----|
D|4--4--4--4--4--4-----4--|------4--4--------------|6-----6-----6--8--6--8--|6-----6-----6-----6-----|
A|------2-----------4-----|---------------4--4--4--|4-----4-----4--4--4--4--|4--4--4-----4-----4-----|
E|4--------------------4--|------2-----------------|------------------------|------------------------|

e|------------------------|------------------------|------1-----------------|------------------------|
B|---------4-----4--------|------7--------------4--|2-----------2--------2--|------2-----------------|
G|------5--------------6--|------6-----3-----6-----|------6-----------------|---------6--6-----6-----|
D|------6-----------4--4--|------4-----6-----4-----|6-----6-----6-----6--6--|------6-----6-----6--8--|
A|6-----6-----6--6--4--4--|------4--------4--------|4-----4-----4-----4--4--|---4--4-----4--4--4--4--|
E|4-----4-----4--4--4--4--|------------------------|4-----4--------4--------|---------4--4-----4-----|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 13 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 02_Rock1-90-C#_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------6-----6-----|------6-----6-----6-----|------------6-----6--8--|------6-----6-----6-----|
D|6-----6--6--6--8--6-----|------6-----8-----6--8--|6-----6-----6--8--6--6--|6-----6-----6--8--8--11-|
A|4-----4--4-----4--4--4--|4--4--4--4--4--4--4--4--|4--4--4--4--4--4--4--4--|4--4--4--4--4--4--4-----|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------4--4--11-11----11-|------11----------------|------6-----6-----6-----|6-----6-----6-----6-----|
D|11----11-11-11-11----11-|---11-11-11-13----11-13-|6-----6-----6--8--6--8--|6-----6-----6--8--6--8--|
A|9--9--9--9--9--9-----9--|9--9--9--9-----4--4--4--|4--4--4--4--4--4--4--4--|4--4--4--5-----4--4--4--|
E|------------------------|------------------------|------------------------|------------------------|

e|------4-----------4--2--|------2-----------1-----|------------------------|------------------------|
B|------4--------------7--|------7-----------6-----|------6-----6--------6--|------------------------|
G|------5--------8-----6--|------6-----------6--8--|------6-----6--------6--|------6-----6--------6--|
D|------6-----------4--4--|---4--4--4--6--8--4--4--|6-----6-----6--6--6--6--|---6--6--6--6-----6--6--|
A|6--6--6--6--6--6--4--4--|------4--------4--------|4--4--4--4--4--4--4--4--|------------------------|
E|4--4--4-----4--4--4--4--|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|8--------|
D|---------|
A|---------|
E|---------|

[note: 27 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Rock1-90-C__comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/02_Rock1-90-C__comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_BN3-154-E_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
161         181                  128                    109           0.8516        0.6022        0.3689                          0.5229

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_BN3-154-E_comp — combined_all_tuned
-----------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|4-----4--------4-----4--|---4--------4-----------|------------------------|------------4-----------|
G|4-----4--------4-----2--|---2--------2-----------|------------------------|---4--------4-----------|
D|2-----2-----2-----------|------------------------|6-----6--------6--------|---4--------4-----------|
A|---------------------2--|---2-----2--2-----------|4-----4-----4-----------|------------------------|
E|---------------------4--|------------------------|---------------------4--|---------4--4-----4-----|

e|------------------------|------------------------|------------------------|------------2-----------|
B|------------------------|------------4-----------|---------------2--------|---4--------4-----------|
G|6-----6--------6--------|------------------4-----|6-----------------------|---2--------2-----------|
D|6-----6--------6--------|---9--------9-----------|6--------------6--------|------------------------|
A|0-----0--------------7--|---------7--7--7--7-----|0-----------------------|---2-----2--2-----2-----|
E|------------5-----------|------------------------|------5-----5-----------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------4--------4-----4--|---4-----0--4-----------|2-----------------------|------------------------|
G|---------------------2--|---2--------2-----------|4-----------------------|------------4-----------|
D|2-----2-----2--2--------|------------------------|6-----6--------6--------|------4-----4-----------|
A|---------0--------------|---2-----2--------------|4-----------4-----------|------------------------|
E|------------------------|------------------------|4--------------------4--|------4--4--4-----4-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|---4--------------------|------------------------|------4-----------------|
G|------6--------6--------|------------8-----------|---------------6--------|------2-----------4-----|
D|------6--------6--------|---9--------9-----------|6-----6--------6--------|------4-----------------|
A|------------------------|---------7--------7-----|0-----0-----------------|2--2--2-----------2-----|
E|5-----------5-----------|------------------------|------------5-----------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_BN3-154-E_comp
-----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|9-----9--------9-----7--|---7--------7-----------|5-----5--------5--------|---4--------4-----4-----|
G|8-----8--------8-----8--|---8--------8-----------|4-----4--------4--------|---4--------4-----4-----|
D|9-----9--------9-----7--|---7--------7-----------|6-----6--------6--------|---4--------4-----4-----|
A|7-----7-----7-----------|------------------------|4-----4-----4-----------|------------------------|
E|---------------------7--|---7-----7--------------|---------------------4--|---------4--------4-----|

e|------------------------|------------------------|------------------------|------------------------|
B|5-----5--------5--------|---9--------9-----9-----|5-----5--------5--------|---7--------7-----7-----|
G|6-----6--------6--------|---7--------8-----8-----|6-----6--------6--------|---8--------8-----8-----|
D|6-----6--------6--------|---9--------9-----8-----|6-----6--------6--------|---7--------7-----7-----|
A|---------------------7--|---------7-----7--------|------------------------|------------------------|
E|5-----5-----5-----------|------------------------|5-----5-----5-----------|7--7-----7--------7-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------9--------9--------|---7--------7-----------|5-----5--------5--------|---4--------4-----------|
G|------8--------8-----8--|---8--------8-----------|4-----4--------4--------|------4-----4-----4-----|
D|------9--------9-----7--|---7--------7-----------|6-----6--------6--------|------4-----4-----4-----|
A|7-----7-----7-----------|------------------------|4-----4-----4-----------|------------------------|
E|---------------------7--|---7-----7-----7--------|---------------------4--|------4-----4-----4-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------5--------5--------|---9--------9-----9-----|5-----5--------5--------|------7-----------------|
G|------6--------6--------|---8--------8-----8-----|6-----6--------6--------|------8-----------------|
D|------6--------6--------|---9--------9-----9-----|6-----6--------6--------|------7-----------------|
A|---------------------8--|---8-----7--------7-----|------------------------|------9-----------------|
E|5-----------5-----------|------------------------|5-----5-----5-----------|7-----------------7-----|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_BN3-154-E_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_BN3-154-E_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_Jazz1-130-D_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
86          90                   78                     67            0.859        0.7444        0.6667                          0.8358

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_Jazz1-130-D_comp — combined_all_tuned
-------------------------------------------------------------------
e|------5-----------------|---------------5-----10-|------------------------|5-----------------------|
B|------5--------5--------|5--------5-----5-----7--|------------------------|5-----------5-----7-----|
G|------5-----------------|---------0--------4-----|---5--------------------|5-----------5-----5-----|
D|------4-----------------|---------------5-----5--|------------------------|5-----------------5-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------3--------------|------5-----------------|------10----------------|
B|5-----------------------|6--------------6--------|------------------------|------7-----------------|
G|4-----------------------|5--------0-----------9--|---------------9--------|------7--------7--------|
D|---------------------5--|5--------7-----5-----4--|---------------4--------|------7-----------------|
A|8-----------5-----------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|5-----------------------|------------------------|

e|------19----5-----------|---------------------5--|---------------5--------|5--------------5--------|
B|---7--------8-----------|---6--------5--------5--|---------------5--------|5--------------5--------|
G|------6-----7-----------|---5--------4-----------|---------------5--------|5--------------5--------|
D|------------7-----------|---5-----------------4--|------4-----------------|---------------4--------|
A|------10----------------|------------8-----------|------5-----------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_Jazz1-130-D_comp
-------------------------------------------
e|------5-----------5-----|5--------7-----5-----5--|------------5-----------|5-----------------------|
B|------5-----------5-----|5--------5-----5-----7--|------------5-----------|5-----------5-----7-----|
G|------5-----------5-----|5--------5-----5-----5--|------------5-----------|5-----------5-----5-----|
D|------4--------------4--|---------5-----5-----5--|------------5-----------|5-----------------5-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------------------5--|------------------------|------2--------2--------|
B|5-----------------------|6--------8-----6-----5--|---------------5--------|------3--------3--------|
G|4-----------------------|5--------7-----5--------|------------------------|------2-----------------|
D|3--------------------5--|---------7-----5-----4--|---------------4--------|------2-----------------|
A|------------------------|------------------------|------------------------|------3--------3--------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------------------5--|---------------5--------|5--------------5--------|
B|------7-----8-----------|---6--------5--------5--|---------------5--------|5--------------5--------|
G|------6-----7-----------|---5--------4--------5--|---------------5--------|5--------------5--------|
D|------5-----7-----------|---5--------3--------4--|------4-----------------|---------------4--------|
A|------------------------|------------------------|------5-----5-----------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Jazz1-130-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Jazz1-130-D_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_Jazz3-150-C_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
32          77                   82                     72            0.878        0.9351        0.6667                          0.7361

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_Jazz3-150-C_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|---7--10----9--8--7--5--|
B|---------8--5--------3--|------------6-----------|------------5--8-----7--|8-----------------------|
G|---------------5--------|---4--------------------|---------5--------9-----|------------------------|
D|---------5--------------|------3-----3-----5-----|---6--------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|5--8--------------------|---------8--------------|------13----12----10----|------11----------------|
B|------10----8-----------|---8--------------------|------------------------|---12----12-10-7--------|
G|---------10----9--------|9-----------------------|------------------------|------------------7--5--|
D|------------------10-8--|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---7-----10----13----12-|---10----8-----7-----5--|---8--------------------|
B|---5-----8-----10----8--|------------------------|------------------------|---------10-------8-----|
G|4-----------------------|------------------------|------------------------|------------------------|
D|------5-----------------|------------------------|------------------------|---------------------9--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------7-----------|------------------------|------------------------|
B|---10-------------------|---------8--------10----|8--10-10----------------|------------6-----------|
G|10----10----------------|------9-----------------|---------10-------5--4--|------------------4-----|
D|------------------------|------------------------|------------10-7--------|---5--------3--5--------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_Jazz3-150-C_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|---7--10-9-----8--7-----|
B|------------5--------3--|------------------------|------------5--8--5--7--|8--------------------10-|
G|---------------5--------|---4--------------------|---------5--------------|------------------------|
D|------------------------|------3-----3-----------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---8--------------------|---------8--------------|------13----12----10----|------11----------------|
B|10----10----8-----------|---8--11----------------|------------------------|---12----12-10----------|
G|---------10----9--------|9-----------------------|------------------------|---------------11-------|
D|------------------10-8--|------------------------|------------------------|------------------12-10-|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------10----13----12-|---10----8-----7-----5--|---8-----5--------------|
B|---------8-----10----8--|---12-------------------|------------------------|------------------8--0--|
G|---9--------------------|------------------------|------------------------|------------------------|
D|9-----------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---5--------------------|---------3--7-----5-----|4-----5-----------------|------------------------|
B|6-----6-----------------|------5-----------------|---------6--------------|---------------------3--|
G|------------------------|------------------------|------------5-----5--4--|------------------4-----|
D|------------------------|------------------------|---------------7--------|---5--------3--5--------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Jazz3-150-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Jazz3-150-C_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_Rock1-130-A_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
107         212                  209                    138           0.6603        0.6509        0.4276                          0.6522

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_Rock1-130-A_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---------2--------------|
G|------2--------2-----2--|0--------2-----2--------|2-----2--------2--------|---------2--2-----------|
D|------2--------2--------|2--4--4--2--2--2-----0--|2-----2-----2--2--------|------4--2-----2--5-----|
A|------0-----0--0-----0--|0--0--0--0-----0--0--0--|0--0--0-----0--0-----0--|0--0--0--0--0--0--5--5--|
E|------------------------|------------------------|------------------0-----|------------------------|

e|2-----------2-----------|------------10-10-10----|------------------------|------------5-----------|
B|------------0--------7--|---7-----0--7-----------|------2-----------------|------------------------|
G|7--7-----7--7--------7--|---7-----7--7--7--7--4--|2--2--2-----2--2--------|0--------2-----2--------|
D|7-----0-----------0--7--|---0--9--0--9-----7-----|2--2--2--------2--------|---4--4-----2--2--------|
A|5--5-----5--5--------5--|------------5--5--5--0--|0--0--0-----0--0--0--0--|0--7--0--7-----0--0-----|
E|5-----5--5--------5--5--|------5-----7-----------|------------------------|---5-----5-----------0--|

e|------------------------|------------3--2--10----|------------------------|------------------------|
B|------5--------------3--|---7--7-----3-----7-----|------2-----------------|------------------------|
G|1--4--4-----4-----------|7--7-----2--2-----7-----|------2-----------------|---------2--2-----------|
D|2--6--6--------6--2--0--|---7--7--0--0-----7--5--|2--2--2--------2-----2--|5-----4--2--2--2--------|
A|2-----2--------2--------|---5--0-----0-----5--5--|0--0--0--0--0--0-----0--|0-----0--0--0--0--------|
E|0--------------------5--|---5-----5--0--------5--|------------------------|---5--------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 3 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_Rock1-130-A_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------2--------2--------|---------2-----2--------|
G|---------2-----2--------|2-----2--2--2--2--2-----|------2--------2--------|2--------2--2--2--0-----|
D|------2--------2--------|5--4--4--2--2--2--2--0--|2--2--2--2--2--2-----7--|5--5--4--2--2--2--0--0--|
A|------0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0-----------------------|------------0--0--------|
E|------------------------|------------------------|------------------------|------------------------|

e|2-----------2--------2--|---2--------2-----2-----|------------------------|------------------------|
B|------3--3--3-----3--3--|---3-----3--3-----3-----|------2--------2--------|------------------------|
G|2--2--2--4--4-----2--2--|---4-----4--4--4--2--1--|------2--------2--------|2-----2--2--2--2--------|
D|0--0--0--0--0-----0--0--|0--0--0--0--0--0--0-----|2--2--2--------2--------|5--4--4--2--2--2--0-----|
A|------------------------|---------------------0--|0--0--0--0--0--0--0--0--|0--0--0--0-----0--0-----|
E|------------------------|------------------------|------------------------|---------------------0--|

e|------0--------------2--|---2--2--3--3--3--2-----|------------------------|------------------------|
B|------0--0--0--0-----3--|3--3--3--3--3-----3-----|------2--------2--------|------------------------|
G|1-----1--------1--4--1--|---2-----2--2-----2--0--|------2--------2--------|------------------------|
D|2--2--------------2--0--|---0-----0--------0--0--|2--2--2--------2-----2--|5-----4--2--2--2-----0--|
A|2--2--------------------|------------------------|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--------|
E|0--0--------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 3 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock1-130-A_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock1-130-A_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_Rock1-130-A_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
50          58                   58                     53           0.9138        0.9138        0.7069                          0.7736

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_Rock1-130-A_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|---------------8--------|------------------------|------------------------|
B|------------------8--10-|---------------------10-|8--10----------10-8--5--|------------------------|
G|---------------9--------|------------------------|------------------------|---------------5--6--7--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------5-----------------|---5--------------------|------------------------|------------------------|
B|6--7-----7--------5--6--|7-----7-----------------|------------------------|---8--------------------|
G|---------------7--------|---------7--5-----5--5--|5--6--9-----------------|------9-----9--7--6-----|
D|------------------------|------------------------|------------------------|---------------------7--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------9-----|7-----------------------|------8-----10-8-----8--|10-------10-------------|
G|---7--------8--9-----8--|---7--5--------5--6-----|6--9--------------9-----|------------------------|
D|9-----------------------|------------7-----------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------5-----------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_Rock1-130-A_solo
-------------------------------------------
e|---------------------5--|---------------7--8--5--|---------------5--------|------------------------|
B|---------------5--8-----|------------------------|8-----------------8--5--|------------------------|
G|------------------------|------------------------|------------------------|---------------5--6--7--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------5-----------------|---5--------------------|------------------------|------------------------|
B|6--7-----7--------5--6--|7-----7-----------------|------5-----------------|---8--5-----5-----------|
G|------------------------|---------7--5-----5--5--|5--6--------------------|---------------7--6-----|
D|------------------------|------------------------|------------------------|---------------------7--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------5-----------|5--------5--------------|
B|------------------9-----|7-----------------------|---5--8--------8--5--8--|------------------------|
G|---7--------8--9-----8--|---7--5--------5--6-----|6-----------------------|------------------------|
D|9-----------------------|------------7--------7--|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock1-130-A_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock1-130-A_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_Rock3-117-Bb_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
35         241                  244                    188           0.7705        0.7801        0.4041                          0.5213

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_Rock3-117-Bb_comp — combined_all_tuned
--------------------------------------------------------------------
e|------10----------------|---------------5--5-----|------3-----------------|------------------------|
B|------11----------------|------6-----6-----6-----|------3-----------3-----|------6-----6--3--3-----|
G|------7-----------7-----|------5-----------5-----|---3--3--------3--3-----|------7-----------------|
D|------8--------8--8-----|7--7--7--------7--7-----|5--5--5--------5--------|7-----7-----7--7--7-----|
A|------8--------8--8-----|8--8--8--------8--8-----|---------------------5--|5--5--5-----5--5--5-----|
E|------6-----------------|------5-----------------|------------------------|---------------------5--|

e|------------------------|------------------------|------------------------|------------------5-----|
B|------------------4-----|------3-----------3-----|---4--4-----4-----4-----|6--6--6--------6--6-----|
G|0--8--8-----8--8--0-----|------3--------7--------|0--0--3-----------------|------5-----------5-----|
D|---5--8--------5--8-----|---0--3--------0--8-----|------5-----5--5--------|3--3--7-----7--7--7-----|
A|6--6--6--------6--6-----|------5-----------8-----|6--6--6-----------------|------8--------8--8--5--|
E|------------------------|6--6--6-----6--6--6-----|------------------------|------------------------|

e|------------------------|---------------5--------|------3-----3-----3-----|------1--------5--------|
B|------3-----3-----3-----|------6-----6--6--6-----|------3-----------3-----|------3-----6--3--3-----|
G|3--3--3--------3--3-----|------5-----------5-----|---3--3-----------3-----|2--2--2-----2--2--2-----|
D|3--3--3--------3--3--5--|7--7--7-----7--7--7-----|5--5--5-----------5-----|0-----0-----------5--5--|
A|------------------------|8--8--8--------8--8-----|------------------------|---------------5--5-----|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------11----|---------3--------------|------11----------------|------1--5--------------|
B|------4-----4-----------|------3--------3--------|------4--------4--4-----|------1--------6--6-----|
G|------3-----------8-----|------3-----------------|0--8--0--------0--3-----|2--2--2-----------5-----|
D|------5--------5--8--5--|------3--------0--3-----|---5--8-----------5-----|3--3--3-----7--7--7-----|
A|------6-----------10----|------5-----------------|6--6--6--------6--6-----|------0--------8--8-----|
E|------------------------|6--6--6--------6--6--5--|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_Rock3-117-Bb_comp
--------------------------------------------
e|------------------------|------1-----1-----------|------3-----3-----3-----|------1-----1-----------|
B|------3-----2-----3-----|------1-----1-----1-----|------3-----3-----3-----|------3-----------2-----|
G|------3-----3--3--3--3--|2--2--2--------2--2-----|3--3--3--------3--3--2--|2--2--2--------2--2-----|
D|------3--------3--3--0--|3--3--3-----2--3--3--4--|5--5-----------5--5--0--|0--0--0-----0--0--0-----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------3-----3-----------|------3-----3-----------|------------2--3--2-----|------1-----1-----1-----|
B|------4-----4-----4-----|------3-----3-----3-----|------4-----4-----4-----|------1-----1-----1-----|
G|------3-----------3-----|------3-----------3-----|------3--------3--3--1--|2--2--2--------2--2--1--|
D|5--5-----------5--5-----|------3-----------3-----|5--5--5-----5--5--------|3--3--------3--3--3--0--|
A|6--6-----------6--------|---5--5--------5--------|6--6--------------------|------------------------|
E|------------------------|6--6--------6--6--------|------------------------|------------------------|

e|------------------------|------1-----1-----1-----|------3-----3-----3-----|------1-----1-----0-----|
B|------3-----3-----3-----|------1-----1-----1-----|------3-----3-----3-----|3-----3--------3--3-----|
G|3--3--3--------3--3--0--|2--2--2--------2--2-----|3--3--3-----------3-----|2--2--2--------2--2--0--|
D|3--3--3--------3--3-----|3--3-----------3--3-----|5--5--------------5-----|0--------------0--------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------3-----3-----------|------3-----3-----------|------3-----3-----3-----|------1-----1-----1-----|
B|------4-----4-----4-----|------3-----3-----------|------4-----4-----4-----|------1-----1-----1-----|
G|------3-----------3--0--|------3-----3-----3-----|------3-----------3-----|2--2--2--------2--2-----|
D|------5--------5--5-----|------3-----------3-----|5--5--5--------5--5-----|3--3-----------3--------|
A|------6-----------------|------5--------5--5--0--|6--6-----------6--------|------------------------|
E|------------------------|6--6-----------6--------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock3-117-Bb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_Rock3-117-Bb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_SS1-100-C#_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
146         111                   98                     87           0.8878        0.7838        0.4402                          0.5287

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_SS1-100-C#_solo — combined_all_tuned
------------------------------------------------------------------
e|---9--------13----11----|9-----9--------------11-|13----13----13-11-------|9-----------------------|
B|------------9-----7-----|------------------------|9-----9-----9--------13-|---------------------11-|
G|---10----11----------9--|10----10-------------11-|---------------11----9--|10----------------12----|
D|------------------------|------------------------|------------------------|---------------10-10----|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------18-------------|---------------9--------|---12----11-7--8--9-----|------12-13-------------|
B|10-------11-------------|7-----10-11-------11----|---8-----7--------6-----|---7--8--9--------------|
G|---------------------10-|------5--6-----6--6-----|------------9-----------|------------------------|
D|---------11----7-----7--|8-----------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---8--------8-----8-----|---6--12----------------|---12----11-10----9-----|---8--------11----9-----|
B|---7-----7--------7-----|---------12-11----11----|---8-----7--6-----6-----|---------9--7-----6-----|
G|------------------------|---9--------9-----9-----|------------------------|---9--10----------------|
D|6-----6-----6--------6--|---------------------9--|------------------------|------------------------|
A|------------------------|8--------------------10-|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_SS1-100-C#_solo
------------------------------------------
e|---9-----11-13----11----|9-----9--------------11-|13----13----13-11----8--|9-----------------3--6--|
B|------------------------|------------------------|------------------------|------------------------|
G|---10----11-13----11-9--|10----10-------------11-|13----13----13-11----9--|10-------------5--------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|5--4-----6-----2-----1--|2-----5--6--------6-----|---12----11-7--8--9-----|---11-12-13-------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------6-----2-----2--|3-----5--6-----6--6-----|---12----11-9-----10----|---11-12-13-------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------12-11-------------|---12-13-11-10----9-----|---8--9--13-11----9-----|
B|---13----13-13----13-13-|---11----12-11----11----|------------------------|------------------------|
G|---11----11-11----11-11-|---9--------9-----9-----|---12----11-10----10----|---9--10-11-11----10----|
D|------------------------|------------------------|------------------------|------------------------|
A|11----11----11-10----11-|9-----9-----8--9--------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_SS1-100-C__solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_SS1-100-C__solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 03_SS1-68-E_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
62         256                  345                    198           0.5739        0.7734        0.2962                          0.4495

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 03_SS1-68-E_comp — combined_all_tuned
----------------------------------------------------------------
e|------------------------|---------------10-------|------------5--0-----0--|------------------------|
B|---------5-----------5--|5--5-----5-----5-----5--|---------5--5--------5--|---5-----5--------------|
G|---------4--4--------4--|1--4--6--4--1--4-----4--|---------4--1--------2--|---4-----2-----4-----4--|
D|0--2-----0--2--2--2--2--|---2--2--2-----9-----2--|0--0-----2--0-----0--2--|0--------0--2--0-----5--|
A|2-----4-----------4--0--|---0--5--0-----5--4--0--|2--2--4-----7--0--4--5--|7--5--4--------2--4-----|
E|0--7-----5--10-5--0--0--|0--0--0--0--12----0--5--|0--0-----5--0-----------|7--7--0--5--7-----------|

e|---------10-------------|---5--10----------------|5-----------5--------24-|------9-----------------|
B|------7--------------5--|2-----------5--------5--|---------3-----------10-|---0-----5-----------5--|
G|---------7--6-----7-----|---0--7--7--------7-----|------------4--------9--|------------4-----------|
D|------7-----5--5--5--5--|5-----5--5--5-----5--0--|---0-----7--6--0-----0--|0--6-----0--------------|
A|7--8--9--7--7--7-----0--|7--7--7--0--7--7--------|5--7--5--5--5-----5--7--|7--7--5--0--5--5--5--5--|
E|5--5--5--5--5-----5-----|---5--------5--------5--|0--7-----5--7--6-----9--|0--7--------7-----------|

e|------------2-----------|------24-5--------------|5--------------------5--|---------5--19----------|
B|---0--0--0-----0-----0--|------------3-----2-----|---------5--0--------5--|5--------5--------------|
G|4--4-----2-----2--2-----|---6-----6--0-----0-----|4--------4-----------4--|---4-----6--4-----1-----|
D|1--1--------------1-----|2--5--------2--2--2--2--|0--0-----7--6--------7--|0--0-----0--6--18-0-----|
A|2--2--2--2--2--2--2--0--|0--7--0--7-----0--0--0--|2-----4-----7--7--5--0--|7-----5-----5--2--2-----|
E|------------------------|---5--24-5--5-----------|---5--------0--0--------|0--7-----5--7--0--4-----|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 58 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 03_SS1-68-E_comp
----------------------------------------
e|---------0-----------0--|---------0-----------0--|---------0-----------0--|---------0--------------|
B|---------0-----------0--|---------0-----------0--|---------0--------------|---------0-----------0--|
G|------------1-----------|1-----------1-----------|------------1--------2--|---------------------0--|
D|0-----1--0--0-----0-----|0-----0-----0--0--0-----|0--0--0-----0--0--0--0--|0--0--0--0--0--0--0-----|
A|2--2--4--0--2--0--4--0--|2--0--4--0--2--2--4--0--|2--2--4--0--2--0--4-----|2--2--4--0--2--2--4-----|
E|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0-----|0--0--0--0--0-----------|0-----------0--0--------|

e|---------------------0--|---------0--0--------0--|---------------------0--|---------0-----------0--|
B|---------3--2-----3-----|2-----3--3--2-----3--3--|---------------------0--|---0-----0--------------|
G|0-----------0--0--0--0--|0--0--0--0--0--0--0-----|---------2--1-----------|---1--------------------|
D|2-----4-----2--2--4-----|2--2--4-----2--2--4--0--|0--0--0--0--0--0--0--0--|0-----0--0--0--0--0--0--|
A|0--0--0--0-----------0--|0--0-----0-----------0--|2--2--4-----2-----4-----|2-----4--0--2--2--4-----|
E|------------------------|------------------------|0--0--------------------|0-----------------------|

e|------------2-----------|------0-----0-----------|---------0-----------0--|---------0-----------0--|
B|---0-----0-----0--------|---2-----2--3-----2--0--|---------0-----------0--|---------0--0--------0--|
G|---------2-----2--------|---0--------0-----0-----|---------2--1--------2--|---------1--1-----1-----|
D|---1--------------1-----|2--------2--2-----2-----|0--0--0-----------0-----|0-----0-----0-----0-----|
A|2-----2--------------0--|0--------0--0--0-----0--|2--0--4-----------4-----|2--2--4-----2-----2-----|
E|------------------------|------------------------|------------0--0--0--0--|------------0--0--0-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 6 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_SS1-68-E_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/03_SS1-68-E_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_BN1-147-Gb_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
134         169                  154                    127           0.8247        0.7515        0.7802                          0.9921

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_BN1-147-Gb_comp — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|2-----2--------------2--|---2-----2-----2--------|------2--------------2--|---------2--------------|
G|3-----3--------3-----3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
D|3-----3--------------3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
A|------1-----------------|---1-----------1--------|---------------------1--|---------1--------------|
E|2-----2--------------2--|---------2-----2-----0--|2-----2--------2-----2--|---2-----2--------------|

e|------------------------|------------------------|------------------------|------------------------|
B|4-----4--------4-----4--|---4-----4-----------0--|2-----2--------2-----2--|---------2--------------|
G|4-----4--4-----4-----4--|---4-----4-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
D|4-----4--------4-----4--|---4-----4-----4-----2--|3-----3--------3-----3--|---3-----3-----3--------|
A|2-----2--------2-----2--|---2-----2-----2--------|------1--------------1--|---1-----1-----1--------|
E|------------------------|---------------------0--|2-----2--------------2--|---------2--------------|

e|---------------------2--|------------------------|------------------------|------------------------|
B|6-----6--------6-----4--|---------4-----4--------|---------------------2--|------------2-----------|
G|5--------------------4--|---3-----4-----4--------|3-----3--------3-----3--|---3-----3-----3--------|
D|6-----6--------------4--|---------4-----4--------|3-----3--------3-----2--|---------2--------------|
A|4-----4--------------2--|---------2-----2--------|------------------------|------------------------|
E|------------------------|---7-----------------0--|2-----2--------------2--|---------2--------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_BN1-147-Gb_comp
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|2-----2--------2-----2--|---2-----2-----2--------|2-----2--------2-----2--|---2-----2-----2--------|
G|3-----3--------3-----3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
D|3-----3--------3-----3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
A|------------------------|------------------------|------------------------|---------------------0--|
E|2-----2--------2-----2--|---2-----2-----2-----0--|2-----2--------2-----2--|---2-----2-----2--------|

e|------------------------|------------------------|------------------------|------------------------|
B|4-----4--------4-----4--|---4-----4-----4--------|2-----2--------2-----2--|---2-----2-----2--------|
G|3-----3--------3-----3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
D|5-----4--------4-----4--|---4-----4-----4--------|3-----3--------3-----3--|---3-----3-----3--------|
A|2-----2--------2-----2--|---2-----2-----2--------|------------------------|------------------------|
E|------------------------|---------------------0--|2-----2--------2-----2--|---2-----2-----2--------|

e|------------------------|------------------------|------------------------|------------------------|
B|6-----6--------6-----4--|---4-----4-----4--------|2-----2--------2-----2--|---2-----2-----2--------|
G|5-----5--------5-----3--|---3-----3-----3--------|3-----3--------3-----3--|---3-----3-----3--------|
D|6-----6--------6-----4--|---4-----4-----4--------|3-----3--------3--------|------------------------|
A|4-----4--------4-----2--|---2-----2-----2--------|------------------------|------------------------|
E|------------------------|---------------------0--|2-----2--------2-----2--|---2-----2-----2-----0--|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_BN1-147-Gb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_BN1-147-Gb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_BN3-119-G_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
29         172                  184                    159           0.8641        0.9244        0.4326                          0.4843

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_BN3-119-G_comp — combined_all_tuned
-----------------------------------------------------------------
e|---------------------2--|---2--------2-----2-----|3-----3--------3--------|---2--------2-----------|
B|3-----3--------3-----3--|---2--------2-----2-----|3-----3--------3--------|---3--------3-----3-----|
G|4-----4--------4-----2--|---2--------2-----2-----|0-----------------------|---2--------2-----2-----|
D|4-----4--------4-----0--|---0-----0--4-----0-----|2-----2--------2--------|------------------------|
A|------------------------|------------------------|---------------------2--|---2-----2--2-----2-----|
E|3-----3--------3--------|------------------------|------------------------|------------------------|

e|------0--------0--------|------------------------|------------------------|------------------------|
B|5--------------------0--|3--3--------3-----------|---------------1--------|---7--------7-----7-----|
G|------5--------5-----0--|---4--------4-----4-----|------0--------0--------|---2--------2-----2--4--|
D|------------------------|---5--------5-----5-----|------2--5-----2--------|------------0-----0-----|
A|3-----3--------3--------|---5--------------------|3-----3-----3--3-----5--|---5-----5--------------|
E|---------------------3--|---3-----3--3-----3-----|------------------------|------------------------|

e|------------------------|---2--------2-----2-----|------3--------3--------|---2--------2-----2-----|
B|------3--------3--------|---2--------2-----2-----|------3--------3--------|---3--------3-----3-----|
G|------4--------4--------|---2--------2-----2-----|------0-----------------|4--2--------2-----2-----|
D|------4--------4--------|---4-----0--------0-----|2-----2-----2-----------|------------------------|
A|---------------------5--|---5--------------------|---------------------2--|---2-----2--------2--0--|
E|3-----------3-----------|------------------------|------------------------|------------------------|

e|------0--------0--------|------------------------|------0-----------------|------------5-----------|
B|------------------------|---3--------3-----------|---------------5--------|---7--------7-----7-----|
G|------4--------4--------|---4--------4-----4-----|------4--------4--------|---2--------------2-----|
D|------5--------5--------|---4--------4-----4-----|------5-----5--5--------|---0--------------------|
A|3-----------3-----------|------------------------|3-----------3--------5--|---------5--5-----5-----|
E|---------------------3--|---------3--------3-----|------------------------|------4-----------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_BN3-119-G_comp
-----------------------------------------
e|------------------------|------------------------|7-----------------------|------------------------|
B|3-----3--------3-----7--|---7--------7-----7-----|8-----8--------8--------|---7--------7-----7-----|
G|4-----4--------4-----6--|---6--------6-----6-----|7-----7--------7--------|---7--------7-----7-----|
D|4-----4--------4-----7--|---7--------7-----7-----|------------------------|---7--------7-----7-----|
A|---------------------5--|---------5--------5-----|7-----7--------7--------|------------------------|
E|3-----3--------3--------|------------------------|---------------------7--|---------7--------7-----|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------------3--|---3--------3-----3-----|------1--------1--------|---7--------7-----7-----|
G|9-----9--------9-----4--|---4--------4-----4-----|------0--0-----0--------|------------------------|
D|10----10-------10----5--|---5--------5-----5-----|------2--------2--------|---7--------7-----7-----|
A|------------------------|------------------------|3-----------3--------5--|---------5--------5-----|
E|8-----8--------8-----3--|---3-----3--------3-----|------------------------|---------------------0--|

e|------------------------|------------------------|------------------------|------------------------|
B|------3--------3--------|---7--------7-----7-----|------8--------8--------|---7--------7-----7-----|
G|------4--------4--------|---6--------6-----6-----|------7--------7--------|---7--------7-----7-----|
D|------4--------4--------|---7--------7-----7-----|------------------------|---7--------7-----7-----|
A|---------------------5--|---------5--------5-----|7-----------7-----------|---------------------0--|
E|3--------0--3-----------|------3-----------------|------------------0--7--|---------7--------7-----|

e|------------------------|------------------------|------------------------|------------5-----------|
B|------5--------5--------|---3--------3-----3-----|------5--------5--------|---7--------7-----7-----|
G|------4--------4--------|---4--------4-----4-----|------4--------4--------|------------------------|
D|------5--------5--------|---4--------4-----4-----|------5--------5--------|---7--------------7-----|
A|3-----------3-----------|------------------------|3-----------3--------5--|---------5--------5-----|
E|---------------------3--|---------3--------3-----|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_BN3-119-G_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_BN3-119-G_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Funk2-119-G_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
20         124                  100                     87             0.87        0.7016        0.1964                          0.2529

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Funk2-119-G_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------6-----6-----|------------------------|------------------------|------------------------|
G|---5--7--8--------------|---5--7--8--10-8--7--5--|7-----------7-----------|---------------------7--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|8--------7--8--7--5-----|------------------------|------------------5--5--|6--7--7--7--7--7--6--7--|
D|---------------------8--|7--------5--4--5--7--4--|5--5--7--7--8-----------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---------14-------20----|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---------------------3--|
G|7--7--7--7--7--6--6-----|------------------------|---------------------7--|5--3--------------3-----|
D|---------------------10-|10-10-10----10-10----10-|10-8--8--8--8--8--8-----|------------------------|
A|------------------------|------------------15----|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---16-------------------|---15----------------20-|---10-------10----------|
B|4--------6--------------|---9--------11-9--11----|---------10-11-------13-|------------------------|
G|------------8--7--------|---------------------13-|12-12-------------------|------------------------|
D|------------------10----|9-----------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------7-----------|
E|------------------------|------------------------|------------------------|---0--------0-----0-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 4 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Funk2-119-G_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------3--4--6-----6-----|------3--4--6--4--3-----|3-----------------------|---------------------3--|
G|---5-----8--------------|---5-----8-----8-----5--|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|4-----------4--3--------|------------------------|------------------------|2--3--3--3--2--3--2--3--|
G|------------8-----5--3--|2-----------------2-----|------2--2--3--3--5--5--|------------------------|
D|------------------------|---------5--4--5-----4--|5--5--5-----------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|3--3--3--3--3-----------|------------------------|---------------------3--|---------------------3--|
G|---------------6--5--5--|5--5--5--5--5--5--5--5--|5--3--3--3--3--3--3-----|5--3--------------3--5--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---4--------6--4--6--4--|3-----------6--------8--|10----------------|
B|4--------6--4--3--------|------------------------|------------------------|------------------|
G|8-----------8--------5--|4-----------------------|------------------------|------------------|
D|------------------------|------------------------|------------------------|------------------|
A|------------------------|------------------------|------------------------|------------------|
E|------------------------|------------------------|------------------------|------------------|

[note: 32 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Funk2-119-G_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Funk2-119-G_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Jazz1-130-D_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
125         206                  156                    140           0.8974        0.6796        0.6519                          0.8429

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Jazz1-130-D_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------------0-----|------0-----------------|------0-----------0-----|------------------------|
B|5-----5-----------3-----|5-----3-----5-----------|5-----3-----1-----3-----|5-----5-----5-----------|
G|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----------5-----|5-----5-----5-----5-----|
D|------0-----------4-----|------4-----4-----0-----|0-----4-----4-----4-----|4-----4-----------4-----|
A|------------5-----5-----|------5-----5-----------|------5-----5-----5-----|------5-----------5-----|
E|------------------------|---------------------5--|------------------------|------------------------|

e|------------------------|------------------------|------0-----------0-----|------0-----------------|
B|------------------5-----|5-----------5-----5-----|5-----3-----------3-----|5-----3-----------------|
G|4-----4--4--4-----4--4--|4-----4-----4-----4-----|5-----5-----5-----5-----|5-----5-----5-----5-----|
D|3-----------3-----3-----|3-----------3-----3-----|------4-----0-----4-----|4-----------------0-----|
A|------8-----------------|------8-----------------|------5-----------5-----|------5-----------------|
E|------3-----------3-----|------3-----------3-----|------------------------|------------------------|

e|------------------------|------------------------|------0-----------0-----|------------------------|
B|------5-----------4-----|---3--------3-----0-----|5-----3-----5-----3-----|------------------------|
G|6-----6-----6-----5-----|---4--3-----4-----0-----|5-----5-----5-----5-----|---6--------6-----6-----|
D|5-----5-----5-----4-----|---3--------------3-----|------------0-----------|---5--------5-----5-----|
A|------------------------|------7-----------------|------5-----------5--5--|------------------------|
E|------5-----5-----4--3--|------2-----3-----3-----|------------------------|5--5--------5--5--5-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Jazz1-130-D_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|
G|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|
D|4-----4-----4-----4-----|4-----4-----4-----1-----|5-----4-----4-----4-----|4-----4-----4-----4--0--|
A|------5-----5-----5-----|5-----5-----5-----5--0--|5-----5-----5-----5-----|5-----5-----5-----5--0--|
E|------------------------|------------------------|------------------------|---------------------0--|

e|------------------------|------------------------|------------------------|------------------------|
B|4-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|5-----5-----5-----5-----|
G|4-----4-----4-----4-----|4-----4-----4--4--4-----|5-----5-----5-----5-----|5-----5-----5-----5-----|
D|3-----3-----3-----3-----|3-----3-----3-----3--0--|4-----4-----4-----4-----|4-----5-----4-----4-----|
A|------------------------|------------------------|------5-----5-----5--0--|5-----5-----5-----5--0--|
E|3-----3-----3-----3--0--|3-----3-----3-----3-----|------------------------|---------------------0--|

e|------------------------|------------------------|------------------------|------------------------|
B|------5-----5-----4-----|---3--2-----3-----3-----|5-----5-----5-----5-----|---5--5-----5-----5-----|
G|6-----6-----6-----5-----|---4--3-----4-----4-----|5-----5-----5-----5-----|---6--6-----6-----6-----|
D|5-----5-----5--0--4-----|---3--2-----3-----3--0--|4-----4-----4-----4-----|0--5--------5-----5-----|
A|------------------------|---------------------1--|5-----5-----5-----5--0--|------------------------|
E|5-----5-----5--0--4--3--|------3-----3-----3-----|------------------------|5--5--5-----5-----5-----|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz1-130-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz1-130-D_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Jazz2-187-F#_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
119         171                  117                     99           0.8462        0.5789        0.3125                          0.4545

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Jazz2-187-F#_comp — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|8-----------------------|---------5-----------7--|---------7--------------|
G|---7--------7-----7-----|7--------7-----7--------|---------6--6--------7--|---------6--7-----------|
D|------------7-----7-----|5--------5--------------|---------6-----------7--|---------7-----------6--|
A|------------------------|7--------7-----7--------|---------------------5--|------------------------|
E|7-----------7-----7-----|------------------------|5--------5--------5-----|---------10-------------|

e|------------------------|---4--------4--------5--|---------5--------------|------------4-----------|
B|------------------------|---6--------6--------5--|---------5--------------|---5--------5-----5-----|
G|------6-----------------|---4--------4-----------|------------------------|---2--------2-----2-----|
D|------------6-----------|---------------------4--|---------4-----------4--|---4-----4--------4-----|
A|------------------5-----|4--4-----4--------------|------------------------|------------------0-----|
E|------------------------|------------------------|------------------------|------5-----------------|

e|------------------------|------------------------|------------------------|---5--------14----------|
B|---------------------8--|---------6--------------|------------------------|---7--6-----10----------|
G|---7-----7-----7-----7--|---------7--------------|---------6--------------|------------11----------|
D|---7-----------------5--|6--------6--------------|---6-----6--------------|---------------------6--|
A|---------------------7--|---------7--------------|---------0-----------5--|------------------------|
E|7-----------------------|---------------------5--|---------------5--------|------------10----------|

e|------------7-----------|---5-----5--------------|------------------------|---------------5--------|
B|------------7-----------|---6-----6-----6-----5--|---------5--------------|---5--------------------|
G|------------7-----------|---4-----4-----4--------|------------------------|---2--------------------|
D|------------5-----------|---------------------4--|---------4--------------|---4--------------------|
A|------------------5-----|4-----------------------|------------------------|---0--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Jazz2-187-F#_comp
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|---7--------7-----7-----|8--------8-----6--------|---------5--5-----5--7--|---------7--------------|
G|---7--------7--7--7-----|7--------7-----7--------|---------6--6-----6--6--|---------6--------------|
D|---7--------7-----7-----|------------------------|---------6--6-----6--7--|---------7-----7--------|
A|------------------------|7--------7-----7--------|---------------------5--|---------5-----------11-|
E|7--------7--------7-----|------4-----------------|5--------5--5--5-----5--|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---12-11----12----------|---9--------9--------10-|---------10----------9--|---9--------9-----9-----|
G|---11-10----11----------|---10-------10-------9--|---------9-----------9--|---9--------9-----9-----|
D|---11-------12-12-------|---9--------9-----------|------------------------|---7--------7--7--7-----|
A|------------11----------|---------------------9--|---------9-----------9--|---9-----9--------9-----|
E|------------------10----|9--------9--------3-----|------4-----------4-----|------------------------|

e|------------------------|------------------------|------------------------|---5--4-----5-----------|
B|---7-----7-----7-----8--|---------6--------------|---5-----5-----5--------|---7--6-----7-----------|
G|---7-----7-----7-----7--|---------7--------------|---------6--------------|---6--------6-----------|
D|---7-----7-----7-----6--|------------------------|---6-----6-----6--------|------------------------|
A|---------------------7--|---------7--------------|---------------------5--|------------5--------11-|
E|7--------7-----7--------|------3--------------5--|---------5-----5--------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---12-------12----------|---10----10----10-------|---------9-----------9--|---9--------------------|
G|---11-------11----------|---10----10----10----9--|---------9-----------9--|---9--------------------|
D|---12-------12-12-------|---9-----9-----9--------|------------------------|---7--------------------|
A|---------11-------------|---------------------9--|---------9-----------8--|---9--------------------|
E|------------------10----|9--------9-----9--3-----|------3--0--------3--3--|3-----------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz2-187-F__comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz2-187-F__comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Jazz3-137-Eb_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
11         229                  189                    155           0.8201        0.6769        0.5455                          0.7355

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Jazz3-137-Eb_comp — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|3-----------------------|------------------------|
B|6--------6--6-----------|---6--------6-----------|4--------4--4--4--------|------------3-----------|
G|7--------7--7-----------|---7--7-----7-----7-----|3-----3--3--3-----------|---3--2-----3-----3-----|
D|8-----8--8--8-----------|---7--------7-----------|------------5-----------|---3--------3-----3-----|
A|6--------6--6--6--------|------------------------|3--------3--------------|------------------------|
E|6--------------------6--|---6--------6-----6-----|---------------------3--|------------3-----3-----|

e|------------------------|---3--------3-----------|------------------------|------------------------|
B|4--------4--4--------3--|---3--------3-----3-----|4--------4--------------|------------------6-----|
G|5--------5--5--0-----3--|---3--------3-----3-----|5--5-----5--0--------7--|------8-----9-----------|
D|5--------5--5-----------|---5--5-----5-----5-----|5--------5-----------6--|------------7-----0-----|
A|---------------------6--|---6--------------6-----|------------------------|------3-----4-----------|
E|4--------4-----4--------|------------------------|4--4-----4--4--4-----6--|------------5-----------|

e|------------------------|------------------------|------------3-----------|------------------------|
B|---8-----8--------------|------------------------|---4--------4--------3--|---------------3--------|
G|8--------8-----7-----7--|------6--7--------------|---3--------3--------3--|------2--3-----3-----5--|
D|---------8-----------6--|------5--6--------------|---------------------3--|------2--3-----3--------|
A|6--------10-------------|------0-----------2--3--|---------3--------------|------------------------|
E|---------11----------6--|---------6--------------|---------------------3--|---------3-----6--3--4--|

e|---------------------3--|------2-----3-----------|------------------------|------------------------|
B|---------4-----------4--|------2--4--3-----------|---4--------4-----------|6-----------6-----------|
G|---------5-----5-----3--|---------0-----------0--|---5-----5--5-----------|7-----------7-----------|
D|5--------5-----5-----5--|------7-----------------|---5--------5-----------|6-----------6--6--------|
A|---------------------6--|------5--6--------------|------------------------|------------------------|
E|---------4--------------|---------------------4--|---4--------------4-----|6--------6-----6--------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Jazz3-137-Eb_comp
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|6--------6--6--6-----6--|---6--------6-----6-----|8--------8--8--8--------|---3--------3-----3-----|
G|7--------7--7--7-----7--|---7--------7-----7-----|8--------8--8--8--------|---3--2-----3-----3-----|
D|8--------8--8--8-----7--|---7--------7-----0-----|8--------8--8--8--------|---3--2-----3-----3--0--|
A|6--------6--6--6--------|------------------------|------------------------|------------------------|
E|---------------------6--|---6--------6-----6-----|8--------8--8--8-----3--|------2-----3-----3-----|

e|------------------------|------------------------|------------------------|------------------------|
B|4--------4--4--4-----8--|---8--------8-----8-----|4--------4--4--4--------|------------------------|
G|5--------5--5--5-----7--|---7--------7-----7-----|5--------5--5--5-----7--|------8-----9-----10----|
D|5--------5--5--5-----8--|---8--------8-----8-----|5--------5--5-----0--6--|---0--------------------|
A|---------------------6--|---6-----6--------6-----|------------------------|------------------------|
E|4--------4--4--4--------|------------------------|4--------4--4--4-----6--|---0--8-----9-----10----|

e|------------------------|------------------------|------------------------|------------------------|
B|---8-----8-----8--------|------------------------|---8--------8--8-----3--|------2--3-----------4--|
G|---7-----7-----7-----7--|------6--7--------------|---8--------8--8-----3--|------2--3-----------5--|
D|---8-----8-----8--0--6--|------5--6--------------|---8--------8--8-----3--|------2--3-----3-----5--|
A|6--------6-----6--------|------------------------|------------------------|------------------------|
E|---------------------6--|------5--6--------7--8--|---------8-----8-----3--|------2--3--------3--4--|

e|------------------------|------------------------|------------------------|------------------------|
B|---------4-----4-----8--|------7--8-----8-----4--|---4--------4-----4-----|6-----------6--6--------|
G|---------5-----5-----7--|------6--7-----6-----5--|---5--------5-----5-----|7-----------7--7-----7--|
D|---------5-----5-----8--|---------------------5--|---5--------5-----5--0--|6-----------6--6-----8--|
A|---------------------6--|------5--6-----6--------|------------------------|---------------------6--|
E|---------4--4-----------|---------------------4--|---4-----4--------4-----|6--------6--------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz3-137-Eb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Jazz3-137-Eb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Rock1-130-A_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
89         190                  178                    158           0.8876        0.8316        0.2554                          0.2975

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Rock1-130-A_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------2--2--------|------------2-----------|---------------2--------|------------------------|
D|2-----4-----------4--2--|---2--4--2--2--2--4--2--|2--2--4--2--2-----4--2--|------4--2--2--2--4-----|
A|------0-----7-----0-----|------0--0--0--0--0-----|------0-----------0-----|------0--0--0--0--0-----|
E|5--5-----5--5--5-----5--|---5-----------------5--|5--5-----5--5--5-----5--|5--5--------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------3-----0--3--|------------3--3--0-----|------------------------|------------------------|
G|2-----4-----------------|---2--4--2--2--2--------|2-----2--------2--------|------------------------|
D|------0-----7--------7--|------0--0--0--0--0-----|2--2--4-----2-----4--2--|---2--4-----2--2--4-----|
A|5--------5--5--5--5--5--|5--5-----------------0--|0--0--0-----------0-----|------0-----------0-----|
E|------------------------|------------------------|---------5--5--5-----5--|5--5-----5--5--5--------|

e|---0--------------------|------------------------|------------------------|------------------------|
B|------2--0--0--0-----3--|------0--------3--------|------------------------|------------------------|
G|4-----------------------|2--2--------2--2--4-----|---2-----2--2--------2--|------------2-----------|
D|2--2--2--2--2--2--2--0--|0--0--0--0--0--0--0--2--|2--2--4-----------4-----|---2--4--------2--4-----|
A|------------------------|------------------------|0--0--0-----7-----0--7--|------0-----7-----0-----|
E|------------------------|------------------------|---------5--5--5-----5--|5--5-----5--5--5--------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Rock1-130-A_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|7-----9-----7-----9--7--|---7--9-----7--7--9--7--|7--7--9--7--7-----9--7--|------9-----7--7--9-----|
E|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|7-----------7--------7--|------------------------|------------------------|------------------------|
D|7-----9--9--7-----9--7--|---7--9--7--7--7--9-----|7-----5-----7-----6--7--|------5--------7--5-----|
A|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5-----|7--7--9--9--7--7--9--7--|---7--9--9--7--7--9-----|
E|------------------------|------------------------|5--5--5--5--5-----5--5--|5--5--5--5--5--5--5-----|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|9--------------------7--|------------7-----------|------------------------|------------------------|
D|9-----11----9--9--10-7--|---7--9--9--7--7--9-----|---7--4-----7-----7--7--|------5--4--7-----4-----|
A|7--7--7--7--7--7--7--5--|5--5--5--5--5--5--5-----|7--7--9--9--7-----9--7--|7--7--9--9--7--7--9--7--|
E|------------------------|---------------------0--|5--5-----5--5--5--5--5--|5--5--5--5--5--5--5--5--|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 1 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock1-130-A_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock1-130-A_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Rock1-90-C#_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
41          74                   81                     61           0.7531        0.8243        0.6065                          0.7705

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Rock1-90-C#_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------6-----------|------------------------|------------------4-----|---------------------7--|
G|------------------------|---------6--6-----6--6--|6--------------------6--|---6-----------6--6--8--|
D|------------3--6--6-----|8--------------8--------|------------------------|------------8-----------|
A|---------4--------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------4--------|------------------------|---------------2--2-----|5--6--7--8--9--6--5-----|
G|6--------------------6--|------------6--4--------|------1-----3--------3--|---------------------6--|
D|------------------------|------------------6--4--|2--3-----3--------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------5-----------|------------------------|------------------------|
B|---------------------5--|5-----5--8--7-----6-----|5-----------------------|------------------------|
G|6--6-----------4--6-----|------------9--6-----6--|6--6--6--4--3--6--------|---------6--6-----------|
D|------------------------|------------------------|------------------6--4--|3--6--8-----------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

[note: 10 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Rock1-90-C#_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|---------------------2--|
B|------------------------|------------------------|------------------4--2--|---2-----------2--2--4--|
G|------------------------|2--6--5--7-----3--4--6--|------------------------|------------3-----------|
D|------------3--6--6--3--|------------------------|------------------------|------------------------|
A|---------4--------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|2--------------4-----1--|------------------------|------------------------|5--6--7--8--9--6--5-----|
G|------------------------|------------6--4--------|------------3--6--6--3--|---------------------6--|
D|------------------------|------------------6--4--|2--3--6--3--------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------5-----------|------------------------|------------------------|
B|---------------------5--|------5--8--5-----5-----|5-----------------------|------------------------|
G|---------------4--6-----|---------------6-----6--|6--------4--3--6--------|------2--6--------------|
D|------------------------|------------------------|------------------6--4--|3--6--------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

[note: 10 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock1-90-C__solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock1-90-C__solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Rock2-142-D_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
137         353                  280                    233           0.8321        0.6601        0.5814                          0.7897

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Rock2-142-D_comp — combined_all_tuned
-------------------------------------------------------------------
e|------3--------3--------|------3--------3--------|---------------1--1-----|------1--------1-----3--|
B|------3-----3--3-----5--|------5--------5--------|------1--------1-----3--|---3--3--------3--3-----|
G|------3--------0-----0--|------5-----------------|------2--------2--------|------------------------|
D|------5--------0--------|------5--------5--5--5--|------3--------3-----3--|---3--3--------3--------|
A|------5--------------3--|------3--------3-----0--|3-----3--------3-----1--|------1--------1--------|
E|3-----3--------3--------|------3--------3--------|1-----1--------------1--|------1-----------------|

e|3--------------------9--|---------------3-----5--|5-----10----5--5-----5--|------5-----------------|
B|------8-----8--8-----8--|------8-----------------|6-----6--------6--3--6--|------6--------15-------|
G|3-----7--------7-----6--|------6--------6--6-----|7-----7--------7-----7--|------7-----------------|
D|2--5--8--------8--------|------5--------2--2-----|7-----7-----7--7--7--7--|------7-----7--------5--|
A|------7--------7-----7--|------7-----------0--0--|5-----5--------5-----5--|------5--------12-------|
E|---------------------5--|------5-----5--5--------|------------------5--5--|---------------5--5-----|

e|------3--------3--3-----|------3--------3--3-----|---------------1-----1--|------1-----------------|
B|------3-----3--3--3--5--|------5--------5--------|------1--------1-----3--|---3--3--------6--------|
G|------0-----0--0--0-----|------------------0-----|------2--------2-----3--|---3--3-----3--7--7-----|
D|---5--0--------0-----5--|------5--------5-----5--|3-----3--------3-----3--|------3--------8--8-----|
A|5--------------------3--|------3--------3--------|---3--3--------3-----1--|------1--------8--------|
E|3-----3--------3--------|------3--------3--------|1-----1--------1--------|---------------6--------|

e|------6--------3-----3--|------3--------3-----5--|------5-----------------|5--5--------5--5--5-----|
B|8-----8--------3-----2--|------2--------2--------|6-----6--------------6--|------6--------6--6-----|
G|------7--------3--------|2--------2--------6-----|7-----7--------7-----7--|------7--------7--7-----|
D|8-----8-----5--5-----2--|------2--------2--2-----|7-----7-----7--7-----7--|7--7--7-----7--7--7-----|
A|7-----10-------------0--|------0-----0--0-----0--|5-----5--------5-----5--|------0-----0--5--------|
E|------12----------------|------------------5-----|5-----5--------------5--|---------------5--------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 7 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Rock2-142-D_comp
-------------------------------------------
e|------3--------3-----3--|---3--3--------3--3-----|------1--------1-----1--|---1--1--------1--1-----|
B|------3--------3-----5--|------5--------5--5-----|------1-----1--1-----3--|---3--3--------3--3--8--|
G|------3--------3--------|------3--------3--2--0--|------2-----2--2--------|------------------------|
D|------5--------5-----5--|------5--------5--5--0--|3-----3-----3--3-----3--|------3--------3--3-----|
A|------5--------------3--|------3--------3--3--0--|3-----3--------3-----1--|------1--------1--------|
E|3-----3-----------------|------3--------3--3--0--|1-----1-----1--1-----1--|------1--------1--------|

e|------------------------|---------------5-----5--|5-----5--------5--5--5--|---5--5--5--5--5--------|
B|8-----8-----8--8-----8--|---8--8-----8--8--8--4--|6-----6--------6--6--6--|------6-----6--6-----2--|
G|7-----7--------7-----6--|---6--6-----6--6--6-----|7-----7--------7--7--7--|---7--7-----7--7--7-----|
D|8-----8--------8--------|------------------------|7-----7-----7--7--7--7--|------7-----7--7--7--5--|
A|7-----7--------7-----7--|---7--7--------7--7--5--|5-----5--------5--5--5--|------5--------5--5--5--|
E|---------------------5--|------5--------5--------|------------------------|---------------5--5--0--|

e|------3--------3--3--3--|---3--3--3--3--3--3-----|------1--------1--------|---1--1--1--1--1--1-----|
B|------3-----3--3--3--5--|5--5--5-----5--5--------|------1--------1-----3--|---3--3--3--3--3--3-----|
G|------------------------|---------------------0--|------2-----2--2--1--3--|---3--3-----3--3--3-----|
D|------5-----5--5-----5--|------5--------5--5--0--|3-----3-----3--3-----3--|------3-----3--3--3-----|
A|------5--------5-----3--|------3--------3--3--0--|3-----3-----3--3--------|------------------------|
E|3-----3-----3--3-----3--|------3--------3--3--0--|1-----1-----1--1--------|------------------------|

e|------------------------|---5--5--5-----5--5--5--|------5-----5--5--------|---5--5-----5--5--5-----|
B|8-----8--------8--8--8--|---8--8--8-----8--8--5--|6-----6-----6--6-----6--|---6--6-----6--6--6-----|
G|7-----7--------7-----6--|------6-----6--6--6-----|7-----7-----7--7-----7--|---7--7--------7--7-----|
D|8-----8-----8--8--0-----|------------------------|7-----7--------7-----7--|------7--------7--7-----|
A|7-----7--------7--0--7--|7--7--7--7--7--7--7--5--|5-----5--------5-----5--|------5--------5--5-----|
E|---------------------5--|5--5--5--5--5--5--5--5--|5--------------5-----5--|------5-----------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock2-142-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock2-142-D_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_Rock3-148-C_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
77          71                   81                     62           0.7654        0.8732        0.1974                          0.2419

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_Rock3-148-C_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|---------------------20-|---------------20----20-|---------------------20-|
B|---------------8--8--10-|8--------------8--10-13-|---------------13-15-13-|------------------10-13-|
G|------------9-----------|------------------------|------------------------|---------------12-------|
D|10----------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------20----20-|---------12----13----12-|---10----20-------------|------------------------|
B|---------------13-13-13-|------------------------|---------13----------8--|---------8--------------|
G|------------------------|------------------------|------------------------|---------9-----7--5--7--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|---------4--------------|------------------------|

e|---------------20----20-|---------------19----20-|------------------------|------------------------|
B|---8--8-----10-13----13-|---------15----12----13-|---8--8--8-----8-----8--|---8--8--8-----8--10-8--|
G|9-----------------------|---16-------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|8--------------6--6--8--|---6-----8-----6--6--8--|---------------8--10-8--|------------------------|
G|------------------------|------------------------|------------------------|---9-----7--7-----------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 4 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_Rock3-148-C_solo
-------------------------------------------
e|---------------3--3--5--|3--------------3--5--8--|---------------8--10-8--|---------------3--5--8--|
B|------------5-----------|------------------------|------------------------|------------------------|
G|5--------5--------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------8--8--8--|8--------12----13----11-|12-10----8--------------|------------------------|
B|------------------------|------------------------|---------------------8--|---------8--------------|
G|------------------------|------------------------|------------------------|---------7--9--7-----7--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------8-----8--|---7-----10----7-----8--|---3--3--3-----3--4--3--|---3--3--3-----3--5--3--|
B|---8--8-----10----------|------------------------|------------------------|------------------------|
G|9-----------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------------3--|---------3-----------3--|---------------3--5--3--|------------------------|
B|---------------6--6-----|---6--6--------6--6-----|------------------------|---3-----3--------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 3 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock3-148-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_Rock3-148-C_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 04_SS1-68-E_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
74         733                  580                    445           0.7672        0.6071        0.3656                          0.5393

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 04_SS1-68-E_comp — combined_all_tuned
----------------------------------------------------------------
e|0-----0--0-----------7--|---------0-----------0--|---0--0--0--------0--0--|------0-----------------|
B|0--5--0--0--------5--5--|0--5--5--------5--5--0--|0--0--0--0-----0--0--0--|0-----5--0-----5--0--5--|
G|1--1--1--1-----1--4--4--|1--4--4--4--4--4--4--1--|4--1--1--1-----1--1--1--|1--4--4--------4--4--4--|
D|2--2--2--2-----2--6--2--|2--6--6--6--6--6--6--2--|2--2--2--2--2--2--2--2--|2--6--6--6--6--6--6--6--|
A|2--2--2--2--2--2--2-----|2--7--7--7--7--7--7--2--|2--2--2--2--2--2--2--2--|2--7--7--7--7--7--7--7--|
E|0--4--4--------0--4--4--|0--7--7--------7--------|0--------0-----0--4--0--|4--7--7--7--7-----0-----|

e|---0--0--0--5--0--0--0--|------5-----5--5--------|---0-----0-----0--0--0--|---------7--------------|
B|---0--0--0--5--0--0--5--|5--5--5--5--5--5--5--5--|0--0--0--0--0--0--0--0--|0--5--5--0-----5--5--5--|
G|2--2--2--2--4--2--2--4--|4--4--4--4--4--4--2--4--|4--1--1--1--1--1--1--1--|1--4--4--1--1--4--4--4--|
D|2--2--2-----2--2--2--2--|7-----7--7-----7--7--2--|2--2--2--2--2--2--2--2--|2--6--6--2--2--6--6--2--|
A|0--0--0--0-----0--0--0--|7--7--7--------7--7--0--|2--2--2--2--2--2--2--2--|2--7--7--2--7--2--7-----|
E|0-----0--0-----0--------|5--5--5--------5-----5--|0-----0-----------------|0-----0-----0--4--0-----|

e|---------7--7--------7--|0--0--5--0--0--0--0-----|---0-----------7--0-----|------0--0-----0--------|
B|5--5--5--5--5--0--5--5--|0--0--5--0-----0--5--5--|0--0--5--5--5--5--5--5--|0-----0--5-----0--5--5--|
G|4--4--4--4--4--9--4--4--|2--2--4--2-----2--4--4--|---1--4--4--4--4--4--4--|---4--1--1--1--1--4--4--|
D|4--4--4--4-----4--4--2--|2--2--7--2-----2--2--2--|2--2--6--6--6--6--6--6--|6--2--2--2--2--2--6-----|
A|7--7--2--2--9-----7--2--|0-----7--0-----0--0--0--|2-----7--7--7--7--7--7--|2--2--2--------2--7-----|
E|------------------7-----|0--5--5--0--------------|0-----7--7--7--7--7--0--|0--0-----4--0-----7--7--|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 135 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 04_SS1-68-E_comp
----------------------------------------
e|0--0--0--0--0-----0--0--|0--0--0--0-----0--0--0--|---0--0--0--0-----0--0--|0--0--0--0--0--0--0--0--|
B|0--0--0--0--------0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0-----0--0--|0--0--0--0--0--0--0--0--|
G|1--1--1--1-----1--1--1--|1--1--1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|
D|2--2--2--2--2--2--2--2--|2--2--2--2--2--2--2--2--|2--2--2--2--2--2--2--2--|2--2--2--2--14-14-2--2--|
A|2-----2-----2--2--2--2--|2--2--2--2--2--2--2--2--|2-----2--2--2--2-----2--|2--2--------2--2-----2--|
E|0-----------------------|0--0--------0--0-----0--|0-----------0--0--------|0--------0--0-----------|

e|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|
B|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|
G|2--2--2--2--2-----2--3--|2--3--2--3-----3--2--2--|0--1--1-----1--1--1--2--|1--1--1--------1--1-----|
D|2--2--2-----------2--2--|2--2--2-----------2--2--|2--2--2--2--2--2--2--2--|2--2--2-----2--2--2--2--|
A|0-----0-----------------|0--0-----------------0--|2--2--2-----2--2--2-----|2--2--2-----------------|
E|0-----------------------|------------------------|0--0--0-----0--0--------|0-----------0-----------|

e|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|
B|---0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0--0--0--0--0--|0--0--0--0-----0--0--0--|
G|4--4--4--4--4--4--4--4--|2--2--2--2--2--2--2--2--|---1--1--1--1--1--1--1--|1--1--1--1--1--1--1--1--|
D|4--4--4--4--4--4--4--4--|2--2--2--2-----2--2--2--|2--2--2--2--2--2--2--2--|2--2--2--2--2--2--2--2--|
A|---2-----2--------2-----|0--0--0-----------0-----|2-----------------2--2--|2--2--------2--2--2--2--|
E|------------------0-----|0--------------------0--|0--------------------0--|0-----------0--0--0--0--|

e|0--------|
B|0--------|
G|1--------|
D|---------|
A|---------|
E|---------|

[note: 286 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_SS1-68-E_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/04_SS1-68-E_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_BN1-129-Eb_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
47          44                   51                     43           0.8431        0.9773        0.3579                          0.3953

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_BN1-129-Eb_solo — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|4--------4--4-----------|6--------6--------------|8--6-----8--------6--8--|9--8--9-----------------|
G|------5--------------5--|------7-----------7-----|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------20----------|------20----------------|---------------6--------|------------------------|
B|---------11-13-16----15-|------13-11----9--8-----|---------6--8-----------|---------4--5-----------|
G|------------------------|------------------------|------------------------|---------------6--5--3--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|---------10-------------|---10-------10----------|
B|------------------------|---------------6--9--7--|8-----------------------|------------------------|
G|1-----3-----------------|---------4--7-----------|------------------------|------------------------|
D|---------5-----3--------|---3--6-----------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_BN1-129-Eb_solo
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|8--------8-----------8--|9--8--9-----------------|
G|8--------8--------------|10-------10-------------|------------------10----|------------------------|
D|---------------------10-|------12----------12----|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------8--11----10-|------8-----------------|------------------------|------------------------|
B|---------11-------------|---------11----9--8-----|---------8--8--11-------|------------------------|
G|------------------------|------------------------|---------10-------------|---------8--9-----------|
D|------------------------|------------------------|------------------------|---------------11-10-8--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|---------10-------------|------------------------|
B|------------------------|------------------9--7--|8-----11----------------|------------------------|
G|------------------------|------------7--10-------|------------------------|------------------------|
D|------8-----------------|---------9--------------|------------------------|------------------------|
A|---------10----8--------|---8--11----------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN1-129-Eb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN1-129-Eb_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_BN1-147-Gb_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
38          27                   35                     25           0.7143        0.9259        0.2258                            0.28

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_BN1-147-Gb_solo — combined_all_tuned
------------------------------------------------------------------
e|------------------------|------------------------|------------------------|---------------6--------|
B|---------------7--------|7--------9--------------|---------------9-----9--|------7-----------------|
G|---------------------6--|------8-----------------|------------------8-----|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---7-----9--7--6--------|16----7-----------------|------------------------|
B|------------------------|---------------------9--|9--------7--------------|------------------------|
G|------------------------|------------------------|------------------------|---------------------6--|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------4--------|------------------------|------------------------|------------------------|
B|---------6--------------|------------------4--7--|7-----------------------|------------------------|
G|6-----------------6-----|4--------------4--------|---------------6--4--4--|------3--4--------------|
D|------------------------|------------------------|------------------------|---------4--------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_BN1-147-Gb_solo
------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|---------------7--------|7--------9--------------|---------------9-----9--|------7--------11-------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|---12----14-12-11----9--|9-----12----------------|------------------------|
G|------------------------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|---------------------11-|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|0-----------------------|
G|---------10----13-------|------------------8--11-|11----------------------|------------------------|
D|11----------------11----|---------------9--------|---------------11-9--9--|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN1-147-Gb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN1-147-Gb_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_BN3-119-G_solo
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
122          62                   70                     57           0.8143        0.9194         0.697                           0.807

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_BN3-119-G_solo — combined_all_tuned
-----------------------------------------------------------------
e|------------------7-----|------------------5-----|---------3--------------|------------------------|
B|------------------------|------------------------|------------------------|---------7--------------|
G|---------7--------------|---------6--------------|4--------------------4--|------------------------|
D|------------------------|------------------------|------------------------|7--------7-----------7--|
A|------------------------|------------------5-----|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|3-----------------------|------------------------|
B|---------------5--------|---------3--3-----------|---------5--------------|------------------------|
G|---------4--------4-----|---2--------------------|---4-----------4--------|---------7--7-----7--5--|
D|5--------------------5--|4--------------------4--|5-----------------5-----|7-----------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------7--8--10-|10----------------------|---------------------7--|8-----------------------|
G|4--------7--------------|---------9--7--6--------|---------5-----7--9-----|------9--7--5--4--------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|7--------5--7-----5--3--|------------------------|------------------------|
G|------------4--5--7--9--|------------------------|------4--4--------------|---7--8--6--7-----5-----|
D|---------5--------------|------------------------|------------7--5--------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_BN3-119-G_solo
-----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------12----|------------------10----|---------8--------------|---------7--------------|
G|------------------------|------------------------|------------------------|------------------------|
D|---------12-------------|---------11-------------|9--------------------9--|7--------------------7--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------5--------|---------3--------------|---------5--------------|------------------------|
G|---------4--------4-----|---2--------------------|---4-----------4--------|---------8--7-----7-----|
D|5-----------------------|4--------------------4--|5-----------------5--7--|7-----------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------7--8--10-|------------------------|------------------5--7--|8-----5-----------------|
G|---------7--------------|------------------------|---------5-----7--------|---------7--5-----------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------------------5--|7--------5--7-----5-----|------------------------|------------------------|
G|------------4--5--7-----|---------------------7--|------5--4--------------|---7--8--6--7-----5--4--|
D|---------5--------------|------------------------|------------7--5--------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 2 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN3-119-G_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN3-119-G_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_BN3-154-E_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
92         185                  195                    152           0.7795        0.8216        0.7632                          0.9539

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_BN3-154-E_comp — combined_all_tuned
-----------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------7--------7-----7--|---7-----7--0-----7-----|------4--------4-----4--|---4-----4--------------|
G|------6--------6-----6--|---6-----6--------------|6-----4--4-----4-----4--|---4-----4--------4-----|
D|------6--6-----6-----6--|---6-----6--------------|------2-----6-----------|------------6-----------|
A|7-----------------------|7--7--------------------|4-----------------------|4-----------------------|
E|------------7--7--------|------------7-----------|------------4--4--------|------------4--------5--|

e|------------------------|------------------------|---------------2--------|---4-----4--------------|
B|------5--5--------------|---7-----7--------7-----|------7--7--------------|---------0--------------|
G|------6--6--------------|---6-----6--4-----6-----|------6--6-----6--------|---8-----8--------------|
D|------5--5-----5--------|---6-----6--------6-----|------5--5-----5--------|---7-----7--------------|
A|------0--0--------------|7-----------------------|------0--------0--------|---------------------5--|
E|5-----------5-----5-----|------------7-----7-----|5-----------5--------5--|7-----7--------7--------|

e|------------------------|------------------------|------------------------|------------------------|
B|---------7-----7-----7--|---7-----7--------7-----|------4--4-----4-----4--|---4-----4--------4-----|
G|------6-----4--6-----6--|---6-----6--4-----6-----|------4--4-----4--------|6--4-----4--------4-----|
D|------6--------6-----6--|---6-----6--------6-----|------2-----6--2--------|---------2--------------|
A|7-----------------------|7--7--------------------|4-----4-----------------|4-----------------------|
E|---------5--7--7--------|------------7-----7-----|------4-----4--4--------|---------4--4-----4-----|

e|------------------------|------------------------|------2-----------------|------------------------|
B|------5-----------------|---7-----7--------7-----|---------------7--------|---10----9--------------|
G|------6--------9--------|---6-----6--------------|------6-----------------|------8-----------8-----|
D|------5--5--7--5--------|---6-----6--------------|------5-----7--5--------|---7--7-----------7-----|
A|------0--0--0--0--------|7-----7--------7-----5--|------0--------0--------|------------------------|
E|5-----------------------|---------------------5--|5--------5--5--------6--|7-----------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_BN3-154-E_comp
-----------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------7--7-----7-----7--|---7-----7--------7-----|------4--4-----4-----4--|---4-----4--------4-----|
G|------6--6-----6-----6--|---6-----6--------6-----|------4--4-----4-----4--|---4-----4--------4-----|
D|------6--6-----6-----6--|---6-----6--------5-----|------2--2-----2-----2--|---2-----2--------0-----|
A|7-----------------------|7-----------------------|4-----------------------|4-----------------------|
E|------------7-----------|------------7-----------|------------4-----------|------------4-----------|

e|------------------------|------------------------|------------------------|------------------------|
B|------5--5-----5-----0--|---7-----7--------7-----|------7--7-----7--------|---9-----9--------9-----|
G|------6--6-----6--------|---6-----6--------------|------6--6-----6--------|---8-----8--------8-----|
D|------5--5-----5--------|---6-----6--------6-----|------5--5-----5--------|---7-----7--------7-----|
A|------------------------|7-----------------------|------------------------|------------------------|
E|5-----------5-----------|------------7-----------|5-----------5--------5--|7-----7--------7--------|

e|------------------------|------------------------|------------------------|------------------------|
B|------7--7-----7-----7--|---7-----7--------7-----|------4--4-----4-----4--|---4-----4--------4-----|
G|------6--6-----6-----6--|---6-----6--------6-----|------4--4-----4-----4--|---4-----4--------4-----|
D|------6--6-----6-----6--|---6-----6--------6-----|------2--2-----2-----2--|---2-----2--------2-----|
A|7-----------------------|7-----------------------|4-----------------------|4-----------------------|
E|------------7-----------|------------7-----------|------------4-----------|------------4-----------|

e|------------------------|------------------------|------------------------|------------------------|
B|------5--5-----5-----0--|---7-----7--------7-----|------7--------7--------|---------9--------------|
G|------6--6-----6--------|---6-----6--------6-----|------6--------6--------|------8-----------------|
D|------5--5-----5--------|---6-----6--------6--0--|------5--------5--------|---7--------------------|
A|------------------------|7-----7--------7--------|------------------------|------------------------|
E|5-----------5-----------|------------------------|5--------5--5--------6--|7-----------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN3-154-E_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_BN3-154-E_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_Jazz1-200-B_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
71          50                   49                     42           0.8571          0.84        0.3636                          0.4286

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_Jazz1-200-B_solo — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------3--5--------3-----|---------3--4-----------|------------------------|
G|------------------------|2--4-----------------4--|---------------4--2-----|4-----------------------|
D|------------------2-----|------------------------|------------------------|------4--2--2-----------|
A|---------0--2-----------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------7-----6-----|---5--------------------|
G|------------------4--6--|7--6--7--6--------4--4--|---------4--------------|------------8-----------|
D|---------2--4-----------|------------------------|---------------8-----7--|---------6--------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|7--9-----11-------9-----|7--9-----------------19-|------------------------|
B|------------------7-----|------------------------|------12-12-------------|------------------------|
G|---------6--8-----------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|---------------16-------|
A|------------------------|---------10-------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|


========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_Jazz1-200-B_solo
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|------------------------|------7--9--------7-----|---------7--8-----------|------------------------|
D|------------------------|7--9--------------------|---------------9--7-----|9--7--------------------|
A|---------------5--7--9--|------------------------|------------------------|------9--7--------------|
E|---------5--7-----------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|------------------------|
G|---------------------6--|7--6--7--6--------------|------------11----10----|---9--------8-----------|
D|---------------6--9-----|------------------9--9--|---------9-----8-----7--|---------6--------------|
A|---------7--9-----------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|7--9-----11-------9-----|7--9--7--7--------------|------------------------|
B|------------------7-----|------------------------|------------------------|---------------7--------|
G|---------6--8--9--------|------------------------|------------------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------------|
B|---------------|
G|---------------|
D|---------------|
A|---------------|
E|---------------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Jazz1-200-B_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Jazz1-200-B_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_Rock1-130-A_comp
Method:    combined_all_tuned

     n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
110         312                  287                    261           0.9094        0.8365        0.1569                          0.1801

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_Rock1-130-A_comp — combined_all_tuned
-------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|2-----2--2--2-----2-----|---2--2-----2--2-----0--|2-----2-----2--2--2--2--|2-----2-----2--2--2--0--|
G|2--2--2--2--2--2--2--2--|2--2--2--2--2--2-----0--|------2--2--2--2--2--2--|2--2--2--2--2--2--2--0--|
D|2--2--2--2--2--2--2--2--|2--2--2--2--2--2-----0--|2-----2--2--2--2--2--2--|2--2--2--2--2--2--2--0--|
A|0-----0--0--0--0--0--0--|0--0--0--0--0--0--0-----|0-----0--0--0--0--0--0--|0--0--0--0--0--0--0-----|
E|------------------------|---------------------3--|------------------------|------------------------|

e|------2-----2--2--2-----|2-----2-----2-----------|------------------------|------------------------|
B|------3--3--3--3--3--3--|------3-----3--3--------|------2--2--2-----2-----|2-----2--2--2-----------|
G|2--2--2--2--2--2--2--2--|2--2--2--2--2--2--2--0--|------2--2--2--2--2--2--|2--2--2--2--2-----2-----|
D|0-----0--0--0--0--0--0--|0--0--0--0--0--0--0-----|------2--2--2--2--2--2--|2--2--2--2--2-----2-----|
A|0-----------------------|------------------0-----|0-----0--0--0--0--0--0--|0--0--0--0--0-----0-----|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|---2-----2--------------|------------------------|------------------4-----|
B|------5-----0-----------|---3--3--3--3--3--3--0--|------2--2--2--2--------|---------5--5-----------|
G|---4--1-----1--1--4--0--|---2--2--2--2--2--2--0--|------2--2--2--2--2--4--|---------7--------------|
D|---2--2-----2--2-----0--|0--0-----0--0--0--0-----|---2-----2--2--2--2--5--|---6--6--6--6-----------|
A|0-----------2--2--2--0--|---0-----0--0--0--0-----|0--0--0--0--0--0--0-----|---7-----7--------------|
E|0-----7-----0--0--------|------------------------|------------------------|------------0-----------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_Rock1-130-A_comp
-------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|------------------------|------------------------|------------------------|---------------------0--|
G|6--6--6--6--6--6--6--6--|6--6--6--6--6--6--6--4--|5-----6--6--6--6--6--6--|6--6--6--6--6--6--6--0--|
D|7--7--7--7--7--7--7--7--|7--7--7--7--7--7--7--5--|6-----7--7--7--7--7--7--|7--7--7--7--7--7--7--0--|
A|7--7--7--7--7--7--7--7--|7--7--7--7--7--7--7--5--|7-----7--7--7--7--7--7--|7--7--7--7--7--7--7-----|
E|5--5--5--5--5--5--5--5--|5--5--5--5--5--5--5--3--|5-----5--5--5--5--5--5--|5-----5--5--5--5--5-----|

e|------------------------|---------------------4--|------------------------|------------------------|
B|7-----7--7--7--7--7-----|7-----7--7--7--7--7--0--|------------------------|------------------------|
G|7--7--7--7--7--7--7--7--|7--7--7--7--7--7--7--0--|------6--6--6--6--6--6--|6--6--6--6--6-----6-----|
D|7-----7--7--7--7--7--7--|7--7--7--7--7--7--------|------7--7--7--7--7--7--|7--7--7--7--7-----7-----|
A|5-----5--5--5--5--5--5--|5--5--5--5--5--5--5-----|------7--7--7--7--7--7--|7--7--7--7--7-----7-----|
E|------------------------|------------------------|5-----5--------5-----5--|5--5--5--5--5-----5-----|

e|------0-----0--0--0-----|---2--2--2--2--2--2-----|------------------------|------------------------|
B|------0-----0--0--0-----|---3--3--3--3--3--3--0--|---------------------0--|---------5--------------|
G|------1-----1--1-----0--|---2--2--2--2--2--2-----|---6--6--6--6--6--6--0--|------7--7--------------|
D|------2-----2--2-----0--|0--0-----0--0--0--0-----|---7--7--7--7--7--7-----|---6--6-----------------|
A|0-----2-----2--2-----0--|---------------0--------|---7--7--7--7--7--7-----|---7--------------------|
E|0-----0-----0--0--------|------------------------|5--5--5-----5--5--5-----|------------------------|

e|------------|
B|------------|
G|------------|
D|------------|
A|------------|
E|------------|

[note: 4 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock1-130-A_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock1-130-A_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_Rock2-85-F_solo
Method:    combined_all_tuned

   n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
8         125                  127                    115           0.9055          0.92        0.7143                          0.7826

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_Rock2-85-F_solo — combined_all_tuned
------------------------------------------------------------------
e|9-----8--6--------------|------------------------|------------------------|------------------------|
B|------------------6-----|------------------------|------------------------|---------------11-------|
G|------------------8--6--|8-----6-----------------|---------5--------------|---------6--10----------|
D|------------------------|---------8--------------|---------6--3--4--------|---3--8-----------------|
A|10----------------------|------------------------|------------------------|---6--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------9--8--9--8--6--|------------------------|------------13----------|------------11-20-8--9--|
B|---------------------7--|8--6--5--8--------------|------6--13----13-9-----|---------10----13-------|
G|------------------------|---------6--5--1--------|------------------------|------------------------|
D|------------------------|------5-----------------|3--6--------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|9--8--6-----------------|------------------9--8--|------------------------|------------------------|
B|------6-----------------|------------8--9--------|------9-----------------|------------------------|
G|---------8--6-----------|---------6--------------|---------8--------------|------3--6--5--5--5-----|
D|------------------------|------------------------|------------10-6--------|---3--------------------|
A|------------------------|------------------------|---------------8--6--3--|---4--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------8--9--6-----|------------------------|------------8--11-12-13-|13----------------------|
B|---------8-----------8--|5--6--------------------|---------9--------------|------13-9--------------|
G|---------5--------------|------6--3--1--------0--|------5-----------------|------------10----------|
D|------------------------|------------------------|2--6--------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---|
B|---|
G|---|
D|---|
A|---|
E|---|

[note: 31 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_Rock2-85-F_solo
------------------------------------------
e|9-----8-----------------|------------------------|------------------------|---------------6--------|
B|---------11-------------|------------------------|------------------------|------------6--9--------|
G|------------------8--6--|8-----6-----------------|---------5--------------|---------6--8-----------|
D|------------------------|---------8--------------|---------6--5-----------|------6--8--------------|
A|------------------------|------------------------|---------------8--------|---8--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|---------9--8--9--8--6--|------------------------|------------13-8--------|------------11-8--8--9--|
B|------------------------|8--6--5--8--------------|------6--9--------9-----|------------10----------|
G|------------------------|---------6--5-----------|------------------------|------------------------|
D|------------------------|---------------8--6-----|---6--------------------|------------------------|
A|------------------------|------------------------|8-----------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|9--8--------------------|---------------6--9--8--|------------------------|------------------------|
B|------11----------------|------------8--9--------|------9--6--------------|------------------------|
G|------10-8--6-----------|---------8--------------|---------8--5-----------|------3--6--5--5--5-----|
D|------------------------|------------------------|---------------6--1-----|------6-----------------|
A|------------------------|------------------------|---------------8--6--3--|5--4--------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------8--9--6-----|------------------------|------------8-----12-13-|13----------------------|
B|---------8-----------8--|5--6--------------------|---------9--------------|---------13-------------|
G|---------5--------------|------6--5--------------|------5-----------------|---------13-------------|
D|------------------------|------------6--------5--|---6--------------------|------------15----------|
A|------------------------|------------------------|7--8--------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

[note: 27 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock2-85-F_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock2-85-F_solo__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_Rock3-117-Bb_comp
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
80         398                  341                    308           0.9032        0.7739        0.3545                          0.4253

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_Rock3-117-Bb_comp — combined_all_tuned
--------------------------------------------------------------------
e|------------------------|------------------------|------------------------|------------------------|
B|3-----3--3--------3-----|------6-----------------|------------------------|------6-----------6-----|
G|3--3--3--3-----3--3-----|5--5--5--5--5--5--5-----|------3--------------0--|------7-----7-----------|
D|3--3--3--3--3--3--3--0--|3--3--3--3--3--3--3--5--|------5--5--5--5--5--0--|7--7--7--7--7--7--7--5--|
A|1--1--1--1--1--1--1-----|---------------------5--|------5--------5--5-----|5--5--5--5--5-----5--5--|
E|---------------------5--|---------------------5--|3-----3--3--3--3--3--5--|------------------------|

e|------------------------|------1-----6-----------|---------------3--------|------5-----------5-----|
B|------8-----------8-----|------3--3--3-----3-----|---4--4-----4--4--4--5--|6--6--6--6--6--6--6-----|
G|---8--8-----8--8--8-----|------3--3--3--3--3--0--|3--3--3--3--3--3--3--4--|5--5--5--5--5--5--5--4--|
D|8-----8--8--8--8--8--5--|3-----3--3--3--3--3-----|---------------------2--|3--3--3--3--3--3--3-----|
A|6-----6-----6--6--6--5--|------1--1-----1--1--5--|6--6--6--6--6--6--6-----|---------------------7--|
E|------------------------|6-----------6-----------|------------------------|------------------------|

e|------------------------|------5-----------5-----|------------------------|------------------------|
B|------3-----------3-----|---6--6--6--------6-----|------------------8-----|---6--6--6--------6-----|
G|---------------3-----0--|5--5--5--5--5--5--5-----|------3--3-----------0--|------7--7--7-----------|
D|------8-----------8-----|3--3--3--3--3--3--3--5--|------5--5-----5--5--0--|7--7--7--7--7--7--7--5--|
A|8-----8--------8--8--5--|---------------------5--|------5--5--5--5--5-----|5--5--5--5--5--5--5-----|
E|6-----6-----6--6--6-----|---------1--------------|3-----3--3-----3--3--5--|5--5--5-----------------|

e|------------------3-----|------------------------|------------------------|------------------5-----|
B|---4--4--4--4-----4-----|------3-----------3-----|4--4--4--4--4--4--4-----|---6-----6--6-----6-----|
G|3-----3--3--3-----------|---3--3--3--3-----3--0--|3--3--3--3--3--3--3-----|5--5--5--5--5--5--5-----|
D|------------------8--5--|3-----3--3--3--3-----0--|------------------------|------------------------|
A|6-----6--6--6--6--6--5--|------1--1--1-----8-----|6--6--6--6--6--6--6-----|8--8--8--8--8--8--8-----|
E|------------------------|6--------------6--6--5--|---------------------5--|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 1 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_Rock3-117-Bb_comp
--------------------------------------------
e|------------------------|------------------------|------------------------|------------------5-----|
B|------------------------|------10----------10----|------3-----------3-----|------6--6--6-----6-----|
G|7-----7--7-----7--7-----|10-10-10-10-10-10-10----|------3--3--3-----3--0--|------7--7--7-----7--0--|
D|8--8--8--8--8--8--8--0--|10-10-10-10-10-10-10-0--|------5--5--5--5--5--0--|7--7--7--7--7--7--7--0--|
A|8--8--8--8--8--8--8--0--|8--8--8--8--8--8--8-----|------5--5--5--5--5--0--|5--5--5--5--5--5--5-----|
E|6--6--6--6--6--6--6-----|------------------------|3--3--3--3--3--3--3--0--|------------------------|

e|------------------------|------6-----------6-----|------------------------|------------------------|
B|------8--8--------8-----|------6--6--6-----6-----|---------------8--8--9--|10----10----------10----|
G|------8--8--8--8--8--0--|------7--7--7--7--7--0--|------8--8--8--8--8--9--|10----10-10-10-10-10----|
D|8--8--8-----8--8--8--0--|------8--8--8--8--8--0--|8--8--8--8--8--8--8--9--|10-10-10-10-10-10-10----|
A|6--6--6-----6--6--6-----|8-----8--8--8--8--8--7--|6--6--6--6--6--6--6--7--|8--8--8--8--8--8--8-----|
E|------------------------|6-----6--------6--6--0--|------------------------|------------------------|

e|------6-----------6-----|------------------------|------3-----------3-----|------5-----------5-----|
B|------6-----------6-----|------10-10-------10----|------3-----------3-----|6--6--6--6--------6-----|
G|------7--------7--7--0--|10-10-10-10-10-10-10-0--|------3--3-----3--3--0--|---7--7--7--7--7--7--0--|
D|------8--------8--8-----|10-10-10-10-10-10-10-0--|------5--5-----5--5--0--|7--7--7--7--7--7--7--0--|
A|8-----8--------8--8-----|8--8--8--8--8--8--8-----|------5--------5--5--0--|5--5--5--5--5--5--5-----|
E|6-----6-----6--6-----0--|------------------------|3-----3-----3--3--3--0--|------------------------|

e|------------------------|------------------6-----|------------------------|------------------------|
B|------8-----------8-----|------6-----------6-----|------------------8-----|------------------10----|
G|8-----8--8--8--8--8--0--|------7--7--7-----7--0--|------8--8--8--8--8-----|10-10-10-10-10-10-10----|
D|8-----8--8--8--8--8--0--|------8--8--8--8--8--0--|8--8--8--8--8--8--8--0--|10-10-10-10-10-10-10----|
A|6-----6--6--6--6--6--0--|8-----8--8--8--8--8--0--|6--6--6--6--6--6--6--0--|8--8--8--8--8--8--8-----|
E|------------------------|6-----6--6--6--6--6--0--|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|


Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock3-117-Bb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_Rock3-117-Bb_comp__ground_truth_midi_tab.txt
========================================================================================
Recording: 05_SS2-88-F_solo
Method:    combined_all_tuned

    n_gt_notes  n_basic_pitch_notes  n_pitch_onset_matches  pitch_precision  pitch_recall  exact_tab_f1  tab_accuracy_given_pitch_match
14          93                   96                     91           0.9479        0.9785         0.709                          0.7363

========================================================================================
REAL AUDIO → BASIC PITCH → ALGORITHM TAB
========================================================================================
REAL AUDIO PREDICTED TAB — 05_SS2-88-F_solo — combined_all_tuned
----------------------------------------------------------------
e|---------6--8--9--6-----|------------------------|------------------------|------------------------|
B|---------6-----------6--|---------6--------------|------------9--11-9--8--|6-----------------6--9--|
G|------------------------|------------8-----------|---------8--------------|------------------------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|------------------5--8--|
B|8--------------8--------|------------------8--6--|6-----------------6-----|------------------6-----|
G|---------10-9-----5-----|---------6--5--9--------|------5-----------------|---------------5--------|
D|------------------------|------------------------|---------6--8--6--------|------------6-----------|
A|------------------------|------------------------|---------8--------8-----|---------8--------------|
E|------------------------|------------------------|------------------------|------------------------|

e|9--------6--------------|---------------6-----8--|8--------8--------------|------------------------|
B|------------6-----------|---------6--9-----------|---------6--4-----------|---------------8--9--13-|
G|------------------------|------------------------|------------------------|---------6--8-----------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------18----8--8--|------------------------|------------------------|
B|11-------------9--8-----|---------11-11-11-------|9--------------6-----8--|6-----------------------|
G|------------------------|------------------------|---------10-8--------8--|---------5--------------|
D|------------------------|------------------------|---------10-------------|------------6--2--3--6--|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------|
B|------|
G|------|
D|------|
A|------|
E|------|

[note: 18 same-grid-cell collisions; later note shown]

========================================================================================
GUITARSET GROUND-TRUTH MIDI TAB
========================================================================================
GROUND TRUTH MIDI TAB — 05_SS2-88-F_solo
----------------------------------------
e|---------6--8--9--6-----|------------------------|------------------------|------------------------|
B|---------6-----------6--|---------6--------------|------------9--11-9--8--|---------------------9--|
G|------------------------|---------6--8-----------|---------8--------------|10----------------10----|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|------------------------|------------------------|------------------------|---------------------8--|
B|8--------------8--------|---------------5--8--6--|------------------------|------------------10----|
G|---------10-9-----5-----|---------6--5--6--------|------5-----------------|------------------10----|
D|------------------------|------------------------|---------6--8--6--------|------------6--10-------|
A|------------------------|------------------------|---------8--------8-----|---------8--------------|
E|------------------------|------------------------|------------------------|------------------------|

e|9--------8--------------|---------------------8--|8-----------------------|---------------------8--|
B|---------11-------------|------------9--11-------|---------9--------------|---------------8--9-----|
G|------------10----------|---------10-------------|---------10-8-----------|---------6--8-----------|
D|------------------------|------------------------|------------------------|------------------------|
A|------------------------|------------------------|------------------------|------------------------|
E|------------------------|------------------------|------------------------|------------------------|

e|6-----------------------|---------6--6--6--8--8--|------------------------|------------------------|
B|---------------9--8-----|------------------------|9--------------------8--|------------------------|
G|------------------------|------------------------|---------10-8--10----8--|10-------7-----------5--|
D|------------------------|------------------------|---------10-------------|---------10-6--5-----6--|
A|------------------------|------------------------|------------------------|------------------8-----|
E|------------------------|------------------------|------------------------|------------------------|

e|---------|
B|---------|
G|---------|
D|---------|
A|---------|
E|---------|

[note: 13 same-grid-cell collisions; later note shown]

Saved ASCII tabs:
 - real_audio_predicted_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_SS2-88-F_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ground_truth_midi_tab: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/05_SS2-88-F_solo__ground_truth_midi_tab.txt

Exported 108 ASCII tab files.
Index: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/ascii_tabs/exported_ascii_tabs__combined_all_tuned.txt
Final audio output folder:
/content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout

CSV files currently in audio output folder:
 - audio_to_tab_eval_by_recording.csv
 - audio_to_tab_eval_summary.csv
 - audio_to_tab_failed_runs.csv
 - audio_to_tab_matches.csv
 - audio_to_tab_predictions_all.csv
 - audio_to_tab_report_table_heldout_test.csv

ASCII tab files currently in audio output folder:
 - ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__matched_only_ground_truth_tab.txt
 - ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__matched_only_real_audio_predicted_tab.txt
 - ascii_tabs/00_Funk1-114-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Funk1-114-Ab_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_Funk1-97-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Funk1-97-C_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_Funk2-108-Eb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Funk2-108-Eb_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_Jazz3-150-C_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Jazz3-150-C_comp__ground_truth_midi_tab.txt
 - ascii_tabs/00_Rock2-142-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Rock2-142-D_comp__ground_truth_midi_tab.txt
 - ascii_tabs/00_Rock2-85-F_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Rock2-85-F_comp__ground_truth_midi_tab.txt
 - ascii_tabs/00_Rock3-117-Bb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Rock3-117-Bb_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_Rock3-148-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_Rock3-148-C_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_SS2-107-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_SS2-107-Ab_solo__ground_truth_midi_tab.txt
 - ascii_tabs/00_SS3-84-Bb_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/00_SS3-84-Bb_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_BN1-129-Eb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_BN1-129-Eb_comp__ground_truth_midi_tab.txt
 - ascii_tabs/01_BN2-131-B_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_BN2-131-B_comp__ground_truth_midi_tab.txt
 - ascii_tabs/01_BN3-154-E_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_BN3-154-E_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_Jazz1-130-D_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_Jazz1-130-D_comp__ground_truth_midi_tab.txt
 - ascii_tabs/01_Rock2-142-D_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_Rock2-142-D_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_Rock2-85-F_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_Rock2-85-F_comp__ground_truth_midi_tab.txt
 - ascii_tabs/01_SS1-100-C__comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_SS1-100-C__comp__ground_truth_midi_tab.txt
 - ascii_tabs/01_SS1-68-E_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_SS1-68-E_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_SS2-107-Ab_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_SS2-107-Ab_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_SS2-88-F_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_SS2-88-F_solo__ground_truth_midi_tab.txt
 - ascii_tabs/01_SS3-98-C_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/01_SS3-98-C_solo__ground_truth_midi_tab.txt
 - ascii_tabs/02_BN1-147-Gb_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/02_BN1-147-Gb_comp__ground_truth_midi_tab.txt
 - ascii_tabs/02_BN2-131-B_solo__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/02_BN2-131-B_solo__ground_truth_midi_tab.txt
 - ascii_tabs/02_Funk1-97-C_comp__combined_all_tuned__real_audio_predicted_tab.txt
 - ascii_tabs/02_Funk1-97-C_comp__ground_truth_midi_tab.txt

,method,recordings,n_gt_notes,n_basic_pitch_notes,pitch_precision,pitch_recall,pitch_f1,exact_tab_precision,exact_tab_recall,exact_tab_f1,tab_accuracy_given_pitch_match,string_accuracy_given_pitch_match,fret_accuracy_given_pitch_match,mean_runtime_sec_per_recording
1,caged_voiced,54,10207,9561,0.802,0.7512,0.7758,0.5549,0.5197,0.5367,0.6918,0.6918,0.6918,0.7057
0,caged_box,54,10207,9561,0.802,0.7512,0.7758,0.5497,0.5149,0.5318,0.6854,0.6854,0.6854,1.8391
2,combined_all_tuned,54,10207,9561,0.802,0.7512,0.7758,0.5191,0.4862,0.5021,0.6472,0.6472,0.6472,0.7478

Saved report table to: /content/drive/MyDrive/Capstone/outputs/audio_to_tab_basic_pitch_heldout/audio_to_tab_report_table_heldout_test.csv

Interpretation:
The previous held-out result measured fretboard assignment using ground-truth GuitarSet notes.
This result starts from raw audio, runs Basic Pitch first, then predicts string/fret positions.
So exact_tab_f1 is the stricter end-to-end audio-to-tab metric.
Matched notes (detected + pitch-correct): 7668
  exact-correct placement : 5256  (68.5%)
  wrong placement         : 2412  (31.5%)

Of the WRONG notes — how many strings off:
  |Δstring|=1:  2309  (95.7%)  ADJACENT (one string off)
  |Δstring|=2:    88  ( 3.6%)  two strings off
  |Δstring|=3:    14  ( 0.6%)  three strings off
  |Δstring|=5:     1  ( 0.0%)  5 off

>>> 95.7% of wrong notes are exactly ONE string off (adjacent).
>>> That's 30.1% of all matched notes (the rest place correctly or miss by 2+ strings).

Fret-diff distribution (sanity: adjacent swaps cluster at ±4/±5):
fret_diff
-10       4
-9       20
-5     1190
-4      400
 4      246
 5      473
 9       53
 10      11
 14       6
 15       8
 24       1
Adjacent errors — solo vs comp:
kind
comp    1438
solo     871
Name: count, dtype: int64

Which string pair gets confused:
pair
G–B    646
D–G    605
B–e    467
A–D    373
E–A    218
Name: count, dtype: int64

Direction:
direction
to thinner/higher string    0.689
to thicker/lower string     0.311
Name: proportion, dtype: float64

slice                  ALL    comp    solo
method
caged_box           0.6854  0.7199  0.6105
caged_voiced        0.6918  0.7308  0.6072
combined_all_tuned  0.6472  0.6677  0.6026

All required symbols present. VAL: 54 TEST: 54

## 3. Monkey-patch `run_basic_pitch_notes` (threshold-aware + threshold-keyed cache)

Identical body to yours, with two changes: it reads module-level `BP_ONSET_THRESHOLD` / `BP_FRAME_THRESHOLD` and passes them to `basic_pitch_predict`, and the cache filename encodes the thresholds so each operating point caches separately. **The threshold-aware cache key is the critical bit** — your original key is filename-only, so without this every sweep step after the first would silently reload the first threshold's notes.

In [5]:
import pandas as pd, numpy as np

# Globals the patched runner reads. The sweep sets these before each eval pass.
BP_ONSET_THRESHOLD = 0.5   # Basic Pitch library default
BP_FRAME_THRESHOLD = 0.3

def _basic_pitch_cache_path_thr(audio_path, onset_threshold, frame_threshold):
    safe = Path(audio_path).stem.replace('/', '_')
    return BASIC_PITCH_CACHE_DIR / f'{safe}_on{onset_threshold:.2f}_fr{frame_threshold:.2f}_bp_notes.csv'

def run_basic_pitch_notes(audio_path,
                          amplitude_threshold=BASIC_PITCH_AMPLITUDE_THRESHOLD,
                          min_midi=BASIC_PITCH_MIN_MIDI,
                          max_midi=BASIC_PITCH_MAX_MIDI,
                          use_cache=True,
                          onset_threshold=None,
                          frame_threshold=None):
    """Patched: threshold-aware Basic Pitch + threshold-keyed cache. Falls back to BP_* globals."""
    if onset_threshold is None: onset_threshold = BP_ONSET_THRESHOLD
    if frame_threshold is None: frame_threshold = BP_FRAME_THRESHOLD
    audio_path = Path(audio_path)
    cache_path = _basic_pitch_cache_path_thr(audio_path, onset_threshold, frame_threshold)

    if use_cache and cache_path.exists():
        return pd.read_csv(cache_path).to_dict('records')

    _, _, note_events = basic_pitch_predict(str(audio_path),
                                            onset_threshold=onset_threshold,
                                            frame_threshold=frame_threshold)
    notes = []
    for event in note_events:
        start, end, pitch_midi, amplitude = event[0], event[1], event[2], event[3]
        if float(amplitude) < amplitude_threshold:
            continue
        midi = int(round(float(pitch_midi)))
        if midi < min_midi or midi > max_midi:
            continue
        notes.append({
            'start': float(start),
            'duration': float(end - start),
            'midi': midi,
            'pitch_class': midi % 12,
            'note_name': midi_to_note_name_simple(midi),
            'amplitude': float(amplitude),
            'true_string': None,
            'true_fret': None,
            'source': 'basic_pitch',
        })
    notes = sorted(notes, key=lambda n: (n['start'], n['midi']))
    pd.DataFrame(notes).to_csv(cache_path, index=False)
    return notes

# Rebind the name in the module namespace so evaluate_audio_to_tab_record() calls the patched version.
import sys
setattr(sys.modules['__main__'], 'run_basic_pitch_notes', run_basic_pitch_notes)
print("Patched run_basic_pitch_notes (threshold-aware + threshold-keyed cache).")

Patched run_basic_pitch_notes (threshold-aware + threshold-keyed cache).

## 4. Pair validation + test records with audio

Mirrors how your cell 35 builds `paired_records` over `TEST_RECORDS`, applied to both splits.

In [6]:
def pair_records(records):
    pairs, missing = [], []
    for r in records:
        ap = find_audio_for_record(r)
        (missing if ap is None else pairs).append(r['recording'] if ap is None else (r, ap))
    return pairs, missing

paired_val, miss_val = pair_records(VAL_RECORDS)
paired_test, miss_test = pair_records(TEST_RECORDS)
print(f"Validation paired: {len(paired_val)}/{len(VAL_RECORDS)}  (missing {len(miss_val)})")
print(f"Test paired:       {len(paired_test)}/{len(TEST_RECORDS)}  (missing {len(miss_test)})")
if miss_val[:5]: print("  e.g. missing val:", miss_val[:5])

Validation paired: 54/54  (missing 0)
Test paired:       54/54  (missing 0)

## 5. Sweep helper

For a given `(onset, frame)`, sets the globals and runs your unchanged `evaluate_audio_to_tab_record` over the paired records for one method. Aggregates `exact_tab_f1` **pooled** (summed TP / summed predicted / summed GT) — the same way your `audio_summary_df` does — so numbers match your pipeline. TDR and playability proxies are averaged for context.

In [7]:
def eval_pairs_at_threshold(paired, onset_t, frame_t, method, label=''):
    global BP_ONSET_THRESHOLD, BP_FRAME_THRESHOLD
    BP_ONSET_THRESHOLD, BP_FRAME_THRESHOLD = onset_t, frame_t
    assign_fn = AUDIO_ASSIGNMENT_METHODS[method]
    rows, all_matches = [], []
    for record, audio_path in paired:
        metrics, _assigned, matches_df = evaluate_audio_to_tab_record(record, audio_path, assign_fn, method)
        rows.append(metrics)
        if matches_df is not None and len(matches_df):
            all_matches.append(matches_df)
    df = pd.DataFrame(rows)
    tp  = df['exact_tab_tp'].sum()
    npr = df['n_basic_pitch_notes'].sum()
    ngt = df['n_gt_notes'].sum()
    P = tp/npr if npr else 0.0
    R = tp/ngt if ngt else 0.0
    f1 = 2*P*R/(P+R) if (P+R) else 0.0
    # TDR weighted by matched-note count (matches your summary's _safe_weighted_avg)
    w = df['n_pitch_onset_matches'].fillna(0).astype(float)
    tdr = float(np.average(df['tab_accuracy_given_pitch_match'].fillna(0), weights=w)) if w.sum() else float('nan')
    pitch_recall = df['pitch_recall'].mean()
    out = {'onset': onset_t, 'frame': frame_t, 'method': method,
           'exact_tab_f1': f1, 'exact_tab_precision': P, 'exact_tab_recall': R,
           'TDR': tdr, 'pitch_recall_mean': pitch_recall,
           'n_pred': int(npr), 'n_gt': int(ngt), 'n_match': int(df['n_pitch_onset_matches'].sum())}
    if label:
        print(f"  [{label}] onset={onset_t:.2f} frame={frame_t:.2f}  "
              f"exact_tab_f1={f1:.4f}  P={P:.3f} R={R:.3f}  TDR={tdr:.4f}")
    matches_cat = pd.concat(all_matches, ignore_index=True) if all_matches else pd.DataFrame()
    return out, matches_cat

## 6. Sweep on VALIDATION → pick by `exact_tab_f1`

First pass runs `predict()` at each threshold, so it is the slow part (~15-25 min for 8 thresholds × validation set). The threshold-keyed cache makes any re-run instant. `caged_voiced` is the default method; change `METHOD` to sweep a different one.

In [8]:
METHOD = 'caged_voiced'                       # 'caged_box' | 'caged_voiced' | 'combined_all_tuned'
ONSET_GRID = [0.30, 0.40, 0.50, 0.60, 0.65, 0.70, 0.75, 0.80]
FRAME_T = 0.30                                # held fixed; see optional frame sweep below

print(f"Sweeping onset on VALIDATION  |  method={METHOD}  |  {len(paired_val)} recordings")
val_rows = []
for ot in ONSET_GRID:
    res, _ = eval_pairs_at_threshold(paired_val, ot, FRAME_T, METHOD, label='VAL')
    val_rows.append(res)

val_df = pd.DataFrame(val_rows)
best = val_df.loc[val_df['exact_tab_f1'].idxmax()]
best_onset = float(best['onset'])
print("\nValidation sweep:")
display(val_df[['onset','frame','exact_tab_f1','exact_tab_precision','exact_tab_recall','TDR']].round(4))
print(f"\n>>> Best onset on validation by exact_tab_f1: {best_onset:.2f} "
      f"(val exact_tab_f1={best['exact_tab_f1']:.4f}, default 0.50 baseline below)")

Sweeping onset on VALIDATION  |  method=caged_voiced  |  54 recordings
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz2-187-F#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN3-154-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock1-90-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-130-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-112-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN1-129-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-110-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk3-112-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz3-137-Eb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-68-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-150-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock2-142-D_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-137-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS3-84-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-114-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock3-148-C_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk2-119-G_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-88-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-90-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock3-117-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk2-108-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock2-85-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Jazz2-110-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-131-B_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS3-84-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk3-98-A_solo_mic.wav...
  [VAL] onset=0.30 frame=0.30  exact_tab_f1=0.4350  P=0.388 R=0.495  TDR=0.6757
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz2-187-F#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN3-154-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock1-90-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-130-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-112-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN1-129-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-110-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk3-112-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz3-137-Eb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-68-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-150-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock2-142-D_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-137-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS3-84-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-114-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock3-148-C_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk2-119-G_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-88-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-90-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock3-117-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk2-108-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock2-85-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Jazz2-110-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-131-B_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS3-84-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk3-98-A_solo_mic.wav...
  [VAL] onset=0.40 frame=0.30  exact_tab_f1=0.4731  P=0.445 R=0.505  TDR=0.6728
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz2-187-F#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN3-154-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock1-90-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-130-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-112-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN1-129-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-110-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk3-112-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz3-137-Eb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-68-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-150-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock2-142-D_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-137-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS3-84-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-114-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock3-148-C_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Funk2-119-G_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN1-147-Gb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-88-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-107-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-90-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock3-117-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk2-108-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock2-85-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz2-187-F#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Jazz2-110-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-131-B_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS3-84-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk3-98-A_solo_mic.wav...
  [VAL] onset=0.50 frame=0.30  exact_tab_f1=0.4885  P=0.481 R=0.496  TDR=0.6656
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-98-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz2-187-F#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_BN3-154-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock1-90-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN2-166-Ab_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-130-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-112-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk3-98-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN1-129-Eb_comp_mic.wav...

   onset  frame  exact_tab_f1  exact_tab_precision  exact_tab_recall     TDR
0   0.30    0.3        0.4350               0.3879            0.4951  0.6757
1   0.40    0.3        0.4731               0.4448            0.5052  0.6728
2   0.50    0.3        0.4885               0.4813            0.4958  0.6656
3   0.60    0.3        0.4854               0.5017            0.4701  0.6528
4   0.65    0.3        0.4843               0.5142            0.4577  0.6510
5   0.70    0.3        0.4807               0.5243            0.4438  0.6504
6   0.75    0.3        0.4692               0.5255            0.4237  0.6434
7   0.80    0.3        0.4512               0.5217            0.3974  0.6372

>>> Best onset on validation by exact_tab_f1: 0.50 (val exact_tab_f1=0.4885, default 0.50 baseline below)

## 7. Report on TEST once — best vs default

In [9]:
res_best, m_best = eval_pairs_at_threshold(paired_test, best_onset, FRAME_T, METHOD)
res_def,  m_def  = eval_pairs_at_threshold(paired_test, 0.50,       FRAME_T, METHOD)

cmp = pd.DataFrame([{'config': f'tuned onset={best_onset:.2f}', **res_best},
                    {'config': 'default onset=0.50',           **res_def}])
print(f"TEST results — method={METHOD}")
display(cmp[['config','exact_tab_f1','exact_tab_precision','exact_tab_recall','TDR','n_pred','n_match']].round(4))

delta = res_best['exact_tab_f1'] - res_def['exact_tab_f1']
print(f"\nDelta exact_tab_f1 (tuned - default): {delta:+.4f}")
if delta > 0.003:
    print("Tuning the onset threshold gives a real end-to-end tab improvement. Bank it.")
elif delta < -0.003:
    print("Default is better here; the validation pick didn't transfer. Keep onset=0.50.")
else:
    print("Flat. Your operating point was already well-chosen — a clean, reportable null.")

Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN2-131-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock2-142-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock2-85-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz3-137-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS1-100-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Funk2-119-G_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS2-107-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN2-131-B_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_BN3-119-G_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Jazz3-150-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Rock3-117-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN1-147-Gb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock1-90-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS1-68-E_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN1-129-Eb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Rock1-130-A_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-107-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN3-154-E_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/GuitarSet/Audio/00_Funk1-97-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS1-68-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Rock1-90-C#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk3-112-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Jazz1-200-B_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_SS1-68-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock3-148-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock3-117-Bb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock3-148-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN3-154-E_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_Funk1-97-C_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock2-85-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock2-142-D_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_Rock1-130-A_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Jazz3-150-C_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_Rock2-85-F_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz2-187-F#_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/05_BN3-119-G_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Jazz1-130-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS3-98-C_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_SS3-84-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_BN1-147-Gb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/04_Rock2-142-D_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_SS2-88-F_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk1-114-Ab_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_SS1-100-C#_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/02_BN1-147-Gb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/01_BN1-129-Eb_comp_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Rock3-117-Bb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/00_Funk2-108-Eb_solo_mic.wav...
Predicting MIDI for /content/drive/MyDrive/Capstone/FullGuitarSetData/AudioFiles/03_BN3-154-E_comp_mic.wav...
TEST results — method=caged_voiced

               config  exact_tab_f1  exact_tab_precision  exact_tab_recall     TDR  n_pred  n_match
0    tuned onset=0.50        0.5372               0.5553            0.5201  0.6924    9560     7668
1  default onset=0.50        0.5372               0.5553            0.5201  0.6924    9560     7668

Delta exact_tab_f1 (tuned - default): +0.0000
Flat. Your operating point was already well-chosen — a clean, reportable null.

## 8. Playability check at the winning threshold

A higher onset threshold feeds fewer, cleaner notes into the CAGED layer. Confirm that didn't worsen the hand-motion profile even if tab F1 rose. Compares fret-jump proxies on the matched notes, tuned vs default.

In [10]:
def playability_proxies(matches_df):
    if matches_df is None or matches_df.empty or 'pred_fret' not in matches_df:
        return {}
    d = matches_df.dropna(subset=['pred_fret']).copy()
    d = d.sort_values(['recording','pred_start'])
    jumps = d.groupby('recording')['pred_fret'].apply(lambda s: s.astype(float).diff().abs())
    jumps = jumps.dropna()
    return {'n_matched_notes': int(len(d)),
            'avg_fret_jump': float(jumps.mean()) if len(jumps) else float('nan'),
            'large_jump_rate(>4)': float((jumps > 4).mean()) if len(jumps) else float('nan'),
            'mean_pred_fret': float(d['pred_fret'].astype(float).mean())}

play = pd.DataFrame([{'config': f'tuned onset={best_onset:.2f}', **playability_proxies(m_best)},
                     {'config': 'default onset=0.50',            **playability_proxies(m_def)}])
print("Playability proxies on matched notes (lower jump = stiller hand):")
display(play.round(4))
print("\nIf avg_fret_jump / large_jump_rate are flat or lower at the tuned threshold, the F1 gain is clean.")

Playability proxies on matched notes (lower jump = stiller hand):

               config  n_matched_notes  avg_fret_jump  large_jump_rate(>4)  mean_pred_fret
0    tuned onset=0.50             7668         1.5201               0.0503          4.9791
1  default onset=0.50             7668         1.5201               0.0503          4.9791

If avg_fret_jump / large_jump_rate are flat or lower at the tuned threshold, the F1 gain is clean.

## 9. (Optional) Joint onset × frame sweep on validation

Frame threshold controls note sustain/segmentation; usually secondary to onset, but cheap to check once the cache is warm for the onset values above. Uncomment to run.

In [ ]:
# FRAME_GRID = [0.20, 0.30, 0.40]
# joint = []
# for ot in ONSET_GRID:
#     for ft in FRAME_GRID:
#         res, _ = eval_pairs_at_threshold(paired_val, ot, ft, METHOD)
#         joint.append(res)
# joint_df = pd.DataFrame(joint).sort_values('exact_tab_f1', ascending=False)
# display(joint_df[['onset','frame','exact_tab_f1','exact_tab_precision','exact_tab_recall','TDR']].round(4).head(12))
# bj = joint_df.iloc[0]
# print(f"Best (onset,frame) on val: ({bj['onset']:.2f},{bj['frame']:.2f})  exact_tab_f1={bj['exact_tab_f1']:.4f}")
# # Then re-run Section 7 with FRAME_T = bj['frame'] and best_onset = bj['onset'] to confirm on TEST once.